### ISSUE TITLE
cannot clear token from package

### ISSUE THREAD

**Issue by draeath** [atom/github#1017]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? N/A
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? N/A
* Have you checked the FAQs on the [message board][message-board] for common solutions? N/A
* Have you checked that your issue [isn't already filed][already-filed]? Yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

No means to manage the GitHub API token

### Steps to Reproduce

Settings -> Packages -> github -> Settings

**Expected behavior:**

Some mechanism to remove or change the API token for github to be visible 

**Actual behavior:**

Various settings including keybinds, but nothing to do with authentication

**Reproduces how often:**

N/A

### Versions

    $ atom --version
    Atom    : 1.18.0
    Electron: 1.3.15
    Chrome  : 52.0.2743.82
    Node    : 6.5.0
    
    $ apm --version
    apm  1.18.1
    npm  3.10.10
    node 6.9.5 x64
    python 2.7.13
    git 2.7.4
    
    $ lsb_release --description
    Description:	Ubuntu 16.04.2 LTS

### Additional Information

I did try to locate where this data is stored, to no avail - I searched in the repo `.git/config` as well as in `~/.atom`. The best I could do was to revoke access via GitHub, but the tab in atom instead repeatedly tries to authenticate. The API key is still stashed somewhere.

**Comment by hueitan** [comment]
I'm getting the same issue that it only allows me to try again, I can't log out or clear the tokens.

![screen shot 2017-07-26 at 10 16 08](https://user-images.githubusercontent.com/2560096/28611281-89285878-71eb-11e7-8474-980ae3fe98d6.png)

**Comment by Xav83** [comment]
I encountered the same problem and found a workaround.
To be able to log in with a new token, I went to my `Github settings`, in the section `Authorized OAuth Apps` ([here](https://github.com/settings/applications)) and revoked the apps related to Atom.
Then, when launching Atom again, the login button was available again 😃 

Hope this will help you 😉

**Comment by draeath** [comment]
Hey Xav83, I did try that to no avail. "The best I could do was to revoke access via GitHub, but the tab in atom instead repeatedly tries to authenticate."
