### ISSUE TITLE
Inline diffs

### ISSUE THREAD

**Issue by joshaber** [atom/github#103]
https://atom.io/packages/git-diff-details is a cool new package using block decorations so show diffs inline. We should/could probably do something similar, but prettier because @simurai.

![68747470733a2f2f6769746875622e636f6d2f73616d752f6769742d646966662d64657461696c732f626c6f622f6d61737465722f64656d6f2e706e673f7261773d74727565](https://cloud.githubusercontent.com/assets/13760/14000583/29fe1edc-f118-11e5-94d2-584e5b1c58a1.png)

**Comment by varemenos** [comment]
Sorry for bumping this thread, the latest version of vscode includes this feature and the git-diff-details package is not maintained and no longer works.

It would be really code to click on the gutter with the colored diff status (green, yellow, red) and be able to see the diff, plus have the ability to quickly revert the action or copy the previous state.

**Comment by JosephTLyons** [comment]
Weird that this was closed.  This feature is heavily missed in Atom.  Sure, there are a couple packages for it, but I think better solutions could be implemented by the actual team.
