### ISSUE TITLE
The commit message box and commit button should be disabled during a commit operation

### ISSUE THREAD

**Issue by Xapphire13** [atom/github#1041]
### Description
Commit message and commit button remain enabled during the execution of a commit. This is likely not noticeable usually, but my project has a long running pre-commit hook so I have a large window to observe.

### Steps to Reproduce

1. Modify a file
2. Stage it
3. Type a commit message
4. Hit commit

**Expected behavior:**
The "commit message" box and the commit button should become disabled until the operation completes.

**Actual behavior:**
Both the message box and commit button are enabled. I can click commit as many times as I wish and all but the first lead to an error message.

### Versions
**OS**: Windows 10 x64
**Atom**: 1.18.0 x64
**atom/github**: 0.3.3

### Additional Information

Successful commit, UI elements remaining enabled:
![commit](https://user-images.githubusercontent.com/3392349/28295397-331104a8-6b15-11e7-8df9-6852ecf709ad.gif)

Clicking commit multiple times (ignore the output in the error, that's the preamble in my pre-commit hook):
![commit fail](https://user-images.githubusercontent.com/3392349/28295434-67ef7a56-6b15-11e7-8119-eee789486e54.gif)

**Comment by BinaryMuse** [comment]
I'm going to call this closed as of #1043 even though there's not a great way to disable the actual message editor box. We can tackle additional UI improvements there in the future.
