### ISSUE TITLE
Repositories using overcommit fail to commit

### ISSUE THREAD

**Issue by bbugh** [atom/github#1051]
### Description

Using the `overcommit` tool for managing git hooks does not allow Git to commit through the github package. When committing, this error message appears:

> This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
> Install it with `gem install overcommit`.

While there is [an issue with overcommit working with editors and RVM](https://github.com/brigade/overcommit/issues/402), after extensive testing, I believe that this is actually an Atom/github package issue. I am using RVM, but even installing overcommit with the system gems and confirming that it works without special `PATH` settings, committing still fails through Atom. 

I also managed to load the PATH variable using [atom-project-shell-env](https://github.com/ddiachkov/atom-project-shell-env) but the Git commit still fails when done through the package.

### Steps to Reproduce

1. Create a sample repository
2. `gem install overcommit`
3. In sample repository, `overcommit --install`
4. Commit the `.overcommit.yml` file before proceeding (important)
5. Make changes to the sample repository
6. Attempt to commit sample changes through atom-github
7. See error message

**Expected behavior:**

It should commit without an issue, unless a git hook fails.

**Actual behavior:**

This error message:

![image](https://user-images.githubusercontent.com/438465/28525148-d8848832-7048-11e7-8ac1-d37c41230ffc.png)

> This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
> Install it with `gem install overcommit`.

**Reproduces how often:**

100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.1

MacOS 10.12.5 (16F73)

**Comment by BinaryMuse** [comment]
#1075 fixes this as long as the environment variables make their way into the Atom process itself — there's code in Atom to ensure this happens, but I guess it's still feasible that there's an edge case here. The change will be in the upcoming beta so feel free to try it out and let us know what you think.
