### ISSUE TITLE
Feature Request : Support Gitflow

### ISSUE THREAD

**Issue by DrChills** [atom/github#1052]
Really great work guys! One thing I think is missing is gitflow branch creation and closure. I appreciate it is simple to do this manually, however, a nice interface would work really well!

**Comment by BinaryMuse** [comment]
Similar to #808, this is not something we're going to add to the package in the near future, and instead we plan on providing services that package authors can use to implement whatever flows they would like — see https://github.com/atom/github/issues/1089 for more information
