### ISSUE TITLE
🙏  Ability to disable merge conflict view

### ISSUE THREAD

**Issue by rmehner** [atom/github#1078]
Hey there,

the merge conflict view is super neat, but it confuses the hell out of me and I ended up with having wrong merges more than once. It's probably due to my workflow and nothing particular bad with this feature, at least I don't have any productive ideas how to improve it. I now fall back to vim whenever I need to solve merge conflicts. It would be super neat, if I can simply disable the feature altogether, while still being able to use the rest of the package :)

So yeah, that's all, a low prio feature request, maybe you get around to do it. Thanks a lot for your work!

**Comment by nuflowx** [comment]
I love the feature too, but if I have loads of merge conflicts in one file I'd need to disable that to get a clear understanding of the code.

+1

**Comment by nuflowx** [comment]
Okay, just figured out an easy workaround. Always just `pick me` for whatever part your looking at and straightaway undo and it will leave you with the standard view

**Comment by smashwilson** [comment]
You can also choose "Dismiss" from the "..." menu on the conflict decoration to clear the controls individually.

<img width="390" alt="screen shot 2017-08-08 at 10 53 02 am" src="https://user-images.githubusercontent.com/17565/29078257-d206cd22-7c27-11e7-9fd8-b50f42246ac7.png">

(I am open to having the ability to disable them in general too. Although I generally try to resist a proliferation of checkboxes :wink:)

**Comment by rmehner** [comment]
> You can also choose "Dismiss" from the "..." menu on the conflict decoration to clear the controls individually.

Nice, didn't even know that. That's a click more than I'd like, but given that this is not where I spend the majority of my day, I'm totally fine with that. Thanks for pointing this out!

> Although I generally try to resist a proliferation of checkboxes

Gotcha. For my purpose, I'd be fine with just having a preference that I can set in some cson-file, but as said above, the whole "Dismiss"-thing is good enough for my use case. Although "Dismiss" might not be the best wording, as my first understanding would be to dismiss the changes, but that might be just me as a non-native speaker :)

For all what I want, consider this closed. Thanks again!

**Comment by dkniffin** [comment]
I'd still like to request this feature be added. As someone who still does all git commits and such via command line, this is way too "GUI" of a way of managing git conflicts for me.

**Comment by bronson** [comment]
Heh, I had no idea "..." was even a menu.  I figured it was minimized text or something and never thought to click it.

Would it make sense to change this icon to a down-arrow, or a hamburger, or something more "menuey"?

**Comment by ungoldman** [comment]
Please allow disabling merge conflict view in package settings:

<img width="774" alt="screen shot 2017-09-07 at 4 36 12 pm" src="https://user-images.githubusercontent.com/427322/30189752-c1d8986a-93ea-11e7-927d-cab617a4d9e6.png">

Disabling the `github` package altogether seems to have weird side effects.

**Comment by trobertsonsf** [comment]
Please, please make this configuration in settings. I really just want this feature of the product disabled altogether. Please give us a nice way to turn it off in settings.

**Comment by Grantimus9** [comment]
This would be very desirable. I've tried to adapt to the GUI but have found it does not work for me. Thanks Atom team.

**Comment by GeoffreyPlitt** [comment]
Please let me turn this off.

**Comment by tim1mw** [comment]
+1 for being able to turn this off, it's really, I find it to be a hindrance not a help.

**Comment by yagudaev** [comment]
I agree with all the above, I find it extremely confusing what the final result of the merge would be. This is especially annoying when trying to do a rebase where I want some of the changes from one 
 part and some of the changes from another part.

Thanks for showing the dismiss, I used to open it back in Sublime to edit it properly because I find it so hard to use.

**Comment by spaultx** [comment]
I also find it extremely confusing to when you have to merge changes from multiple branches. Is there a way to turn of merge conflicts through UI ?

**Comment by Arcanemagus** [comment]
@spaultx The PR that closed this issue added a setting controlling this.

Under Settings -> Packages -> github simply disable this setting:
![image](https://user-images.githubusercontent.com/427137/43486512-ec1b3f76-94c8-11e8-8090-40e3b7bcbaec.png)
