### ISSUE TITLE
Add Push Check-box in next to Commit Button

### ISSUE THREAD

**Issue by cortner** [atom/github#1085]
Feature Request: 

Wonderful package, the only thing I'd love to see is a checkbox next to the `Push` button and the `Amend` checkbox that if enabled will automatically commit AND push.

**Comment by rsese** [comment]
Thanks for the suggestion!  Looks like there's an existing request that covers it so I'll close as a duplicate of https://github.com/atom/github/issues/912 and you can subscribe there for updates if you'd like.
