### ISSUE TITLE
Not automatically show the next unstaged file after stage a file.

### ISSUE THREAD

**Issue by yubaoquan** [atom/github#1091]
### Description

Is this [pr #1016 (Supersedes #970) ](https://github.com/atom/github/pull/1016) not merged to github 0.3.4-0?

### Steps to Reproduce

1. Modify 2 files of a certain repo in atom.
2. Stage one of them.
3. See what happens.

**Expected behavior:**

When I stage a file , it should open the unstaged change view of the next unstaged file.

**Actual behavior:**

It does nothing.

**Reproduces how often:**

Every time.

### Versions

atom 1.19.0
github 0.3.4-0

**Comment by lee-dohm** [comment]
No, it isn't merged into v0.3.4-0 of the github package. See the header of https://github.com/atom/github/commit/671929349b59d356a36ab22170f70b7208097117
