### ISSUE TITLE
Cannot 'split [direction] and move active item' when git diff is active item

### ISSUE THREAD

**Issue by petemill** [atom/github#1097]
### Description

Running the atom command 'split right and move active item' when a git diff tab is the active item, there is what seems to be an infinite loop - the title bar loops between two different titles, the editor is unresponsive, and eventually offers to 'force close'.

### Steps to Reproduce

1. Create a test project:
   - `mkdir git-test1 && cd git-test1`
   - `git init`
   - `echo "hi" >> first.txt
   - `git commit -am "initial"
2. Make a pending edit
    - `echo "hello" >> first.txt
3. open atom
    - `atom --safe .`
4. Open the diff: click `first.txt` in the _Unstaged Changes_ pane
5. Open the command palette (`cmd-shift-p`) and choose the command `split right and move active item`.

**Expected behavior:**
The single plane is split to two, and the git diff tab is moved to the pane on the right.

**Actual behavior:**
Editor loops very quickly between two strings in the title bar, is unresponsive, and eventually offers to 'force close'.

**Reproduces how often:**
100%

### Versions
1.18.0
1.19.0
macOS: 10.12.5

**Comment by kuychaco** [comment]
Thanks for the report! This was fixed in #1158
