### ISSUE TITLE
Diff view does not update with subsequent changes on Windows

### ISSUE THREAD

**Issue by damieng** [atom/github#1103]
The diff view does not always reflect the most recent changes on Windows for a file inside a folder. 

## Repo steps

1. Open a project with folders
2. Open a file within a folder
3. Modify the file
4. View the diff from the Git pane
5. Modify the file again
6. Observe no changes in the diff view even if opened and closed

There are also messages in the console `Unable to find item at path x/y with staging status unchanged`

It appears this is a \ vs / issue after a screen-share with @smashwilson

**Comment by 50Wliu** [comment]
See also #1092

**Comment by damieng** [comment]
Yeah, this looks like a dupe of the other, sorry. Closing in favor of that one.

**Comment by ADTC** [comment]
Hi, is this supposedly fixed? I'm encountering this bug on Windows as well. I looked at the duplicate issue but there is no open issue or PR there.
