### ISSUE TITLE
GitHub tab contents does not take up full width of dock item

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#1117]
Example:

<img width="664" alt="menubar_and_github__preview__ ___github_github" src="https://user-images.githubusercontent.com/189606/29475380-4bdf77ea-8414-11e7-8261-a5fd56f97fdd.png">

Repro'd on `v0.5.0-0-16-g60e78044`

**Comment by 50Wliu** [comment]
Looks familiar to #488.

**Comment by simurai** [comment]
Looks like another of these "wrapper" `<div>`s got added:

![screen shot 2017-08-19 at 5 01 38 pm](https://user-images.githubusercontent.com/378023/29484752-4d879900-8500-11e7-8d2c-071272a137ea.png)

All these nested `<div>`s wouldn't be needed, UI wise. But I think in React you can't just add content and always need a single element that wraps the content. For example, is there a way to change this 

https://github.com/atom/github/blob/9336733bdafd767e51ba1226694384ab6477855e/lib/containers/pr-selection-by-branch-container.js#L60-L87

to just this (without the wrapping div):

```js
if (edges.length === 1) {
  return (
    <div>...</div>
    <PrInfoContainer pullRequest={edges[0].node} />
  );
}
```

Tried it out, but got this error:

```
Adjacent JSX elements must be wrapped in an enclosing tag
```

Anyways, made PR https://github.com/atom/github/pull/1123 that keeps flexbox going.

**Comment by simurai** [comment]
Found a way by using an Array: https://stackoverflow.com/a/37132051

```js
if (edges.length === 1) {
  return ([
    <div key="0">...</div>,
    <PrInfoContainer  key="1" pullRequest={edges[0].node} />
  ]);
}
```

Downside, you have to also add these `key` attributes.

**Comment by simurai** [comment]
Update re. endless nested `div`s. Once we update to React `v16.2.0`, we can use that [Fragments feature](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) to get rid of all the extra `div`s in a clean way.

```jsx
render() {
  return (
    <>
      <ChildA />
      <ChildB />
      <ChildC />
    </>
  );
}
```
