### ISSUE TITLE
Open Merge conflict doesn't become focus

### ISSUE THREAD

**Issue by ungb** [atom/github#1120]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes 
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Yes
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Opening a merge conflict with a file open, opens merge conflict but doesn't focus.  
### Steps to Reproduce

1.  Open a Project with a merge conflict. 
2. Open a file to view that doesn't have merge conflicts(make sure it's not pending item by double clicking it.
3. Go to github package and view a merge conflict by clicking on it once.  

**Expected behavior:**

[What did you expect to happen?]
Merge conflicts opens and becomes focused
**Actual behavior:**

[What actually happened instead?]
Merge conflicts opens on another tab but isn't in focus

**Reproduces how often:**

[What percentage of the time does this happen?]
100%
### Versions
```
Atom    : 1.21.0-dev-44f3cf73e
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

github@0.4.2
```
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

see Gif:
![mergeconflict](https://user-images.githubusercontent.com/5624870/29984548-c8d1009c-8f0f-11e7-8980-38df034c40b9.gif)

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

/cc @smashwilson @nathansobo

**Comment by nathansobo** [comment]
It seems to occur intermittently. Sometimes it works. Once you stage one of them though it seems to stop, and then if you close and reopen tabs you can make it start working again.

**Comment by nathansobo** [comment]
:heart:
