### ISSUE TITLE
Unable to push/pull with ssh on atom/atom master branch

### ISSUE THREAD

**Issue by ungb** [atom/github#1122]
### Description

Unable to push/pull with ssh off master

Could be related to ASAR changes 

### Steps to Reproduce

1. Open Atom with a git repo that is using ssh as the remote and have ssh setup
2. Try to push/pull/fetch on the toolbar on github package

**Expected behavior:**

[What did you expect to happen?]

It currently works on Stable and Beta, but doesn't work on master.

**Actual behavior:**
```
ssh_askpass: exec(/private/var/folders/lp/h7g12x7j68s02jr25ybpt2vc0000gn/T/github-117718-88505-19y2qj7.qcj9p8ehfr/git-askpass-atom.sh): Permission denied
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
See error when trying to do anything with a git repo that using SSH 

![image](https://user-images.githubusercontent.com/5624870/29481404-dc4221d6-8435-11e7-9294-b0d0e6043b92.png)

[What actually happened instead?]

**Reproduces how often:**
100%
[What percentage of the time does this happen?]

### Versions
```
Atom    : 1.21.0-dev-44f3cf73e
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

github@0.4.2
```
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

/cc @smashwilson @iolsen

**Comment by smashwilson** [comment]
@ungb Hmm. Can you retry with github@5.0.0 (the version I put in atom/atom master this afternoon)? I'm hopeful that aeae473da1981c0c7 will take care of this like it did for the gpg wrapper 🤔

**Comment by ungb** [comment]
Was able to verify this is fixed in 5.0.0! thanks @smashwilson

**Comment by cryptid11** [comment]
it still doesnt work...:/

**Comment by ungb** [comment]
@cryptid11 can you provide the following info?  

What version of atom are you using? 
What version of github package do you have installed(If you go to settings -> packages on atom and search for github you can find this info)?  
Which OS are you on(Windows, Mac, Linus Distro)?  
Lastly, can you check to see if push/pull with ssh works on your terminal/cmd prompt?
