### ISSUE TITLE
Filter un/tracked files in 'Unstaged Changes'

### ISSUE THREAD

**Issue by vpacik** [atom/github#1131]
Currently the Unstaged Changes window displays list of all files (excepts one filtered out by .gitignore) - both tracked and untracked - which can make it quite long in same cases. 

Suggestion: make a option to filtered out all untracked files and keep only the tracked ones similar to 
`git status --untracked-files=no ` or globally set `git config status.showuntrackedfiles no` directly in the window or in the package settings.

**Comment by BinaryMuse** [comment]
Thanks for the suggestion! I'm going to roll this into https://github.com/atom/github/issues/888
