### ISSUE TITLE
Pull request labels should reflect label and font colors from GitHub

### ISSUE THREAD

**Issue by brylie** [atom/github#1139]
# Description

The issue labels in the GitHub pane seem to be using the Atom font color. This can lead to difficulties with visibility (contrast):

![screenshot_20170825_112228](https://user-images.githubusercontent.com/17307/29705707-efc7ae4a-8987-11e7-9167-0fcb29f15e48.png)

## Steps to Reproduce

1. Log in with GitHub in Atom
2. Open a branch with a linked PR
3. Note the label/font colors

**Expected behavior:**
The label and font colors should be the same as on GitHub

**Actual behavior:**

The font color seems to be the same as used by the current Atom theme.

**Reproduces how often:**

100%

### Versions
atom 1.19.3
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.6.2
git 2.11.0
Kubuntu 17.04

### Additional Information

The GitHub labels for the related PR have the following label/font colors:
![screenshot_20170825_112735](https://user-images.githubusercontent.com/17307/29705840-6b35839a-8988-11e7-929f-9f395eaf48be.png)

Compare with the Atom GitHub integration:
![screenshot_20170825_112228](https://user-images.githubusercontent.com/17307/29705850-76f14462-8988-11e7-84c8-8d62707e29ce.png)

**Comment by BinaryMuse** [comment]
Thanks for the report! This has already been fixed by an awesome community member in https://github.com/atom/github/pull/1000
