### ISSUE TITLE
Line breaks are inserted in long lines in commit message body

### ISSUE THREAD

**Issue by ckrger** [atom/github#1148]
### Description
When the commit message body contains long lines these are broken - by inserted line breaks - upon pressing commit in the dock item.

### Steps to Reproduce
1. Write a commit message that has lines longer than 70 something characters in body
2. Click on commit
3. Run 'git show' in console - line breaks have been inserted, making breaking the long lines

**Expected behavior:**
I would expect the commit message to appear exactly as typed in dock item.

**Actual behavior:**
Line breaks are inserted, long lines are broken into multiple shorter lines.

**Reproduces how often:**
always

### Versions
Atom on Linux (Ubuntu 16.04)

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12+
git 2.9.3

### Additional Information
Inserting line breaks might be wished for by other users. If so, I could live with a property in 'settings' that would control the value at which line breaks are inserted.

**Comment by BinaryMuse** [comment]
There's some prior discussion on this in https://github.com/atom/github/issues/248. I'd be amenable to a setting, though we try to be very thoughtful about the things we add settings for. /cc @atom/github-package for 💭 s.

**Comment by bronson** [comment]
Well, my nicely indented commit message is now garbage.  I have to agree, this is a bug.  If Atom is going to automatically insert line breaks, it should at least show me how my commit message will ACTUALLY look before committing.  Otherwise, how can I trust that it's doing what I intend?

And, if a "silently reformat my commit message" option will exist, I hope it defaults to off...?

**Comment by kevinansfield** [comment]
Definitely agree with this being seen as a bug, it makes git commits inside Atom unusable for me - our team have a specific format where commit bodies are markdown formatted for use in GitHub etc and the forced line breaks 💩 all over that and are completely unexpected.

**Comment by kuychaco** [comment]
Thanks for the feedback. We'll discuss about adding a setting. 

In the meantime, you can avoid this automatic commit message wrapping by committing from an expanded commit editor, which is just a regular Atom text editor. The formatting as you see it in the editor will be preserved while committing. 

Just note that if you close the commit message editor, then the contents will be transferred to the commit message box, and pressing "Commit" at this point will result in automatic commit message body wrapping at 72 chars.

Here's how you can edit your commit message in an editor:

![git_ ___src_test-repo_and_file-patch-view_js_ ___github_github](https://user-images.githubusercontent.com/7910250/31696441-20eebaf6-b366-11e7-8375-b4b692bd7f85.png)

![git_ ___src_test-repo_and_line_breaks_are_inserted_in_long_lines_in_commit_message_body_ _issue__1148_ _atom_github_and_file-patch-view_js_ ___github_github](https://user-images.githubusercontent.com/7910250/31696624-73123fd2-b367-11e7-9a87-f1c9a7e8145c.png)

Hope this helps!

/cc @bronson @kevinansfield @ckrger

**Comment by kevinansfield** [comment]
@kuychaco the expanded commit message editor doesn't work for me. When clicking it my Git view switches to the submodule's parent repo and saving/closing the commit file does nothing, it just switches back to the submodule view with the same staged/unstaged files

**Comment by kuychaco** [comment]
Aw bummer. Yeah our submodule support isn't fully fleshed out yet. I'll get #1223 done for you @kevinansfield so you can just turn hard-wrapping off entirely. Hopefully next week sometime as this week I'm in refactoring mode. Appreciate your patience!

**Comment by kevinansfield** [comment]
No worries, really glad it's being looked at :) Thanks for all the awesome work! ❤️
