### ISSUE TITLE
Uncaught Error: Cannot find pane for item in `DockItem#activate`

### ISSUE THREAD

**Issue by broccolini** [atom/github#1150]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [github](https://github.com/atom/github) package 0.5.0

### Stack Trace

Uncaught Error: Cannot find pane for item in `DockItem#activate`

```
At /Users/broccolini/.atom/packages/github/lib/views/dock-item.js:142

Error: Cannot find pane for item in `DockItem#activate`
    at setTimeout (/packages/github/dock-item.js:142:15)
```

### Commands

```
     -0:11.8.0 github:toggle-git-tab (atom-pane.pane)
```

### Non-Core Packages

```
busy-signal 1.4.3 
firewatch-syntax 1.1.1 
github-atom-light-syntax 0.3.2 
intentions 1.1.5 
linter 2.2.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.8 
wakatime 7.0.3 
```

**Comment by rsese** [comment]
Based on your comment in https://github.com/atom/github/issues/935#issuecomment-327210990, it sounds like you get this error just when starting Atom, there are no particular steps to reproduce?

As in the other issue, do you see the same error in safe mode (`atom --safe`)?
