### ISSUE TITLE
Unable to push, even correct username or password

### ISSUE THREAD

**Issue by Twiistrz** [atom/github#1164]
Even my username or password is correct this error always popup.

Unable to push
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Twiistrz/Soul-Worker-FAQ.git/'

![atom bug](https://user-images.githubusercontent.com/25744238/30234676-2fc7bf16-9532-11e7-80ff-5b2b69c909f8.png)

**Comment by Twiistrz** [comment]
Fixed it by disabling my Two-factor authentication

**Comment by 50Wliu** [comment]
If you have 2FA setup without a credential helper, your password is instead a [personal access token](https://help.github.com/articles/providing-your-2fa-authentication-code/#when-youll-be-asked-for-a-personal-access-token-as-a-password).
