### ISSUE TITLE
switch Enable and Disable will add toolbar repeat

### ISSUE THREAD

**Issue by Rikidesu** [atom/github#1170]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?      yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?   yes
* Have you checked the FAQs on the [message board][message-board] for common solutions?  yes
* Have you checked that your issue [isn't already filed][already-filed]?  yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

switch enable and disable , will add toolbar repeat

### Steps to Reproduce

1. open Settings - packages - Github
2. Disable
3. Enable
4. will add lots of toolbar

**Expected behavior:**

display a toolbar 

**Actual behavior:**

display many toolbar

**Reproduces how often:**

100%

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.10.1

OS:  OSX 10.11.6

### Additional Information

![atom-package-github-issue](https://user-images.githubusercontent.com/7548245/30357168-ea9efdd6-9802-11e7-9d99-bd83c9b9da84.gif)

**Comment by BinaryMuse** [comment]
Thanks for the catch and the great bug report!
