### ISSUE TITLE
Open preview of diff in same tab

### ISSUE THREAD

**Issue by royteusink** [atom/github#1175]
**The problem:**
At this time, if you have a lot of changes across many files and you want to preview the changes, every diff opens in a separate tab which leads to a lot of open tabs.

**My feature request:**
Option to open all git diffs in one and the same tab.

[ ] Configuration option
[ ] Open diff view in same tab by default.
[ ] Ctrl + Click opens diff in separate tab.

**Comment by Zakini** [comment]
+1 for this. Wasn't this the behaviour in a previous version anyway?

**Comment by Arcanemagus** [comment]
Enable the "Allow Pending Pane Items" setting in Atom Core and it will already do this. (Atom v1.21.0-beta1)

**Comment by Zakini** [comment]
@Arcanemagus This works in v1.20.1 as well, but I prefer to keep that setting disabled so that Atom doesn't slow to a crawl if I accidentally single click on the minified css/js file.

**Comment by yubaoquan** [comment]
[this package](https://atom.io/packages/tree-view-click) provide an alternative way to both keep allow pending disabled and all diffs in the same panel. @Zakini

**Comment by hendricha** [comment]
+1
I use zentabs to manage my tabs normally so I don't need pending tabs in my normal workflow. However I would still like to have my diffs not flooding my tab bar.

**Comment by brettz9** [comment]
@Zakini : I don't see it working in 1.20.1 for Github diffs (only for files in the Project pane)...

Also, while tree-view-click mentioned by @yubaoquan sounds interesting, I like the single-click real open behavior for files but I don't want it for diffs (as there's little reason to have this polluting my tabs)...

**Comment by annthurium** [comment]
Good news -- now we have the ability to preview diffs from all files that are about to be in a commit in the same tab/pane.  See the "commit preview" button on the Git pane.

Going to close this out, but if you have additional questions / concerns please feel free to reopen 😄

**Comment by brettz9** [comment]
@annthurium : Is there any way to change the behavior (or may I request to do so) such that clicking unstaged changes either opens a diff tab that auto-closes or which at least can default to adding to staging?
