### ISSUE TITLE
Not showing changes while staging/committing

### ISSUE THREAD

**Issue by werunom** [atom/github#1177]
After updating to v1.20, when I open the github package (by clicking on the bottom right corner files-icon) to stage and commit the files, I am unable to see the changes I have made to the files. Before this update, I was able to see the changes when I click on the files in unstaged/staged changes

**Steps to reproduce**
The below gif shows how to reproduce...
![peek 2017-09-16 08-10](https://user-images.githubusercontent.com/24664855/30510003-fd8f493a-9ad9-11e7-95e3-19f541cc9fca.gif)

**Console message**
![screenshot_20170916_121919](https://user-images.githubusercontent.com/24664855/30509954-533d2aba-9ad9-11e7-99be-ac781ebbb9b5.png)

**Versions**
```
Atom : 1.20.0
OS: Manjaro KDE (64 bit)
```

**Comment by 50Wliu** [comment]
Does this work on files that do not have spaces?

**Comment by werunom** [comment]
I just checked. The package shows the same behaviour for a new txt file that has some characters without any spaces.

**Comment by 50Wliu** [comment]
I can repro this with a file that has spaces, but not with files without spaces.

**Comment by werunom** [comment]
Strange. I did now and I can see what you are mentioning - the diff for a file not having spaces were shown in the staging area. 

In any case, we can conclude that viewing differences in staging area is not working for files with spaces.

**Comment by Grillo-del-mal** [comment]
I can reproduce this error on 1.21.0 on Windows and Linux (fedora)

I attached a simple project that reproduces the problem [here](https://github.com/atom/github/files/1376057/repo.zip). It was created using the following bash script:
```sh
# Create the files
mkdir -p "repo/folder"
mkdir -p "repo/other folder"
echo "text" > "repo/folder/file"
echo "text" > "repo/folder/other file"
echo "text" > "repo/other folder/file"
echo "text" > "repo/other folder/other file"

# Create repository
git init repo
```

**Comment by Grillo-del-mal** [comment]
Just to be clear, the problem can be reproduced if any part of the path has spaces, it doesn't matter if it's the file or the folder.

The only file that works on the example is the first one (/repo/folder/file). the changes cannot be seen for the other 3, the first one because the file has spaces on it's name, while the other 2 because they are inside a folder that it's name has spaces.

**Comment by the-j0k3r** [comment]
Ill add a Me too comment here @smashwilson since this seems to have fallen into some crack.

My git config has no such values mentioned above to be commented out or worked around, so it breaks randomly here more often than not.

```
~> atom -v

Atom    : 1.21.1  
Electron: 1.6.15  
Chrome  : 56.0.2924.87  
Node    : 7.4.0  

~> apm -v  

apm  1.18.5  
npm  3.10.10  
node 6.9.5 x64  
python 3.5.2  
git 2.14.2.windows.1  
visual studio

Windows 10.0.15063.502 Pro

```
