### ISSUE TITLE
Unable to amend commit with expanded commit message editor 

### ISSUE THREAD

**Issue by jasonrudolph** [atom/github#1178]
### Description

When you use the expanded commit message editor to amend a commit, the github package uses the original commit message instead of the amended commit message.

Unless you know how to recover your amended commit message (see the "additional info" section below), this can seem like a data loss issue.

### Steps to Reproduce

1. Edit a file
1. Stage the change
1. Click the "amend" checkbox to amend the previous commit
1. Click the button to show the expanded commit message editor
1. Make your desired changes to the original commit message
1. Close the expanded commit message editor
1. Observe that commit messge box shows the original commit message

**Expected behavior:**

At Step 7, the commit message box should show the edited commit message that you entered in Step 5

**Actual behavior:**

The commit message box shows the original commit message

**Reproduces how often:**

100%

### Versions

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

$ apm show github
github
├── 0.6.1
...

$ atom --version
Atom    : 1.22.0-dev-024ad73a5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.7
npm  3.10.10
node 6.9.5 x64
python
git 2.14.1
```

### Additional Information

In the demo below, notice also that unchecking the "amend" checkbox shows your edited commit message, and re-checking the "amend" checkbox goes back to the original commit message. The first time I encountered this issue, I didn't realize that I could recover my lovingly-crafted commit message this way. I thought my amended commit message was gone forever 😱, and I resorted to reconstructing it from scratch. I thought this was a **data loss** issue, and others may mistakenly make the same conclusion. 😬 

### Demo

![demo](https://user-images.githubusercontent.com/2988/30546284-362cbd78-9c5a-11e7-9a29-1eadb617182f.gif)

**Comment by jfoclpf** [comment]
I don't see that option. What am I missing?

![image](https://user-images.githubusercontent.com/3984909/83200370-75d51100-a143-11ea-83df-11b4d61bf5ca.png)

**Comment by jrobinson3k1** [comment]
This issue is one of the first hits when you search for amending commits with the Github package in Atom, so answering for future time travelers.

Right click your most recent commit and there's an Amend option in the context menu. Working as advertised at the time of this comment.
