### ISSUE TITLE
Feature Request: github:stage-all keyboard shortcut

### ISSUE THREAD

**Issue by mike3run** [atom/github#1187]
I see that a while ago there was some discussion regarding adding the stage-all unstage-all commands as shortcuts without having to open the github panel right here:

https://github.com/atom/github/pull/405#issuecomment-270817399

However I'm not sure if we can be able to map them by ourselves?

I'm trying the following to no avail:

```coffeescript
'.workspace':
  ', g a': 'github:stage-all'
```

**Comment by mike3run** [comment]
Never mind took a dive in the source code:

'github:stage-all-changes'
'github:unstage-all-changes'

Are the actual commands now

**Comment by VityaSchel** [comment]
Add to keymap.cson:

```cson
'*':
  'alt-g a': 'github:stage-all-changes'
```

I had to practice a bit to successfully stage, commit and push with combination of hotkeys 😅
