### ISSUE TITLE
Incorrect styles on github-ChangedFilesCount causes status bar tile to appear unaligned

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#1198]
### Description

It looks like there's a few issues with the `github-ChangedFilesCount` status bar tile.  First of all, it's outside the `span` that the other two GitHub tiles are contained in (branch select, push/pull).  Then it's an `a` instead of a `div`.  But more importantly, it has the `icon` class assigned to the tile itself rather than a sub-span, causing the tile to be ~2 pixels lower than the rest of the tiles.

![github-changedfilecount-issues](https://user-images.githubusercontent.com/2766036/31196679-e1a6370a-a94e-11e7-91bd-722e0b8e699e.gif)

/cc @simurai maybe when you're back

**Comment by pingping-n** [comment]
So nice! Thank you.
