### ISSUE TITLE
Unable to git push since atom v1.21.0

### ISSUE THREAD

**Issue by HitomiTenshi** [atom/github#1199]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since `v1.21.0` I get an error when I try to push my commits via the git window in atom.

```
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://[url]/[project].git'
```

`v1.22.0-beta0` has the same issue.

My project uses LFS to store some media files.

### Steps to Reproduce

1. Stage changes and create a commit
2. Click on `Push`

**Expected behavior:** It should push commits to remote without errors.

**Actual behavior:** The above error appears.

**Reproduces how often:** Always since `v1.21.0`

Previous versions are not affected.

### Versions

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10 x64

**Comment by smashwilson** [comment]
Does `.git/hooks/pre-push` exist within your repository?

If it does, I wonder if this is similar to atom/github#1169, where git is trying to execute a shell script but `sh.exe` isn't on the `%PATH%`.

**Comment by HitomiTenshi** [comment]
Yes, `.git/hooks/pre-push` exists in my repository.

Atom versions prior to `v1.21.0` pushed fine. I downgraded to `v1.20.1` so I can continue pushing without having to open another `cmd` window.

**Comment by the-j0k3r** [comment]
same bug here since beta https://github.com/atom/github/issues/1199

**Comment by the-j0k3r** [comment]
no comments from devs?

**Comment by UVLabs** [comment]
When I click "Push" it asks for login credentials but nothing comes up for me to enter a commit message and nothing changes in the online repo, the file also stays orange(meaning its not been committed but has changed)

What's happening here?

**Comment by HitomiTenshi** [comment]
Still happening in atom `v1.24.0`.

**Comment by HitomiTenshi** [comment]
This issue is still happening in atom `v1.26.0-beta0`. #NeverFix

Seriously guys, this issue hasn't been fixed for more than 5 months now. The error is still the same as described in the issue description.

Ignore the comments that mention other issues. I checked them and they are all not related to this issue!

This issue only happens when I use LFS on a project and try to push commits using atom. The file `.git/hooks/pre-push` exists and pushing via the command line works as expected.

**Comment by HitomiTenshi** [comment]
@rsese Would you mind looking into this?

I hope I tagged the right guy 😄

**Comment by rsese** [comment]
I can take a look to at least try and reproduce on Windows with a repo using LFS.

**Comment by rsese** [comment]
Finally had a chance to give this a try and was unable to reproduce on Windows 10 with a repository using LFS (which looks like it creates a `pre-push` hook so my test repository had that too).

It sounds like this happens with any project of yours that uses LFS?

Do any hooks generate a similar error?  E.g. if you just have a non-LFS test repo and add a post-commit hook that just creates a file, does that work or do you get the same error - I tried with a test repo by creating `.git/hooks/post-commit` with just:

```
#!/bin/sh

touch test.dat
```

And then the file gets created after committing with the GitHub package.

> pushing via the command line works as expected

Just curious, do you have Git Bash installed or something else?

**Comment by HitomiTenshi** [comment]
We're using our own GitLab server. I just created a test project with LFS and was unable to push directly on the first initial commit. I wasn't even able to use the `stage all` feature, I had to go into `cmd` and enter `git add .` before I was able to create a commit in atom.

![atom_2018-03-29_10-02-19](https://user-images.githubusercontent.com/7304212/38077207-78e2b12a-3338-11e8-85de-f07f55a3d64c.png)

I'll try to recreate this on GitHub, give me a moment.

**Comment by HitomiTenshi** [comment]
Okay I got the same error on GitHub.

**Comment by HitomiTenshi** [comment]
Ok I got the same error on GitHub.

![atom_2018-03-29_10-18-54](https://user-images.githubusercontent.com/7304212/38077852-b7becc2e-333a-11e8-94fb-3433b0ba3737.png)

Fork this project:
https://github.com/HitomiTenshi/Test-LFS.git

Change something in `test.txt`.

Then Commit and push and you'll get the error.

**Comment by HitomiTenshi** [comment]
Hmm seems to be some very strange issue with the PC in my office. I'm currently on vacation, so I can't test if adding `sh.exe` to the PATH fixes it. I'll test it once I'm back.

In the meantime I tested the LFS issue with my Notebook. Seems like my Notebook does not have this issue.

The PC in my office is somewhat old, it was setup back when Windows 10 was freshly released. I kept git for windows up to date on it though! (with the LFS option in the installer) I'll post another comment once I tested the PATH thing on my office PC.

Thanks for assisting me with my issue @rsese, greatly appreciated!

**Comment by HitomiTenshi** [comment]
@rsese You were right! It was a **PATH** issue. For some reason, my git entry in PATH on my office PC was pointing to `C:\Program Files\Git\cmd`. Seems like older git installations created this entry in PATH but newer installations did not update it to `C:\Program Files\Git\bin`.

Even uninstalling and reinstalling git did not fix the PATH issue.

Manually changing `C:\Program Files\Git\cmd` to `C:\Program Files\Git\bin` solved my problem. 👍 

Thanks for all the help. 😄
