### ISSUE TITLE
Cannot read property 'lines' of null exception when pressing `tab` after staging the last line of a diff

### ISSUE THREAD

**Issue by nathansobo** [atom/github#1202]
### Description

After staging the last line of a diff view via line-wise staging, pressing `tab` produces an uncaught exception. Here's a video:

![staging-tab-exception](https://user-images.githubusercontent.com/1789/31252152-812f5994-a9dd-11e7-87a7-bc197aeeb4b9.gif)

### Steps to Reproduce

1. Open the diff view for an unstaged file
2. Enter line-wise staging mode via `/` or clicking a line
3. Hit `enter` repeatedly to stage all lines
4. Hit `tab`
5. 💥

**Expected behavior:**

No 💥

**Actual behavior:**

💥

**Reproduces how often:**

100%

### Versions

github@0.6.3

/cc @ungb @Ben3eeE for prioritization.

**Comment by iolsen** [comment]
@kuychaco could you take a look at this while you're in bugfix mode?

**Comment by kuychaco** [comment]
🔨 🔨 🔨

**Comment by nathansobo** [comment]
❤️
