### ISSUE TITLE
no way to correct token

### ISSUE THREAD

**Issue by paolobenve** [atom/github#1210]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? yes
* Have you checked the FAQs on the [message board][message-board] for common solutions? yes
* Have you checked that your issue [isn't already filed][already-filed]? yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

I entered a wrong token, and I don't find a way to enter the correct one

### Steps to Reproduce

1. [First Step]

on a pc where atom hasn't been installed yet, install atom and open it

2. [Second Step]

click on the github link, and insert anything in the input field -> atom doesn't log you to github, and doesn't give you the chance to insert the correct token

### Versions

1.21

**Comment by rsese** [comment]
Thanks for the report!  Looks like this is resolved in https://github.com/atom/github/pull/1180 and is currently available in the 1.22 beta.

In the meantime, if you clear the token from whatever credential helper you're using, you should be able to enter a new token.

**Comment by paolobenve** [comment]
where is the standard credential helper in ubuntu 16.04?

**Comment by paolobenve** [comment]
I found the problem: I hadn't any keyring installed, opening an issue for that
