### ISSUE TITLE
Diff does not work when there is a SPACE character in file's path

### ISSUE THREAD

**Issue by dhlavaty** [atom/github#1221]
I just see "File has no contents", when trying to display diff for Staged and/or Unstaged changed files, when there is a SPACE character in file's path. In my case there is a folder named "Dusko Co Je To". Running `git diff` in terminal works without any problem.

![diff-problem-atom](https://user-images.githubusercontent.com/513138/31649004-1114411e-b311-11e7-89bd-8f9b0cae5176.png)

**Reproduces how often:**

Everytime, when there is a SPACE char in file's path

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

github plugin: 0.6.2

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5

**Comment by 50Wliu** [comment]
This was just fixed in #1217.
