### ISSUE TITLE
Uncaught (in promise) Error: Git head failed

### ISSUE THREAD

**Issue by Arcanemagus** [atom/github#1222]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Opening a repository that is completely new, as in no commits have been made yet, shows an error in the console.

### Steps to Reproduce

1. Create an empty folder.
2. Run `git init` in the folder
3. Open the folder in Atom

**Expected behavior:**

No errors printed to the console.

**Actual behavior:**

An `Uncaught (in promise) Error: Git head failed` error is printed to the Console:

![image](https://user-images.githubusercontent.com/427137/31683065-b12a6646-b330-11e7-9415-95ecf80f62fb.png)

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.22.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.2.windows.3
visual studio
```

OS: Windows 10 x64 Enterprise

### Additional Information

If you initialize the repository in Atom itself the same issue happens if you then reload the window.

**Comment by BinaryMuse** [comment]
Looks like this is being thrown from core (there were some recent changes there). Do you mind reopening in `atom/atom` and cross-referencing this?
