### ISSUE TITLE
Dragging vertical scroll bar resets to the top

### ISSUE THREAD

**Issue by Arcanemagus** [atom/github#1226]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

If you drag the vertical scroll bar of the [un]staged changes as soon as the mouse is released it resets to the top position. Using the scroll wheel works normally.

### Steps to Reproduce

1. Have a large enough diff that you have a vertical scroll bar.
2. Attempt to view the changes at a certain point using the vertical scroll bar.
3. Watch it reset to the top when the mouse is released.

**Expected behavior:**

When the mouse is released the scroll bar stays at it's current location.

**Actual behavior:**

When the mouse is released the scroll bar resets to the top.

![2017-10-19_11-57-01](https://user-images.githubusercontent.com/427137/31788764-a9e2832e-b4c4-11e7-9ce9-8c14ff31b73f.gif)

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.22.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.2.windows.3
visual studio
```

OS: Windows 10 x64 Enterprise

**Comment by Ben3eeE** [comment]
Thanks was just going to file this myself 😆

**Comment by 50Wliu** [comment]
Related to #884.  Going to bet they're caused by the same bug.
