### ISSUE TITLE
Staged and Unstaged diff preview always opens in the same pane.

### ISSUE THREAD

**Issue by stakaz** [atom/github#1232]
Hello, 

I don't know why, but regardless of my settings to the option: `Direction to open Diff Pane` the staged or unstaged pane always opens in the same pane as the actual Git pane. this is uncomfortable as after each file I have to return to the Git tab which is in the same pane to actually choose another file. 

I remember this worked for me recently but not it is not. Can someone help me with this issue? Thanks.

**Comment by olaszakos** [comment]
Same here, it's annoying.

**Comment by Koshmaar** [comment]
I have the same issue now, it started on 1.32 and even after update to 1.35 its broken. I tried reseting the value to "none", and then to "right". I tried restarting atom etc. Nothing helps. In the .atom/config.cson I have
```
 github:
    viewChangesForCurrentFileDiffPaneSplitDirection: "right"
```
Value seems ok, so the error must be in the package.
