### ISSUE TITLE
Tabbing through inputs is broken in clone dialog

### ISSUE THREAD

**Issue by akonwi** [atom/github#1234]
In the clone dialog, the url input is autofocused. Once I hit tab, I expect focus to move to the destination directory input but instead the focus moves to the 'cancel' button.

This seems to be an issue with using `<atom-text-editor>`. I found this because I'm seeing the same broken behavior as I try to create a form with atom-text-editors. I guess I'll open an issue in the atom repo about it too.
### Steps to Reproduce

1. active 'Github: Clone' command
2. press 'tab' key

**Expected behavior:**
focus should move to the input labeled 'To Directory'

**Actual behavior:**
Focus is moved to the 'Cancel' button

**Reproduces how often:**
100% 

As you can see in the following gif, I have the keybinding resolver active and I'm pressing tab from the first input.

![tab-atom](https://user-images.githubusercontent.com/2013804/32063801-22362ae8-ba46-11e7-8247-2c70a4067c91.gif)

**Comment by jasonrudolph** [comment]
This issue is resolved in atom/atom#16492, and those improvements will likely be available in Atom 1.25.
