### ISSUE TITLE
Add the ability to copy text from the diff view

### ISSUE THREAD

**Issue by Xapphire13** [atom/github#1236]
### Description
When viewing the diff of a changed file it would be nice to have the ability to select and copy text from it. It's common to have a large refactor task and need to copy a snippet from a deleted file.

### Versions
**Atom:** 1.21.1
**atom/github:** 0.6.2

**Comment by Xapphire13** [comment]
I have a WIP for this [here](https://github.com/Xapphire13/github/commit/a37952e78080f32fe1e217106d9be923d3c14181)

**Comment by annthurium** [comment]
good news!  We now support copying and pasting from diff views, because we are using atom's `TextBuffer` to render the diff view.

Going to close this out, but please feel free to reopen if you have any problems. 😄
