### ISSUE TITLE
Manual would be nice

### ISSUE THREAD

**Issue by cdnschr** [atom/github#1240]
Call me stupid or lazy, but I don't get how to connect Atom with my git account. The Readme isn't helping at all... I guess I'll stick to the console instead of wasting another 20 minutes.

EDIT:
NVM my git wasn't working properly, now that I fixed my configuration the git integration does work fine. Maybe you could point out that the user should have a working git before using this. I know it's pretty obvious when you think about it, but maybe this could save some people time. ;)

**Comment by rsese** [comment]
Sorry for the trouble here @cdnschr but I'm glad you have things sorted out.  Working on improved documentation is on the team's radar so thanks for the suggestion about covering prerequisites :+1:
