### ISSUE TITLE
Tab navigation from staged changes goes to diagnostics table

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1245]
Repro steps:

1. Install atom-ide-ui v0.5.4
2. Open diagnostics table (can use `Diagnostics: Toggle Table` in command palette)
3. Select file in Staged Changes list
4. Hit `tab`

Expected: Commit box is highlighted for typing commit message
Actual: Filter input field in diagnostics view is focused

/cc @nathansobo who initially found the bug

**Comment by nathansobo** [comment]
❤️ for filing this for me. I was just about to close my laptop for the day when I hit it.

**Comment by 50Wliu** [comment]
Possibly related:
#753 (though after installing atom-ide-ui it is now Diagnostics that appears)
`core:focus-next/previous` focuses Diagnostics' "Filter" input and then doesn't focus anywhere else

**Comment by nathansobo** [comment]
Is this a problem with the tabIndex values on these fields?
