### ISSUE TITLE
documentation for GPG signing support missing

### ISSUE THREAD

**Issue by Spitfire1900** [atom/github#1247]
Using Windows 7 64-bit
Atom version 1.22.0
github version 0.7.0
Team's SCM tool: Atlassian Bitbucket v5.5.0

I've configured git to sign commits with git commit -S. I am not prompted for my gpg passphrase and commits are made unsigned. How is gpg signing configured with this package?

**Comment by rsese** [comment]
> How is gpg signing configured with this package?

There's no specific configuration within the package itself as far as I know to tell Atom to use GPG.  But you can tell Git to sign commits by default with this config for a particular repository:

```
git config commit.gpgsign true
```

And Atom should then prompt you for your passphrase.
