### ISSUE TITLE
Improve the startup time

### ISSUE THREAD

**Issue by mittalyashu** [atom/github#1258]
![image](https://user-images.githubusercontent.com/29014463/32991307-c9cc85f6-cd5e-11e7-925e-0bf4d0a94626.png)

**Comment by serafeimgr** [comment]
I have also raised this in #920

**Comment by rsese** [comment]
Thanks @serafeimgr, we'll go ahead and close as a duplicate of https://github.com/atom/github/issues/920.  You can share your screenshot and other details in that issue @mittalyashu.
