### ISSUE TITLE
View open/closed/merged status in PR listing

### ISSUE THREAD

**Issue by brettz9** [atom/github#1266]
### Description

View open/closed/merged status in PR listing (with ability to sort by group or number or at least be grouped by status).

### Steps to Reproduce

1. Go to the Github (PR) Preview.

**Expected behavior:**

1. Be able to distinguish already merged or closed PRs from open ones.

**Actual behavior:**

One has to click on each PR to determine its status.

**Reproduces how often:**

N/A. (Always)

### Versions

Mac 10.13.2

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.6

### Additional Information

None.

**Comment by annthurium** [comment]
merged and unmerged prs are visually distinct now.  Going to close this out.  Feel free to reopen if you feel the issue warrants further discussion. 😄
