### ISSUE TITLE
Issues staging changes to execute permissions

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#1273]
The GitHub package chokes on files that have filemodes changed from 100644 to 100755 or vise versa. Repro steps:

**Scenario 1**: only changing file mode

1. Change a non-executable file in a repo to be executable: `chmod +x somefile.txt`
2. Click on the file in Atom

Atom throws an exception in the diff parser (`what-the-diff`). It *is* possible to stage the file by pressing enter on the file or right-clicking and choosing "Stage."

**Scenario 2**: text and file mode changes

1. Change a non-executable file in a repo to be executable: `chmod +x somefile.txt`
2. Change the contents of the file
3. Click on the file in Atom

In this case, Atom shows the text changes and allows the user to stage the lines/hunks effected, but once they're all staged, the same issue as the scenario above appears.

---

Pretty sure this is a duplicate but I can't seem to find the original issue. `¯\(º_o)/¯`

**Comment by 50Wliu** [comment]
#1102 is related.
