### ISSUE TITLE
Unstaged changes view pops up unexpectedly when switching panes

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/github#1287]
### Description

Sometimes, when changing focus from a diff view in one pane to a text editor in another pane, another diff view unexpectedly pops up.

### Steps to Reproduce

1. Add multiple project folders, each of which are a git repository (say `atom` and `github`).
2. Open a diff view for a file in the `atom` repository.
3. Change focus to another pane in which a file from `github` is open.
4. A diff view for the first modified file in the `github` repository opens unexpectedly.

![diff-view](https://user-images.githubusercontent.com/326587/35066367-34420704-fb85-11e7-8ed6-88aab9c57975.gif)

**Expected behavior:**

It seems like diff views should only open when I directly perform some action in the commit panel. They shouldn't open in response to other unrelated events like changing focus to a text editor.

**Actual behavior:**

Diff views spontaneously open when changing focus to a pane containing a text editor.

**Reproduces how often:**

Unfortunately, this seems to depend on some sequence of events that I don't fully understand. I can't always get it to happen.

### Versions

```
Atom    : 1.25.0-dev-3d8902d52
Electron: 1.7.10
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by Ben3eeE** [comment]
![github unstaged changes 2](https://user-images.githubusercontent.com/1058982/35067241-9bb006b8-fbd3-11e7-9b32-8cbb23bd03cc.gif)

**Comment by maxbrunsfeld** [comment]
I'm still seeing a similar bug after building https://github.com/atom/atom/commit/7dfb45eb61a48a4ce18a0dd2e31f944ed4467ae3.

### Repro:

1. Enable the `Allow Pending Pane Items` setting.
1. Open the `atom` repo in Atom with no outstanding changes.
1. Open the file `package.json`
1. Make a one-line change such as inserting a newline at the top of the file.
1. Open the Git panel
1. Click on `package.json` in the `Unstaged Changed` section.
1. There should now be two tabs: the `package.json` editor and the `Unstaged Changes` view, which should be focused.
1. Click on the first tab (the `package.json` editor).

### Expected behavior

The `package.json` editor becomes the active item.

### Actual behavior

The `package.json` editor *momentarily* becomes active, but then the `Unstaged Changes` view immediately becomes active again.

**Comment by maxbrunsfeld** [comment]
I tried to record a GIF, but when I click the editor tab, focus switches back to the diff tab so quickly that you can't even see it.

![test](https://user-images.githubusercontent.com/326587/40561511-618fe356-6012-11e8-8797-4dcd038e5f31.gif)

**Comment by Ben3eeE** [comment]
The comments by @maxbrunsfeld here is the same issue as https://github.com/atom/github/issues/1444#issuecomment-390105541

**Comment by smashwilson** [comment]
Closing this because #1488 _should_ deal with it Once And For All :tm:. Re-open at will if you see this pop up with atom/github >= 0.15.2.
