### ISSUE TITLE
User stylesheet not overriding package settings

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1292]
See comments in https://github.com/atom/github/issues/1074#issuecomment-321909351

From @DavidCarpus:

![image](https://user-images.githubusercontent.com/24421399/29230309-6da51f7e-7eb0-11e7-93a0-ca97e45e4258.png)

> Not sure if needs to be logged separately or not but I tried to 'force' the font size by adding to my style.less but apparently the github-package-styles seems to be loaded later than the 'user' stylesheet?

Note that multiple team members have been unable to repro on our Mac computers. The user who filed the initial report was on Linux.

**Comment by simurai** [comment]
Ideally the `priority` of `github-package-styles` should be `0`. So that themes and user's `styles.less` come after.
