### ISSUE TITLE
GitHub (preview) pane, issues view

### ISSUE THREAD

**Issue by Anonymous142** [atom/github#1306]
I can view github's PR(pull request) with Atom GitHub package.

Can I also view and write GitHub issues?
There are some packages, but not working properly.

If i can view, write, open, and close issues with github pane, that would be really perfect.

**Comment by rsese** [comment]
Thanks for reaching out!

> Can I also view and write GitHub issues?

No, you can only view pull requests through the GitHub panel at the moment (the documentation details all the package's functionality [1]).   If you want to keep up with feature updates, you can keep an eye on our blog (http://blog.atom.io/) if you'd like.

[1]: http://flight-manual.atom.io/using-atom/sections/github-package/
