### ISSUE TITLE
Co-author commits

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1309]
Introduce the ability to specify one or more co-authors on a commit, [as supported by GitHub](https://blog.github.com/2018-01-29-commit-together-with-co-authors/).

See desktop/desktop#3879 for design and inspiration from GitHub Desktop.

**Comment by simurai** [comment]
Let's steal that nice gif too:

https://user-images.githubusercontent.com/634063/35525976-610efbb6-0526-11e8-9231-03b6fb95b420.gif

**Comment by smashwilson** [comment]
Fixed by #1355 and #1374.

:zap: :metal: @kuychaco and @annthurium :metal: :zap:
