### ISSUE TITLE
Status Bar item for Git panel has misaligned hover effect

### ISSUE THREAD

**Issue by Hirse** [atom/github#1339]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Yes
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The hover effect on the last status bar item, which shows the number of changed files and opens the Git panel, is misaligned. This only occurs on the last item, but not the previous ones.
![atom-github-status-bar](https://user-images.githubusercontent.com/2564094/37172700-66c5fe7a-22c6-11e8-8024-e36412e19d38.jpg)

![atom-github-status-bar](https://user-images.githubusercontent.com/2564094/37172736-818b3608-22c6-11e8-973d-9a4c182cbe10.gif)

### Steps to Reproduce

1. Hover over the status bar items
2. See the ugly misalignment of the hover background

**Expected behavior:**

I expect it to look like the other status bar items.

**Actual behavior:**

It does not look like the others. There is a ~1 pixel offset on the top.

**Reproduces how often:**

Every time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
`1.24.1`, Windows 10

**Comment by 50Wliu** [comment]
This will be fixed in future Atom versions.

**Comment by Hirse** [comment]
Is it already fixed in the code or do you just intend to fix it?
Your comment doesn't give me any information unfortunately. 😞

**Comment by 50Wliu** [comment]
We have already fixed it (atom/github#1307), but it may take a few Atom versions (usually 1-3) for it to appear on stable.  Sorry if that was unclear - I'll work on improving the wording for the future!

**Comment by Hirse** [comment]
Thanks for the update. I am happy to hear that is is already fixed. 😄
