### ISSUE TITLE
Update Relay dependencies to 1.5.0

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1345]
I've locked our Relay dependencies to 1.4.1 in #1344 to work around [an issue with Relay 1.5.0](https://github.com/atom/github/issues/1340), but the Real Fix that would let us stay up to date shouldn't be that bad.

I suspect that this is conflicting with our RelayNetworkLayerManager implementation:

> Changes the type of `RelayNetwork.execute` to return a `RelayObservable` with `variables` and `node`, in addition to the QueryPayload.

[v1.5.0 release notes](https://github.com/facebook/relay/releases/tag/v1.5.0)

**Comment by annthurium** [comment]
assuming this is resolved since we are now at relay-runtime 3.0.0 in master.  But please reopen if this is still a problem.
