### ISSUE TITLE
Previewing unstaged & staged changes (diff pane) does not work

### ISSUE THREAD

**Issue by zinkkrysty** [atom/github#1348]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? YES
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? YES
* Have you checked the FAQs on the [message board][message-board] for common solutions? YES
* Have you checked that your issue [isn't already filed][already-filed]? YES

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When I click on a file in the github pane I expect to get a preview (diff) of the changes. Instead nothing happens.

### Steps to Reproduce

1. Open a github project (currently only happens for one specific project)
2. Make changes to some files
3. In the right Github pane, click on one of the changed files

**Expected behavior:**

to get a preview (diff) of the changes

**Actual behavior:**

nothing happens

**Reproduces how often:**

every time I do it on a specific Git project. I tried other projects and there it works fine. I cannot share the project, though I can post some git data if you tell me what to look for.

### Versions

Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.1
python 2.7.10
git 2.16.2

github package 0.8.4

MacOS 10.13.3

### Additional Information

It used to work fine until I updated Atom and some packages (~ a week ago).

It works on other Git projects, but on one specific git project I get this error.

While having the dev tools open, I get this output:

```
<embedded>:267185 Uncaught (in promise) Error: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"prUrl","type":"URI!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByUrlQuery","selections":[{"kind":"LinkedField","alias":null,"args":
....
```

[-1520868841710.log](https://gist.github.com/zinkkrysty/27d441f79fafb7b6ca9d962eb005f6a6)

**Comment by rsese** [comment]
Thanks for the report - that particular error that you saw in devtools was reported in https://github.com/atom/github/issues/1340 and should be fixed in the next releases.  Not sure if it's related to this issue though....

I believe https://github.com/atom/github/issues/1340 was not an issue in 1.24.0, can you install 1.24.0 and see if you still have the same problem?

**Comment by lukevangorp-wf** [comment]
I noticed this issue yesterday after installing 1.24.1.  I've just installed 1.24.0 and am now able to open and work with the Git/Github panes.

**Comment by HughZurname** [comment]
Yup, same issue here. Works on 1.24.0 but not on 1.24.1

**Comment by rsese** [comment]
Thanks @lukevangorp-wf :+1:

The fix for https://github.com/atom/github/issues/1340 will be available in 1.25 and 1.26-beta0 (/cc https://github.com/atom/github/issues/1346#issuecomment-373008191) so you can stick with 1.24.0 for now and then wait for the next release to confirm if this issue is also fixed by https://github.com/atom/github/pull/1344.

**Comment by rsese** [comment]
1.25 has shipped, can folks confirm if you're still having this problem?

**Comment by zinkkrysty** [comment]
Working for me now, thanks!

**Comment by rsese** [comment]
Thanks for confirming @zinkkrysty :bow:  If anyone else is still seeing this issue on 1.25 or 1.26 beta, please open a new issue and fill out the issue template and we'll take a look.
