### ISSUE TITLE
Atom Doesn't Ask for SSH Password

### ISSUE THREAD

**Issue by lbunge** [atom/github#1351]
Description
Atom doesn't ask for ssh password when cloning from Github. Doesn't clone or throw errors - Dies silently.

Steps to Reproduce
Have ssh key with password
Attempt to clone from GitHub using ssh
Be sad
Expected behavior: It clones repo

Actual behavior: Dies silently

Reproduces how often: 100%

Versions
Atom : 1.23.3
Electron: 1.6.15
Chrome : 56.0.2924.87
Node : 7.4.0

Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  Which operating system + version are you using?

Also, can you update to the latest stable release (currently 1.25) and confirm if you still have the same issue there?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/github/issues/1351#issuecomment-375807668. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
