### ISSUE TITLE
Pressing "Escape" when asked to confirm a Force Push executes the Force Push

### ISSUE THREAD

**Issue by mattmattmatt** [atom/github#1368]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? **Yes.**
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? **Yes.**
* Have you checked the FAQs on the [message board][message-board] for common solutions? **Yes.**
* Have you checked that your issue [isn't already filed][already-filed]? **Yes.**

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Pressing "Escape" when asked to confirm a Force Push executes the Force Push instead of canceling the Push.

### Steps to Reproduce

1. Cmd/Ctrl-click the "Push" button in the interface or use command palette to "Force Push"
1. Dialog window pops up, asking to "Cancel Push" or "Force Push"
1. Press "Escape" key on keyboard

**Expected behavior:**

Dialog window closes without Force Pushing (as if "Cancel Push" was clicked).

**Actual behavior:**

Force Push is being executed (as if "Force Push" was clicked).

**Reproduces how often:**

All of the times.

### Versions

macOS Sierra, v10.12.6

```shell
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.12
git 2.14.3
```

**Comment by rsese** [comment]
Thanks @mattmattmatt :+1:  I can reproduce on macOS 10.12.6 with Atom 1.26.0-beta0 - clicking `Cancel Push` works ok.
