### ISSUE TITLE
Git stopped working

### ISSUE THREAD

**Issue by lukepighetti** [atom/github#1391]
I woke up today and git wasn't working with any of my project folders. They had been functioning fine the previous day.

Inside the folders I can confirm that git is working.

```
Lukes-MBP:pigeonbot lukepighetti$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Lukes-MBP:pigeonbot lukepighetti$ git remote -v
origin	https://github.com/Pigeoncoin/pigeonbot.git (fetch)
origin	https://github.com/Pigeoncoin/pigeonbot.git (push)
```

However, inside Atom the git tab is blank for all projects. Removing and adding a project folder does not help.

![image](https://user-images.githubusercontent.com/666539/38768601-51a4aa58-3fc4-11e8-899c-84514e356a2c.png)

Atom is up-to-date `1.25.1` on `macOS 10.13.2 (17C88)`

**Comment by rsese** [comment]
Do you see any errors in devtools console?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

Also, did you try any of the debugging suggestions from the `Prerequisites` section like safe mode (`atom --safe`)?

I just tried Atom 1.25.1 on macOS 10.12.6 and the Git functionality worked ok on a couple of test repos.

**Comment by lukepighetti** [comment]
It appears to have been user error. In order for the git tab to refresh you have to click on a file inside a project folder. I was just clicking the project folder without having any tabs open.

So I guess it's either user error or possible UX improvement.

Thanks!

**Comment by rsese** [comment]
Thanks for the details, glad things are working for you now - that's odd though, if I open a new test repo with no files open, I don't see the "Create repository" view 🤔 

We'll close for now and keep an eye out if more people run into this.
