### ISSUE TITLE
Searching for github in command palette brings up a lot of co author

### ISSUE THREAD

**Issue by ungb** [atom/github#1407]
### Description

Searching for github in command palette brings up a lot of co author 
### Steps to Reproduce

1. Install and link latest github package from master.  
1. Open this repo off master
1. Open Atom and search for `Github` in command palette 

**Expected behavior:**

Should only see 1 of each command

**Actual behavior:**

See a bunch of `Co Author`
![image](https://user-images.githubusercontent.com/37118738/39067005-ffd1e840-448b-11e8-8780-d1d20f60e59e.png)

**Reproduces how often:**
100%

### Versions

Atom is 1.26 and github package sha 2ed5f1e9a6648e9e602b2f0c82e49cab87fe645c

You might have to scroll a little to see this.  
/cc @kuychaco @smashwilson

**Comment by Ben3eeE** [comment]
I see the same behavior on 1.27 beta.
