### ISSUE TITLE
Poor performance while scrolling a large Git Diff View

### ISSUE THREAD

**Issue by robertrossmann** [atom/github#1445]
### Description

The Diff view performs poorly when viewing large diff (ie. when updating npm's _package-lock.json_) - frame rate drops to about 1fps.

From a brief look into the Performance profiles (attached below) it looks like both scrolling and clicking a line causes *all* components to re-render. This is most visible in the _click profile_ and I am just assuming that something similar is happening also during scroll, even though it's not visible from the _scroll profile_.

### Steps to Reproduce

1. Start Atom either in Safe Mode or normally
1. Open a large diff (~3k of changed lines, ie. when re-creating _package-lock.json_ after upgrading from _npm@5.6_ to _npm@6.0_)
1. Scroll down or click
1. Observe low frame rate

**Expected behavior:**

Smooth experience while scrolling & clicking around, peaceful thoughts

**Actual behavior:**

Poor frame rate, long delays to user input, fear and despair 😱

**Reproduces how often:**

100% of the time for large diffs (tested with ~3k changed lines)

### Versions

```
Atom    : 1.27.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

- Performance profiles:

[atom-git-diff-view-click.json.zip](https://github.com/atom/github/files/1979263/atom-git-diff-view-click.json.zip)
[atom-git-diff-view-scroll.json.zip](https://github.com/atom/github/files/1979265/atom-git-diff-view-scroll.json.zip)

**Comment by annthurium** [comment]
https://github.com/atom/github/pull/1512 has shipped to atom beta and it's a significant performance improvement.  We'd love to know what you think.

I'm going to close this out, just for the sake of not leaving issues open forever, but please do feel free to reopen if there are additional concerns 😄
