### ISSUE TITLE
Slowness when typing in commit message editor due to frequent `loadUsersFromLocalRepo` calls

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/github#1463]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When typing a commit message, Atom starts to feel sluggish. I recorded a profile and it looks like `loadUsersFromLocalRepo` is getting called each time I type a key.

### Steps to Reproduce

1. Open the commit message editor
2. Start recording a profile
3. Start typing

**Expected behavior:**

Low CPU usage.

**Actual behavior:**

High CPU usage.

**Reproduces how often:**

100% for me.

### Versions

```
Atom    : 1.29.0-dev-c950a3e89
Electron: 2.0.0
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

Zoomed-out profile (showing multiple keystrokes):

![screen shot 2018-05-15 at 11 26 03 am](https://user-images.githubusercontent.com/326587/40076224-37ee31f6-5833-11e8-8c32-48b3dc292e5b.png)

Zoomed-in profile (showing details):

![screen shot 2018-05-15 at 11 26 11 am](https://user-images.githubusercontent.com/326587/40076239-425005f2-5833-11e8-9be1-688ed38e2724.png)

**Comment by annthurium** [comment]
should be fixed by https://github.com/atom/github/pull/1464 but please let me know if any additional issues come up.

**Comment by maxbrunsfeld** [comment]
⚡️
