### ISSUE TITLE
Ammend commit message is corrupted in certain cases since atom 1.27.0

### ISSUE THREAD

**Issue by gliviu** [atom/github#1465]
### Steps to Reproduce

1. change some file
2. stage change
3. set commit message
```
a

b

c
```
4. commit
5. change the file again
6. stage change
7. right click on last commit in history and chose Amend
8. take a look with 'git log'

**Expected behavior:**

Last commit message should be

```
a

b

c
```

**Actual behavior:**

Corrupted commit message

```
a

bc
```

**Reproduces how often:**

Always

### Versions

Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.14
git 2.16.1.windows.1
visual studio 2015
Windows 10

**Comment by ajborley** [comment]
+1 (breaks my gitlint)

**Comment by rsese** [comment]
Thanks for the report @gliviu - I was able to reproduce this with Atom `1.29.0-dev-9ba737de2` on macOS 10.12.6.

**Comment by smashwilson** [comment]
Looks like we were both misparsing existing commit messages _and_ overzealously applying git's commit message filters. We should be better behaved now :zap:

**Comment by gtema** [comment]
@smashwilson, in which version will it be released? I'm struggling now with 1.27. Waiting for 1.29 is too long. It really hinders me in day-to-day work (backport)?

Thanks for the fix

**Comment by smashwilson** [comment]
I'm backporting the fix to the 0.15 (:atom: 1.28.x-beta line) and 0.14 (:atom: 1.27.x stable line) presently. I'll release new patch versions for 0.16, 0.15 and 0.14 after I get this and a few other regressions fixed. They'll go out with the next stable or hotfix release of Atom.

Yeah, we know it takes us too long to get fixes out to our users' hands, especially stable users. See atom/atom#17379 for some discussion about ways we're investigating to improve our release cadence!

**Comment by gtema** [comment]
Thanks
