### ISSUE TITLE
commits through Atom aren't connected to my account

### ISSUE THREAD

**Issue by marsinearth** [atom/github#1470]
I've connected this Github account's third-party key on provided page by github.atom.io (can't replicate it atm)
after then, I have no problem with functionally using it, but my github stats are like this:
<img width="1026" alt="2018-05-18 1 36 12" src="https://user-images.githubusercontent.com/6101260/40191696-33558386-5a3d-11e8-9642-8dd3a769dda8.png">

the only one with delete .netlify commit with profile photo is the one that I've committed on github.com page, others are all using github atom integration. Due to this, my github profile stats and everything is a lot less..

I tried to figure out why but googling didn't work out, failing find cases related to mine.

**Comment by annthurium** [comment]
hello @marsinearth.

github profile stats are calculated using the email address specified in git config from the project you pushed the commits from.  What is the output of your git config?  You can find this by typing `git config -l` inside the repository you pushed from.

**Comment by marsinearth** [comment]
That scratches right on the spot. Thanks!! I've updated user.name and user.email for local git config and magically it worked out

**Comment by annthurium** [comment]
yay, glad that worked out!  Happy committing.
