### ISSUE TITLE
Do not ask for all permissions to private repositories by default

### ISSUE THREAD

**Issue by 2m** [atom/github#1479]
### Description

Github for Atom requires read and write permissions to public *and private* repositories by default.

![after](https://user-images.githubusercontent.com/422086/40304543-d47ee33c-5cff-11e8-877a-cb0cfc990327.png)

**Expected behavior:**

Ask for read/write permissions only for public repositories.

**Actual behavior:**

Permissions asked for public *and private* repositories.

### Versions

```
apm  1.19.0
npm  6.0.1
node 10.1.0 x64
atom 1.27.0
python 2.7.15
git 2.17.0
```

### Additional Information

I assume this might have been brought up already, but I was not able to find a similar ticket from before.

Asking for write permissions for private repositories prevents me from evaluating the plugin.

**Comment by sguthals** [comment]
👋  @2m 

Thanks for opening up this issue. Unfortunately, we aren't going to limit the repository access to only public repos at this time. When you authenticate with GitHub through our extension, you are authenticating for all of your repositories.

**Comment by 2m** [comment]
I understand. Thank you for the response.
