### ISSUE TITLE
Atom collab github not working

### ISSUE THREAD

**Issue by TAG-Epic** [atom/github#1484]
Hey, i am new to atom, it has a github repo save, i have added my username and email but it wont post it (or just me beeing a dumbass) How do i fix it

**Comment by annthurium** [comment]
Hello.  I'd like to help but I don't have enough info to understand what the problem is.  Would you mind filling in some of the information on the issue template?

**Comment by EpicShardGamingYT** [comment]
@annthurium i am trying to make it post it to my github but it isnt working, i have set username and email, but it wont post? Is it just me beeing stupid again

**Comment by rsese** [comment]
> i have set username and email, but it wont post?

Can you share more details about this like what specific steps are you trying, what happens, and what do you expect to happen?   Are you getting an error of some kind?  If you can share a GIF/screencast of the behavior you're seeing that could be helpful too.
