### ISSUE TITLE
Feature request: Split the current hunk into smaller hunks

### ISSUE THREAD

**Issue by varemenos** [atom/github#1499]
> Have you checked that your issue isn't already filed?

Yes I did try to look for this issue in the issue tracker but found nothing relevant.

### Description

`git add`'s interactive mode gives us the ability to split the current hunk into smaller hunks. This is extremely useful while using `git add -p`

> Stage this hunk [y,n,a,d,/,j,J,g,e,?]? ?
...
*s - split the current hunk into smaller hunks*
...

_from https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging_

Now, Atom's github package has the ability to stage hunks but doesn't provide us with the option to split these hunks into smaller ones and I almost always end up having to select line after line to stage the selection because the hunks are usually too large and contain more lines of code than needed.

### Steps to Reproduce

1. Make some changes to the repo's codebase
2. Open Git/Github Pane
3. Open a file and try stage a hunk

**Expected behavior:**

I was expecting to have a chance to split the hunks into smaller hunks if the current size is too large for my needs.

**Actual behavior:**

The hunk selected by Atom was too large so I had perform this hunk splitting feature that git provides myself.

### Versions

```
>> atom --version && apm --version
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.10
git 2.17.0
```

**Comment by schtandard** [comment]
Agreed, this would be great.
