### ISSUE TITLE
Amend checkbox not there

### ISSUE THREAD

**Issue by danhab99** [atom/github#1506]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? It's not mine so no
* Have you checked the FAQs on the [message board][message-board] for common solutions? Did, couldn't find anything
* Have you checked that your issue [isn't already filed][already-filed]? Yes, it isn't

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The amend checkbox on the sidebar is not there

### Steps to Reproduce

1. Open the sidebar

**Expected behavior:**

To see the amend checkbox

**Actual behavior:**

Not seeing the amend checkbox

**Reproduces how often:**

Idk I've been doing a lot of work

### Versions

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 3.6.5
git 2.17.1.windows.2
visual studio 2015
```

### Additional Information

I use the "Atom Material" theme.

**Comment by 50Wliu** [comment]
The Amend option has been moved to the context menu.  Access it by right-clicking on the most recent commit.

![amend-context-menu](https://user-images.githubusercontent.com/2766036/40880714-dccaf0d4-6683-11e8-8031-e93b4f6abad2.png)

**Comment by danhab99** [comment]
But then how am I suppose to remove hunks from the previous commit?

**Comment by 50Wliu** [comment]
The new workflow is as follows: https://github.com/atom/github/issues/1466#issuecomment-390527153

If you have any suggestions, please feel free to add them to that issue!
