### ISSUE TITLE
Fresh Atom install Github pane empty

### ISSUE THREAD

**Issue by jato8987** [atom/github#1519]
![image](https://user-images.githubusercontent.com/18424700/41196663-e3f0e662-6bfa-11e8-9502-3d0fb4e5b3d8.png)

Just installed Atom as a new user. I'm trying to integrate with GitHub, but the pane is empty. Google searches are not returning any similar behaviors. Happy to assist in trouble shooting.

**Comment by jato8987** [comment]
Not sure if this helps... as a work around I attempted to open Atom from the GitHub Desktop GUI but received no response.

**Comment by smashwilson** [comment]
Interesting. Can you open your developer tools (Ctrl-Shift-P to open the command palette, then run "Window: Open Dev Tools") and see if there are any errors in the Console tab?

**Comment by jato8987** [comment]
Sorry about the slow reply...busy start to the week. I am not seeing any errors.

**Comment by rsese** [comment]
Just to clarify, do you have git repository open in Atom (can't tell since the tree-view is hidden in your screenshot)?   If I open Atom with no project open or a project that isn't a git repository, the GitHub tab is blank in those cases.

**Comment by jato8987** [comment]
Novice move on my end - I've always just opened into a project and thus didn't realize it could be blank! Thanks for pointing this out. All good on my end now.

**Comment by rsese** [comment]
Ahhh great, glad that's sorted out - it does seem like we could have a more informative message in the cases I mentioned above rather than just showing an empty pane?  I'll open a separate issue about that if there isn't one already.

**Comment by jato8987** [comment]
Sounds like a great idea to implement!
