### ISSUE TITLE
Push/pull only works when pressing the text itself, not the status bar tile

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#1530]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The push/pull action only goes through when you are clicking on the actual text, not the tile itself, despite the entire tile appearing to be clickable.

![github-push-pull-button-area](https://user-images.githubusercontent.com/2766036/41429143-326671b2-6fda-11e8-955a-4f8e10a816b9.gif)

### Steps to Reproduce

1. Attempt to click the push/pull tile, but *not* the text itself
2. See the tile react to being clicked, but nothing actually happens
3. Try again by clicking on the text area
4. Notice the push/pull action actually occurs

**Expected behavior:**

Both 2) and 4) perform the push/pull action

**Actual behavior:**

Only clicking on the text itself triggers the action

**Reproduces how often:**

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.29.0-dev-0422e0d61
Electron: 2.0.1
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
Windows 10 x64.

**Comment by annthurium** [comment]
Thanks @50Wliu for reporting!  We should definitely fix this.  I can add this to my list of short term priorities.

**Comment by annthurium** [comment]
hmm, actually this issue belongs in https://github.com/atom/status-bar.  Lemmesee if I can find a way to move it.

**Comment by annthurium** [comment]
I don't think you can actually move issues...recreated the issue over there.

https://github.com/atom/status-bar/issues/224
