### ISSUE TITLE
Push/pull tooltip shows up much quicker than other status bar tooltips

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#1531]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The tooltip for the push/pull status bar tile shows up much quicker (almost instantly) than any other tile in the status bar.

![github-push-pull-button-tooltip](https://user-images.githubusercontent.com/2766036/41429407-09e7a5f2-6fdb-11e8-8a8f-7bad42da2731.gif)

### Steps to Reproduce

1. Hover over the push/pull status bar tile

**Expected behavior:** Tooltip to appear after a delay

**Actual behavior:** Tooltip appears almost instantly

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.29.0-dev-0422e0d61
Electron: 2.0.1
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by annthurium** [comment]
thanks for reporting! moved to `status-bar` repo: https://github.com/atom/status-bar/issues/225

**Comment by annthurium** [comment]
@50Wliu ahh, my mistake, it's not!  Will reopen and close that other issue.  Sorry about that.

**Comment by annthurium** [comment]
addressed in https://github.com/atom/github/pull/1534
