### ISSUE TITLE
Commit message jumps around

### ISSUE THREAD

**Issue by lloiser** [atom/github#1536]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The commit message in the text box starts to jump around in a certain edge case.
It's nothing dramatic just annoying.
Also some characters are clipped (maybe the root cause?)

![mac](https://user-images.githubusercontent.com/3003233/41587386-6a05deea-73af-11e8-8099-d2bbf23036c3.gif)
1. I highlighted the clipped character
2. focus -> jumps
3. type `a` -> jumps
4. remove `a` -> jumps

### Steps to Reproduce

Given the following commit message:
```
aaa-aaaa: aaaaaaa aaa-aaaaaa aaaa aaaaaa aaaaaaaa

aa aaaaa aaa aaaa aa aaaa aa aaaaaa aaaa aaaaaaaaaa aa aaa aaa aa aa a aaaaaaa aaa. aaaa aaaa aa aaaaaaaaaaa aaaa aaaa-aaaaaaa aaaaaa aaa aaaaaa aaaaaa aa
```

And both the `.atom-dock-mask` and `.atom-dock-content-wrapper.right` have `width: 323px`.

And my editor has the following font settings:

```css
atom-workspace {
  --editor-font-size: 10px;
  --editor-font-family: Menlo;
  --editor-line-height: 1.4;
}
```

The commit message already jumps around when focusing the text field. The same happens when you type, remove a character or use your arrow keys for navigation.

**Expected behavior:**

It should not jump around...

**Actual behavior:**

[What actually happened instead?]

**Reproduces how often:**

100%

### Versions

```
$ atom --version
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.10
git 2.15.2

github 0.14.5
atom-dark-ui 0.29.0
atom-dark-syntax 0.53.2
```

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by Arcanemagus** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/atom/pull/17474. It is currently scheduled for release when the _next_ beta release (the one _after_ v1.28.0 hits stable) reaches Stable.
