### ISSUE TITLE
Integrate with the metrics API

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1546]
Once [atom/telemetry](https://github.com/atom/telemetry) is integrated into Atom (atom/telemetry#8), consume the [metrics package service](https://github.com/atom/metrics/blob/eddf3161f1eb1701302511d9fe06098c44d01638/lib/metrics.js#L32-L38) and send "interesting metrics" to GitHub's internal metrics pipeline for users who have consented to it.

We'll need to decide on what metrics we want to collect initially - I believe @annthurium had identified some in their original write-up. If we can think of any other hypotheses we want to test in our initial ship, though, this would be a good opportunity to get them in early.

#1545 will help lay some of the groundwork for this, I think.

/cc @telliott27 for awareness.

**Comment by annthurium** [comment]
here's what we came up with during the editor tools mini summit:

- Commits made by the GitHub package
- Commits made by the GitHub package that have a co author
- Authentication requests made for the GitHub package
- GitHub package version
- Amend actions
- Partial staging actions
- opening/closing the Git / GitHub panes
- Push actions
- pull actions
- create pull request actions

I'm sure there are more things we could track, though!
