### ISSUE TITLE
Improve GitHub tab blank slate in a couple of cases 

### ISSUE THREAD

**Issue by rsese** [atom/github#1566]
### Prerequisites

✔️ ✔️ ✔️ ✔️ 

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Splitting off from https://github.com/atom/github/issues/1519#issuecomment-397169258; while poking at that issue I noticed that in a couple of cases, the GitHub tab will just be blank if opened:

1. If the project opened isn't a git repository
2. if Atom is opened with no project

So if you haven't used the GitHub package before you might think something's wrong 🤔 
 
### Steps to Reproduce

Taking the first case above:

1. `mkdir test-no-repo; cd test-no-repo`
2. `atom --safe .`
3. <kbd>ctrl-shift-8</kbd>

**Expected behavior:**

An informative message rather than a blank tab?  E.g. when you have the GitHub tab open for a git repository with no github.com remote you see:

![no-gh-remote](https://github-slack.s3.amazonaws.com/monosnap/sandboxtest-git_2018-07-05_17-19-50.png)

**Actual behavior:**

You see an empty GitHub tab:

![no-git-repo](https://github-slack.s3.amazonaws.com/monosnap/sandboxtest-no-repo_2018-07-05_17-20-25.png)

**Reproduces how often:**

100%

### Versions

```
atom -v
Atom    : 1.30.0-dev-55fc57600
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
apm -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0-dev-55fc57600
python 2.7.10
git 2.14.3
```

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by mikebronner** [comment]
Having this issue as well, it just started after updating to version 1.30.0. Previously I could be opening Atom without a project, then open a project folder, and it would populate the Git tab. Now I need to close the git tab manually after opening a project, then re-open the git tab, and it will display as expected (otherwise it is a blank pane).

**Comment by bragovo** [comment]
Same behaviour in 1.31.1, starts from 1.30.

**Comment by rsese** [comment]
Thanks @mikebronner @bragovo!  I think you're both describing a different issue that I think is more a bug?  The 2 cases I described above are places I think we can improve the messaging of the Git tab when you're not working with a Git repository.

I went ahead and opened https://github.com/atom/github/issues/1718 if you want to subscribe (let me know if I mis-understood the issue you were describing).

**Comment by willcraft1** [comment]
Just started using Atom again and had a 5 minute brain error trying to figure out why I couldn't use the github pane to open a repo. :D

**Comment by dfmiller** [comment]
I had to reload the window for the tree to show after installing a new version (1.32.0)

**Comment by annthurium** [comment]
we have an empty state error message now!  Going to close this out but please feel free to reopen if there are additional issues.
