### ISSUE TITLE
Accessibility audit tooling

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1597]
Let's get some accessibility audit tooling integrated into our test / CI pipelines, so we can see how we're doing on the accessibility front and start the process toward continuously improving.

**Comment by smashwilson** [comment]
Eslint plugin: [eslint-plugin-jsx-a11y](https://www.npmjs.com/package/eslint-plugin-jsx-a11y)

**Comment by annthurium** [comment]
there's also Spectron: https://github.com/electron/spectron#accessibility-testing

Spectron is a more general integration testing framework for electron apps, that has a11y audit functionality.  So this dovetails with our goals of having proper integration tests.

**Comment by smashwilson** [comment]
Now that #1599 is in, should we close this in favor of other incremental, less open-ended issues? Or we can leave it open until some of those open-ended issues exist, maybe?

**Comment by annthurium** [comment]
sure - I can file issues for the individual lint rules we want to enable.
