### ISSUE TITLE
Commit pane item

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1655]
Let's design a pane item to show the contents of a single commit. :art: The work in #1512 will allow us to show much larger diffs in a performant way, which opens the door to a full-commit view.

We can access it by:

* Clicking on an entry in the recent commits view
* (Maybe) showing the combined staged changes while the keyboard focus is in the commit message editor, like a `git commit -v`
* (Eventually) clicking on a commit entry in the issueish pane item
* (Eventually) from diving into a single commit on the log view (#1419)

We'll want to show the full diff with some kind of navigation controls to allow you to move among the changed files. It'd also be a good place to put controls for contextual actions that you can take on that commit: amending the most recent, hard and soft resets, revert, checkout, create and checkout a new branch.

**Comment by simurai** [comment]
> We'll want to show the full diff with some kind of navigation controls to allow you to move among the changed files.

Does this mean that in the same pane, there are diffs of multiple files stacked on top of each other, like on .com and the navigation controls would change the scroll position? That would be nice for allowing:

> (Maybe) showing the combined staged changes while the keyboard focus is in the commit message editor

Like when there are 2 changed files you don't have to switch between them and could just scroll and see the diff of both files.

**Comment by simurai** [comment]
Mockups for:

> (Maybe) showing the combined staged changes while the keyboard focus is in the commit message editor, like a `git commit -v`

![commit-preview](https://user-images.githubusercontent.com/378023/47568149-54aaae00-d96b-11e8-833a-98356b69db29.png)

In the mockup, there is a "Preview" button that can be clicked to see a preview of the next commit... buuuuuut, it _could_ show automatically on focus when there is already a `FilePatchView` open. Like when you clicked on a file to see the diff, then why not re-use that same pane for the preview when focusing the commit message editor. 👍 

If you click the "Preview" button, but there is no commit message, it just shows `...`.

![image](https://user-images.githubusercontent.com/378023/47568070-17deb700-d96b-11e8-8707-25d4ee0d3667.png)


> Clicking on an entry in the recent commits view

![commit-pane](https://user-images.githubusercontent.com/378023/47567450-8a4e9780-d969-11e8-9a51-96d327d0716b.png)
