### ISSUE TITLE
Remote management: select remote to pull from / push to

### ISSUE THREAD

**Issue by lucascosti** [atom/github#1679]
One thing that I think Atom's git integration does very poorly with at the moment is remote management. I'd like to be able to interactively choose which remotes I fetch/pull/rebase from or push to, and I can't do that at the moment.

Ideally, I'd like to see a right-click menu option for "Pull from..." and "Push to..." to get prompted for the remote, and have the option for that interactive prompt to be the default action (i.e. always prompt me which remote I want for the action).

**Comment by rsese** [comment]
Thanks for opening a new issue for this!  It looks like there's an existing issue about adding more remote management functionality so I'll go ahead and close this in favor of https://github.com/atom/github/issues/555.  I'll also add your comments to that issue.
