### ISSUE TITLE
Can not preview changes by clicking on files from the side panel

### ISSUE THREAD

**Issue by sorcamarian** [atom/github#1682]
### I've tried to see the difference in a file 
![side-panel](https://user-images.githubusercontent.com/12509753/45220574-399ab680-b2b7-11e8-8dce-d0b66fb594a8.jpg)
### After clicking on a file with a change:
![atom-github-0 18 3-package-diff-error](https://user-images.githubusercontent.com/12509753/45220302-5d113180-b2b6-11e8-83ac-664083b48ff4.jpg)
### After clicking on new file(blank page):
![new-file-changes](https://user-images.githubusercontent.com/12509753/45220787-099fe300-b2b8-11e8-97b1-3d5ec2985fc4.JPG)

### The error messages
` Unable to open 'atom-github:\file-patch\project\...\index.html?workdir=C%3A%5CUsers%5CMarian...&stagingStatus=staged' `
`EINVAL, open 'atom-github:\file-patch\project\...\index.html?workdir=C%3A%5CUsers%5CMarian...&stagingStatus=staged'`

---
### Versions

`atom -v`:
```
Window: 10
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
` apm -v`:
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0
python 2.7.14
git 2.18.0.windows.1
```
(I use https://github.com/coreybutler/nvm-windows)

### Tried to install [v 0.20.0-0](https://github.com/atom/github/releases/tag/v0.20.0-0) 
`apm install github`
(Through PowerShell, opened as Administrator)

**Comment by annthurium** [comment]
@sorcamarian thanks for reporting!

Does there happen to be a question mark or other special character in the filename?  We recently fixed an issue where we were not properly uri encoding filenames, so you couldn't view files with special characters in the name.

**Comment by sorcamarian** [comment]
I think that is the problem.
I'll check this tomorrow.

**Comment by sorcamarian** [comment]
@annthurium, I'm sorry for the delay.

Indeed, a **special character** was in the **directory name**, namely: **#**.
The package worked fine once I removed the character.

Thank you!

**Comment by annthurium** [comment]
@sorcamarian no worries about the delay!  

That bug should be fixed in the next release of the GitHub package.  In the meantime you can try building from source if you'd like.  I'm going to close this out but feel free to reopen if there are additional issues viewing files from the staging area.
