### ISSUE TITLE
Cannot handle local branch being named differently from its remote branch

### ISSUE THREAD

**Issue by stuartchaney** [atom/github#1697]
### Description
1. Team Member creates a PR on a branch named feature/replace-iphone-image-template

2. When checking out this PR on Atom. A branch is created named 
pr-81/stuartchaney/feature/replace-iphone-image-template

The branch created on my local system should be feature/replace-iphone-image-template

When clicking fetch from Atom this will lead to the following

![](https://cl.ly/b8683baa617f/Image%202018-09-18%20at%2010.12.05%20AM.png)

**Expected behavior:**

local branch created from checking out PR should be feature/replace-iphone-image-template

**Actual behavior:**

local branch created from checking out PR is pr-81/stuartchaney/feature/replace-iphone-image-template

**Reproduces how often:**
100%

### Versions

1.30.0

**Comment by vanessayuenn** [comment]
The underlying issue is that we're not properly handling the case where the local branch is named differently from its upstream. Related issue: #918.
