### ISSUE TITLE
The merged commit text on a PR is squished together

### ISSUE THREAD

**Issue by mattr-** [atom/github#1701]
### Description

After merging a PR, the merge commit is text is squished together, as seen in the actual behavior section of this issue.

### Steps to Reproduce

1. Add the [tracks repo](https://github.com/TracksApp/tracks) - it's public - as a project folder to atom
1. Open `test/controllers/search_controller_test.rb` with Cmd-T
1. Open the GitHub tab (Ctrl-Shift-8)
1. Select PR 2117 from the list of pull requests to open the PR view
1. Scroll down to the section of the pane that contains the merge indication

**Expected behavior:**

Expected the text to be `merged commit` as in this doctored screenshot:
![doctored screenshot expected behavior](https://user-images.githubusercontent.com/77174/45932212-9e544300-bf3e-11e8-95f1-d463e7c88259.png)

**Actual behavior:**

![screenshot of actual behavior](https://user-images.githubusercontent.com/77174/45932144-93e57980-bf3d-11e8-9ca1-f775bf85a90d.png)

the text `mergedcommit` is squished together rather than being displayed as `merged commit`

**Reproduces how often:**

Always.

### Versions

Running on OS X 10.13.6

![atom-github package version screenshot](https://user-images.githubusercontent.com/77174/45932245-233f5c80-bf3f-11e8-878c-8eb089d03664.png)

```
$ atom --version
apmAtom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0
python 2.7.15
git 2.18.0
```

### Additional Information

I looked into the code for this briefly, and it looks like the UI in question is rendered here:
https://github.com/atom/github/blob/10d4dd2b1e5bf12cc092ab0fdc7b44ddf5f6b6d2/lib/views/timeline-items/merged-event-view.js#L30-L32

I'm not familiar enough with React to know how to handle this particular situation but would be happy to follow guidance or pair with someone on a fix. 🙂 

Thanks for your attention! :heart:

**Comment by rsese** [comment]
Thanks @mattr- :v:  Just dropping into to mention I can reproduce on macOS 10.12.6 and 1.33.0-nightly0.

**Comment by annthurium** [comment]
thanks for reporting!  I have an Atom community member looking for a good first issue, so I'm going to work with her on resolving this bug.
