### ISSUE TITLE
GitHub API Rate Limit warning in dev mode

### ISSUE THREAD

**Issue by vanessayuenn** [atom/github#1707]
When open in dev mode, I keep getting a lot of silent warning in the console:
```
GitHub API Rate Limit: 5000/5000 — resets in n minutes
```
It doesn't seem to impact any regular usage though, so `¯\_(ツ)_/¯`.

**Comment by annthurium** [comment]
5000/5000 is remaining / total :smile: so gonna close this out.  We could definitely make that more clear, though!
