### ISSUE TITLE
figure out a way of instrumenting context menu actions

### ISSUE THREAD

**Issue by annthurium** [atom/github#1728]
Right now, we don't have a great way of collecting UI metrics for context menu actions.  Understand context menu actions is critical for discoverability, so we can understand how users are using the package.

I don't even have good suggestions as to what this might look like - more investigation is needed.

**Comment by vanessayuenn** [comment]
After some digging, I found a [`contextCommand` flag](https://github.com/atom/atom/blob/master/src/main-process/context-menu.js#L19) hidden way in the command dispatch event when the command is triggered via context menu. So I think we can totally track context menu actions!
