### ISSUE TITLE
Keyboard interactions for Git committing

### ISSUE THREAD

**Issue by nathansobo** [atom/github#174]
Before we staff ship, it should be possible to commit via this package without ever touching the mouse. Here's some initial thinking I did with @maxbrunsfeld on a comprehensive keybinding scheme.
- **Focusing and toggling the Git and GitHub panels.** These bindings are based on a logical extension of the existing binding for toggling focus on the tree view. Since they're based on numbers, we could potentially extend this scheme even further to manage other panels:
  - Existing binding
    - `ctrl-0` – focus/blur the tree view
  - Proposed new bindings:
    - `ctrl-shift-0` – show/hide the tree view
    - `ctrl-9` – focus/blur the Git panel
    - `ctrl-shift-9` – show/hide the Git panel
    - `ctrl-8` – focus/blur the GitHub panel ("8" for "Octocat")
    - `ctrl-shift-8` – show/hide the GitHub panel
    - `esc` blurs the panel, returning focus to the active pane item
- **Moving focus between elements of the Git panel.** When you focus the Git panel, either the unstaged/staged file list is focused or the commit message editor is focused.
  - "Sub-focus" is retained across panel focus/blur events, so you could blur the panel with the commit message editor focused, then still have the editor focused when you restore focus to the panel.
  - `tab` moves _forward_ between _merge conflicts_, _unstaged files_, _staged files_ and finally to the commit message editor. Once focus is in the editor, we do not change focus on `tab` but instead insert tabs / spaces into the editor. To return to the lists, use `shift-tab`.
  - `shift-tab` moves _backward_ from the commit message editor to the _staged files_, _unstaged files_, and finally _merge conflicts_. To match behavior of _tab_ going forward, we don't cycle around.
  - Intuitive arrow navigation
    - `down` on the last entry in the file list focuses the commit editor.
    - `up` at position `(0, 0)` of the editor moves to the last item of the file list.
- **Navigating unstaged/staged files**
  - `up` and `down` navigate both unstaged and staged file lists as a single list.
  - `left` transfers focus from the panel to the currently selected diff
  - `right` transfers focus to the current diff back to the panel
  - `enter` toggles staging status on the selected file and selects the next item in the list.
- **Committing**
  - `cmd-enter` (`ctrl-enter` on Win/Linux) anywhere in the git panel with a _non-empty commit message_ creates a commit.
  - `cmd-enter` with an _empty commit message_ focuses the commit editor.

/cc @atom/core

**Comment by spark131072** [comment]
I would like to ask is there any keybinding to stage all, or can I create one?

I've tried this but no react at all.
> * `shift-enter` toggles staging status on **all** files in a list. Basically moves all files between unstaged/stages changes.

Thanks!

**Comment by tassosblackg** [comment]
Hi,
is there a way to focus inside git-tab without using the mouse?
I mean when I hit 

> cntl-shft-9 

and git tab toggles I want to focus on the changes box in order to select file with up-down hit enter and then with tab use the commit message etc. I use shortcuts to commit, push fetch etc but
