### ISSUE TITLE
Re-introduce the "large diff" gate

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1759]
With #1512, we can now handle much larger diffs without causing the same UI lockups that we observed previously. It isn't infinite, though, so there is likely still some diff size where we should make users click through a confirmation before trying to render a patch.

**Comment by annthurium** [comment]
@vanessayuenn are you working on this?  If so would you mind assigning it to yourself?

**Comment by paul-arthurthiery** [comment]
hey @vanessayuenn @annthurium would it be possible to update the status on this ? it's ongoing on a closed board so... is it ongoing or dropped ? I'm waiting impatiently for this issue to be fixed 😁

**Comment by annthurium** [comment]
@paul-arthurthiery we shipped the large diff gate feature in Atom 1.36 Beta, which was released the second week of March.  Check it out, let us know what you think! 😄 

Beta rolls over into stable in next month's release, so if you don't feel like dealing with Atom Beta, you should be able to use the feature sometime in April.  

Let me know if you have any other questions

**Comment by rsese** [comment]
Helllooo!   Based on Ash's comment above:

> It isn't infinite, though, so there is likely still some diff size where we should make users click through a confirmation before trying to render a patch.

And from https://github.com/atom/github/issues/1968#issuecomment-485143172 (/cc @trusktr):

>@rsese Hello! Atom 1.36.0 works much better with big diffs now. Thanks!

> I found that it still may take long to load certain big diffs like the following: https://gist.github.com/trusktr/175c7b1402c960daed3e022fdc1d79fe

Sounds like slowdown is still expected for some super large diffs and there's potential followup work to have people click through to see these large diffs?
