### ISSUE TITLE
GitHub panel won't accept new token

### ISSUE THREAD

**Issue by agrossfield** [atom/github#1768]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

This morning, when I went to use the GitHub pane I got a message saying "Your token no longer has sufficient authorizations. Please re-authenticate and generate a new one."  I did so on GitHub, then clicked the login button.  However, no matter how I enter the token into the dialog box (paste using mouse, ctl-v, or typing in it), nothing happens when I click "login".

### Steps to Reproduce

1. Open the GitHub pane, be asked to provide a token
2. Click login, enter the token (as far as I can tell, all entry mechanisms fail, including typing it)
3. Click login.

**Expected behavior:**

I expected to be authenticated to GitHub.

**Actual behavior:**

Nothing.  The "login" button flashes when clicked, but otherwise nothing.

**Reproduces how often:**

100%.

### Versions

1.30.0 and 1.32.0 (I upgraded to see if the problem went away) on Linux.

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by smashwilson** [comment]
Just to confirm: the token you're pasting was generated at https://github.atom.io/login, not a personal access token from GitHub proper, correct?

**Comment by agrossfield** [comment]
No, I generated it on github proper, using my account setting panel. 

I'm an idiot -- the instructions are there, and I didn't follow carefully. You can close this issue.
