### ISSUE TITLE
remote: Repository not found even though it exists

### ISSUE THREAD

**Issue by S0nMoon** [atom/github#1785]
### Description

Whenever I try to Sync, Push, Pull, etc it tells me my repo isn't existing.

### Steps to Reproduce

1. Clicking the Sync, Push, Pull button

**Expected behavior:**

Work normally

**Actual behavior:**

Told me an error

**Reproduces how often:**

100%

### Versions

Atom: 1.32.2
Windows 10

### Additional Information

![image](https://user-images.githubusercontent.com/32783392/48294639-cc380d00-e442-11e8-8bec-e0a601c45a41.png)

**Comment by Powell-v2** [comment]
@S0nMoon How did you resolve this issue?
