### ISSUE TITLE
Commit preview documentation

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1791]
This is a checklist of the documentation we'd like to have in place before we ship an Atom release that includes the Commit Preview feature we're introducing in #1767.

### Documentation

- [x] Gif for demos
- [x] Flight manual update https://github.com/atom/flight-manual.atom.io/pull/499
- [x] README image update https://github.com/atom/github/pull/1810
- [x] Feature blog post on GitHub blog
- [x] "Notable Change" sentence for Atom release notes
- [x] Release blurb for Atom release blog post https://github.com/atom/blog.atom.io/pull/245
- [x] Tweet

**Comment by smashwilson** [comment]
@simurai when you have bandwidth, could you tackle the .gif creation and README screenshot updates? 🙇

**Comment by simurai** [comment]
I think it's probably safest to only start with this once #1767 is merged and we have some sort of "feature freeze". Otherwise we have to do it twice like if "the button" would still move or so.

The release deadline seems to be **Nov 21**.

**Comment by simurai** [comment]
Let's close this again. Tweet will be in the next Atom release. I also added the demo gif to https://github.com/atom/github/pull/1767 at the top.

**Comment by annthurium** [comment]
we're still waiting on @meaghanlewis who has agreed to write a blog post for this in January when the feature rolls over into stable, so let's keep that open until then.
