### ISSUE TITLE
Papercut-like Features

### ISSUE THREAD

**Issue by drguthals** [atom/github#1794]
👋 I'm starting a list of papercut-like issues that could potentially be transitioned into features that we build. Feel free to add to this list. We can re-visit this list as we decide on things to work on. 

# Git Workflow
- Creating a repository locally, it's not obvious how to then publish it to a remote GitHub repository. For example, this is how we do it in Unity:
![initializerepopublishtogithub](https://user-images.githubusercontent.com/1314285/48455813-7a102800-e771-11e8-87c3-3073df30149c.gif)

**Comment by smashwilson** [comment]
Rather than make one issue for all of these, how would you feel about grouping them with a label? That way we could drop individual issues on the current sprint project as we tackle them, and better track what we have done and what we could pick up as we have time.

**Comment by smashwilson** [comment]
Also this specific issue is already kind of covered in #1566.

**Comment by sguthals** [comment]
Thank you, yes, I will do that tomorrow 🎉

**Comment by smashwilson** [comment]
I've added a papercut label and added it to [a bunch of issues from our backlog](https://github.com/atom/github/issues?q=is%3Aissue+is%3Aopen+label%3Apapercut) that felt "kind of small, and probably not involving too much @simurai time". (I didn't look _too_ closely at many of them so it's quite possible we'll take one look at them and say "screw this." We can always just take the label off 😅 )

Feel free to do your own pass to find more papercuts, or to write new ones!

Do you mind if we close this in favor of #1566 and the other papercuts-labelled issues?
