### ISSUE TITLE
spacing issue with git and github status bar icon for some themes

### ISSUE THREAD

**Issue by annthurium** [atom/github#1803]
### Description

In the "Atom Dark" and "Atom Light" theme (and possibly others), the icons in the status bar are crowded next to the text and look like they need some padding or something.

atom light has the problem:

<img width="496" alt="screen shot 2018-11-20 at 12 44 21 pm" src="https://user-images.githubusercontent.com/3781742/48801761-0b2b5580-ecc2-11e8-8c09-4f151a5befba.png">

one light does not:
<img width="517" alt="screen shot 2018-11-20 at 12 45 42 pm" src="https://user-images.githubusercontent.com/3781742/48801835-4037a800-ecc2-11e8-9508-2b30ed396b22.png">

The size of the text is bigger in one light, and this issue may have something to do with that.

### Steps to Reproduce

1. change your theme to one of the affected themes

**Reproduces how often:**

100%

### Versions

Atom    : 1.34.0-nightly16
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by annthurium** [comment]
@simurai it doesn't look like we have any theme-specific code inside the github package at the moment.

Do you have thoughts on the most robust approach to fix this?

**Comment by simurai** [comment]
There would be a few options:

- Fix it in the GitHub package by targeting specific themes with `theme-[name]`, like `.theme-atom-dark-ui status-bar .icon:before`.
- Fix it in the theme.
- Fix it in the status-bar package.

Hmmm.. maybe we can give "Fix it in the status-bar package" a try. It seems that other community themes also have the same problem.

**Comment by annthurium** [comment]
yay, thanks @simurai !
