### ISSUE TITLE
Message template does not ignore commented lines like Git does

### ISSUE THREAD

**Issue by lee-dohm** [atom/github#1817]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Comment lines are included in the commit message upon commit when your `~/.gitmessage` file contains commented lines.

### Steps to Reproduce

1. Create a `~/.gitmessage` file that contains two blank lines followed by two lines starting with a `#` character
1. Execute the command `touch test` from the command-line inside a Git repository
2. Launch Atom in Safe Mode
3. Open the Git panel
1. Double-click the `test` file in the Unstaged Changes panel
1. Type `foo` in the first line of the Git commit message box
1. Click "Commit to master"
1. Go back to the command line and execute `git log -1`

**Expected behavior:**

The commit comment text to consist only of `foo`

**Actual behavior:**

The commit comment contains `foo`, the blank line, and the two following commented lines

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.35.0-nightly2
Electron: 2.0.14
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

* I haven't tested other configurations of commented and uncommented lines (such as starting with comments and then having blank lines)
* My `~/.gitmessage` file is symlinked to my dotfiles directory (though I hope that won't make a difference)

**Comment by annthurium** [comment]
just merged https://github.com/atom/github/pull/1902 which should resolve this
