### ISSUE TITLE
Allow Github button to be hidden

### ISSUE THREAD

**Issue by FelixVicis** [atom/github#1839]
### Description

It would be very useful to allow the github button to be hidden if a user doesn't want to use it.

### Versions
```
~$ atom --version
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
~$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.12
git 2.7.4
```
OS: Ubuntu 16.04

**Comment by annthurium** [comment]
@FelixVicis you can hide the GitHub button by adding the following css to your stylesheet:

```
// styles.less
.status-bar {
  .github-StatusBarTile {
    display: none;
  }
}
```

**Comment by FelixVicis** [comment]
Done that, I was hoping for something more 'official'. Thanks for the help
