### ISSUE TITLE
GitHub tab crashes upon lost of internet connection

### ISSUE THREAD

**Issue by vanessayuenn** [atom/github#1844]
### Description

GitHub tab does not handle internet connection dropping well. 

### Steps to Reproduce

1. Open a project in Atom that has a GitHub repo with opened PRs
2. Open GitHub tab
2. Click on any PR from the list
3. Opens Network tab in Chrome devtool and check the "Offline" box (or just disconnect from internet in any way)
4. Click on another PR from GitHub tab
5. Watch the world crash and burn

![image](https://user-images.githubusercontent.com/6842965/49953565-a4830b80-fefe-11e8-83aa-a1e3ad5356f0.png)

**Expected behavior:**

Gracefully fail to fetch any additional info from github.com, and display a nice message informing users they have lost internet connection.

**Actual behavior:**

The whole package crashes with no way to recover beside a full reload.

**Reproduces how often:**

100%

### Versions

All versions

**Comment by vanessayuenn** [comment]
Other issues related to being offline: #1732 #1528

**Comment by the-j0k3r** [comment]
Also related https://github.com/atom/github/issues/2089

For this issue, Ive tried following the steps outlined by @vanessayuenn  and cant duplicate this with my current setup (as below),

```
$ apm -v

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python
git 2.21.0.windows.1
visual studio

$ atom -v

Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

Edit: 
github package version: 0.27.0

OS: Windows 10 Pro -1803 r17134.706
```
