### ISSUE TITLE
(Un)staged changes does not use editor font size

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#1858]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The TextEditors used for the (un)staged changes view do not respect the editor font size I have configured.
![unstaged-changes-font-size](https://user-images.githubusercontent.com/2766036/50303129-27a1e580-045a-11e9-99e4-cc1c05e173ce.png)
![editor-font-size](https://user-images.githubusercontent.com/2766036/50303180-47390e00-045a-11e9-972a-0351c76848e4.png)

It looks like this was noticed before with the old view in #331 and fixed in #333.

### Steps to Reproduce

1. Set the editor font size to anything other than 12
2. Open (un)staged changes
3. Compare to a normal text editor

**Expected behavior:** Font sizes to be identical

**Actual behavior:** Font sizes are different

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
Atom    : 1.35.0-dev-add03bdbe
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by simurai** [comment]
That's :grimacing: intended: https://github.com/atom/github/commit/1390a6a8327fa3aaa0060a98c581c9ff8f1d0f88

When adding the changed files https://github.com/atom/github/pull/1829 to PRs, I felt that the default font size is too large. In that commit ☝️, the font size got locked to the font size of UI themes.

But I'll happily revert that commit again. An alternative could be that the file path and hunk titles use the UI font-size, but the diff/code use the font size from Atom's config. Like this:

![screen shot 2018-12-21 at 10 47 28 am](https://user-images.githubusercontent.com/378023/50320077-11edf800-050e-11e9-9a58-185e13e48b7e.png)

**Comment by 50Wliu** [comment]
Yeah, the difference is quite striking:
![different-font-sizes](https://user-images.githubusercontent.com/2766036/50323870-d588b080-04a9-11e9-89d7-9edd9c1bda58.png)

Maybe not that noticeable if the font sizes are off by just one or two, but by three it's hard _not_ to notice.
