### ISSUE TITLE
Show committer name or GitHub username in CommitDetailItem

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1875]
> I usually recognize my co-workers/fellow open-sourcerers by their names or by their Github handles. I would prefer to see at least the committer's name in the commit details pane.
>
> > Stretch goal: show a card on hover with additional information fetched from Github ([inspiration](https://atom.io/packages/github-user-datatip))

![screenshot 2019-01-03 at 12 01 06](https://user-images.githubusercontent.com/3058150/50634615-9483a800-0f4f-11e9-9796-374a7e486487.png)

cc @roberrossmann from https://github.com/atom/github/issues/1870#issuecomment-451115442

**Comment by annthurium** [comment]
just merged https://github.com/atom/github/pull/1906 so this should be in the next release!  Thanks @robertrossman for the suggestion.

**Comment by robertrossmann** [comment]
Awesome, thanks for incorporating that idea! You guys & gals are great! ❤️
