### ISSUE TITLE
Atom freezes on huge changes (but not merely large ones)

### ISSUE THREAD

**Issue by jrial** [atom/github#1887]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Yes
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When selecting huge files in the Unstaged Changes box, Atom freezes.

### Steps to Reproduce

1. Select a huge file in the Unstaged Changes box
2. Atom stops responding.

**Expected behavior:**

Atom refuses to load the diff unless you explicitly tell it to, as it does for "large but not huge" changes.

**Actual behavior:**

Atom freezes. Presumably because it tries to load the huge diff.

**Reproduces how often:**

Always

### Versions

(capman) [17:26] nighty@saltmine capman$ atom --version
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
(capman) [17:26] nighty@saltmine capman$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.14
git 2.17.1
(capman) [17:27] nighty@saltmine capman$ grep mint /etc/apt/sources.list.d/official-package-repositories.list 
deb http://ftp.nluug.nl/os/Linux/distr/linuxmint/packages tara main upstream import backport
(capman) [17:27] nighty@saltmine capman$ uname -a
Linux saltmine 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

(in other words: Linux Mint 19, running kernel 4.15.0)

### Additional Information

* Possibly related to closed issue #1425
* Not sure if it manifests itself always of only with new files; I always get it on those huge SQL dumps.
* For those experiencing the same issue, a temporary workaround is force quitting Atom, restarting it, and pressing CTRL-W as soon as the window displays.

https://www.youtube.com/watch?v=J7Ph1805dSE demonstrates this issue. Steps in the video:

1. I show the file sizes of both files involved: 68kB and 145MB
2. I select the 68kB file to see what Atom does
3. Atom refuses to load the diff and displays a button, allowing us to override this
4. I double-click the 68kB file to stage it and it moves from `Unstaged Changes` to `Staged Changes`
5. Atom automatically selects the next file in `Unstaged Changes`, which happens to be a 145MB SQL dump
6. I try to click on another tab to see if Atom is still responsive. It's not.
7. I wait a bit to see what happens next.
8. Atom shows the Force Quit / Wait dialog

**Comment by smashwilson** [comment]
#1759 should take care of this. Thanks for getting us some example filesizes to start with, that was one of the things we were missing :smile:

> For those experiencing the same issue, a temporary workaround is force quitting Atom, restarting it, and pressing CTRL-W as soon as the window displays.

You can also launch Atom with `--clear-window-state` to discard the serialized session, although that will get rid of any other session data you have as well (tab placement, unsaved buffers, etc).

**Comment by jrial** [comment]
> You can also launch Atom with --clear-window-state to discard the serialized session, although that will get rid of any other session data you have as well (tab placement, unsaved buffers, etc).

True, but I often have unsaved buffers containing todo lists, and I like to preserve my flow (open files etc.), hence I'm hesitant to use that startup option if I can a avoid it. ;)

Should I close this one, as it's a duplicate of #1759?

**Comment by smashwilson** [comment]
> Should I close this one, as it's a duplicate of #1759?

👍 I'll get it 😄
