### ISSUE TITLE
Git Diffs Are Hard to Read in 1.34 (Possibly theme specific)

### ISSUE THREAD

**Issue by framerate** [atom/github#1911]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using the Bliss theme, the new git-diff is very hard to visually follow. (Bug report requested by @annthurium via twitter!

1.32 looked like this:
<img width="258" alt="screen shot 2019-01-14 at 4 02 11 pm" src="https://user-images.githubusercontent.com/74291/51151946-a0118180-1821-11e9-9f43-71cf6b2c15e8.png">

1.34 looks like this:
<img width="350" alt="screen shot 2019-01-14 at 4 01 52 pm" src="https://user-images.githubusercontent.com/74291/51151952-a7388f80-1821-11e9-8115-5fe547c68631.png">

### Steps to Reproduce

1. Install Atom + Bliss Theme
2. Look at the ugly
3. (Thank everyone at atom for their hard work!)

**Expected behavior:** The diff should be super easy to visually grep

**Actual behavior:** I end up using an external program for my diffs!

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

Using MacOS 10.14.3

### Additional Information

[Bliss UI Theme](https://atom.io/themes/bliss-ui)
[Bliss SyntaxTheme](https://atom.io/packages/bliss-syntax)

**Comment by rsese** [comment]
I was poking at atom/atom issues so went ahead and transferred the issue over, hope that's ok @annthurium :v:

**Comment by framerate** [comment]
Nice!

Is there a tutorial on "migrating themes to 1.34" you can point me at? I can probably fork the theme and issue a PR, because as you correctly assumed... I'm rather attached to this one right now :)

**Comment by annthurium** [comment]
We don't have a tutorial -- I did not know that there were community themes that styled the git diff view within atom.  😮 But yeah, if this problem is more widespread we should put some guidelines out.

I suspect that changing  all instances of `.github-HunkView-line` to `.github-FilePatchView-line` will get you most of the way there, although you may have to fiddle with the selectors a bit. 

The code that the github package uses to style the diff view is here, in case that's helpful to refer to:
https://github.com/atom/github/blob/master/styles/file-patch-view.less

and the pr that introduced this regression is here (but uhh, it's a really big pr just to warn you):
https://github.com/atom/github/pull/1512/files

Good luck, and let me know if there are any other questions I can answer -- I'm happy to help.

**Comment by framerate** [comment]
Thank you @annthurium! I'll take a look as soon as I get some downtime from writing my own code :P

And thank you for reminding me why I stick with Atom :)

**Comment by saadq** [comment]
Hey, creator of bliss-ui/bliss-syntax here. Thanks for alerting me of this issue, it should be fixed now. And thanks very much @annthurium for taking the time to help out.

**Comment by framerate** [comment]
Thank you everyone! Tomorrow will be a much nicer code day since I can go back to my favorite syntax! ♥️

**Comment by annthurium** [comment]
yay, thanks @saadq and @framerate for being so kind and understanding.  

Going to close this out now but please reopen if you have any additional questions or concerns.  Happy to chat about theme stuff anytime so don't hesitate to ping me. 😄
