### ISSUE TITLE
No github login

### ISSUE THREAD

**Issue by nichtDerFuchs** [atom/github#1914]
### Description

On the GitHub tab, there is no "login to GitHub" button.

### Steps to Reproduce

1. Open GitHub tab
2. GitHub tab is empty

**Expected behavior:**

There will be a login button.

**Actual behavior:**

The tab is empty.

**Reproduces how often:**

All the time

### Versions
apm -v
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.7.1
git 2.20.0.windows.1
visual studio

atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

Windows 10 Professional

![Screenshot of the github tab](https://user-images.githubusercontent.com/34921068/51345325-f1787580-1a9a-11e9-9304-d05aa6462cda.png)

**Comment by rsese** [comment]
Thanks for the report!  Do you have a Git project open while you have the GitHub tab toggled on?

**Comment by christinahaig** [comment]
I am having the same problem.  There is a Git project open, but I can't understand how to close it.

**Comment by nichtDerFuchs** [comment]
Fixed it!

It only opens when a Git project, which was created with GitHub Desktop, is already open. It didn't open with Git projects created differently for me.
