### ISSUE TITLE
error: cannot spawn undefined: No such file or directory

### ISSUE THREAD

**Issue by 233cy** [atom/github#1915]
请问error: cannot spawn undefined: No such file or directory怎么解决？
![default](https://user-images.githubusercontent.com/29916783/51438042-d51a4a00-1ce1-11e9-977c-0f08773e68e5.png)

**Comment by 233cy** [comment]
![default](https://user-images.githubusercontent.com/29916783/51438401-a5ba0c00-1ce6-11e9-985f-d153df26acc1.png)

**Comment by 233cy** [comment]
临时解决办法，Git不要使用ssh链接，使用https才可以如图
![image](https://user-images.githubusercontent.com/29916783/51614852-78c55d80-1f61-11e9-840d-93611982841e.png)

**Comment by rsese** [comment]
Thanks for the report!  

Looks like you have a workaround, thanks for mentioning that:

> 临时解决办法，Git不要使用ssh链接，使用https才可以如图

translation:

> Temporary solution, Git don't use ssh link, use https to figure

Based on this and the screenshots you shared, there have been similar reports in https://github.com/atom/github/issues/1215 (there's a lot going on in there) so we'll close in favor of that issue for now.

Lastly, for future issues it would be helpful if you use the issue template - the information in the template is super helpful for us when triaging issues.
