### ISSUE TITLE
GitLab access

### ISSUE THREAD

**Issue by TriMoon** [atom/github#1924]
### Description

I want to use this package to access repos that are on **GitLab**.

### Steps to Reproduce

1. clone a repo from GitLab
2. open atom with a file from that repo (while inside that directory ofcourse)

**Expected behavior:**

Atom would show the same info for the repo as it shows for repos from GitHub

**Actual behavior:**

I get a message telling: &ldquo;_This repository does not have any remotes hosted at GitHub.com._&rdquo;

**Reproduces how often:** 100%

### Versions
```console
~/git/ atom-beta --version; apm-beta --version; uname -a
Atom    : 1.35.0-beta0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.0-beta0
python 2.7.15+
git 2.20.1
Linux debian 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux
```

### Additional Information
There seems to be a repo that tried something similar but it has stalled. https://github.com/sergeysova/atom-gitlab
Maybe contact them if you implement this possibility within your package.

**Comment by Aerijo** [comment]
I don't see how this is relavent to the GitHub package; GitLab integration would be completely distinct. The only relation it has to GitHub is that both store git repos. Beyond that, their API, authentication model, etc, would be totally different.

It sounds like a fine community package, but not something that belongs in core, much less a part of this package.

**Comment by vanessayuenn** [comment]
Hello @TriMoon, thanks for opening this issue. Unfortunately, there is currently no plan in foreseeable future to extend the GitHub tab to support repos hosted outside of GitHub.com. This is because the GitHub tab functionality is intrinsically tied to APIs and features unique to GitHub, and hence cannot be easily extended to support other platforms. The git tab, however, will continue to work for any git repository regardless of where it's hosted. Hope this helps!

**Comment by TriMoon** [comment]
@Aerijo , @vanessayuenn 
Ok i understand, didn't know their API's etc differed that much :+1: 
But maybe it's an idea for you guys to make a similar package for GitLab, as it is something a lot of private developers use these days, be it on GitLab.com or own servers,  since GitHub was taken over by a comercial company like M$...
Eg. Support OpenSoftware **more** :wink:

**Comment by archcorsair** [comment]
@TriMoon Just do you know, Atom is developed by GitHub..

**Comment by TriMoon** [comment]
> @TriMoon Just so you know, Atom is developed by GitHub..

Then i will be dropping Atom as soon as they start adding stuff that's not open-sourced and free to re-use (eg. proprietary), which will happen sooner as later with anything M$ touches... :-1:

**Comment by Aerijo** [comment]
@TriMoon Perhaps my comment above where I say `not something that belongs in core` is a bit misleading; nothing about this package is core. A community package for GitLab could be just as capable as this one. The only difference is that Atom has put in a commitment to maintain this package.

As for who would make it, you'd probably have to start with people who use GitLab. As you say, I'm sure there are many, but it's unlikely any Atom staff will be using it enough to invest the time and effort. Nor do I expect them to suddenly create and start maintaining another package on top of the existing workload.

Note though, that this package _is_ entirely open source, so might be useful as a starting point for anyone who wants to put in the effort. Though the API will be different, the core concepts / features are probably the same and it may end up meshing nicely.

Personally, I don't use this package and wouldn't use a GitLab one either. I use the website itself for everything beyond pushing commits. So I don't have a reason to contribute to such a package.

**Comment by Arcanemagus** [comment]
> that violate the users privacy and anonymous state.
> (Disabling Telemetry instantly now)

`telemetry` data is already completely anonymous. The team actually spent quite a bit of work rewriting the package so it sends the data directly to GitHub instead of through Google Analytics as it was before so they could maintain complete control over the data without a 3rd party being able to access it.

The sending of data is also opt-in, so unless you previously agreed to sending the data it wasn't doing anything in the first place. There's no harm in disabling sending of telemetry though if you don't trust it 😉.

**Comment by TriMoon** [comment]
@Arcanemagus Under normal circumstances the end user could indeed trust the developers to keep that data secure, but in the case of a commercial company like M$ who nowerdays owns GitHub one can not as has been proven over and over in the past...
To make it really transparent of how and what they collect they should provide direct link(s) to the **source code parts** where this functionality is handled... :tongue: 
And yes i **had** enabled it before, at install time, until https://github.com/atom/github/issues/1924#issuecomment-459063601 opend my eyes about this project not being a normal community driven product...

**Comment by archcorsair** [comment]
@TriMoon I hope I haven't mislead you into thinking Atom is not a community driven project with my comment, it very much is. That's why you and I, who are not project owners can contribute code and opinions here on this very repo.

**Comment by Arcanemagus** [comment]
You can find the full source code for `telemetry` here: https://github.com/atom/telemetry

Note that it provides a service that other parts (such as the `github` package) hook into, so you aren't going to find many (any?) of the parts where data is collected there.

**Nothing** about Atom is closed source other than the backend service stuff like the server part of the package ecosystem.

**Comment by TriMoon** [comment]
@Arcanemagus 
> You can find the full source code for `telemetry` here: https://github.com/atom/telemetry
> 
> Note that it provides a service that other parts (such as the `github` package) hook into, so you aren't going to find many (any?) of the parts where data is collected there.
> 
> **Nothing** about Atom is closed source other than the backend service stuff like the server part of the package ecosystem.

Thanks for the link to the [telemetry code](https://github.com/atom/telemetry). :+1: 
Starting a sentence with  **Nothing** and then negating that fact in the same sentence is not convincing anyone that it is that way, its actually admitting that the software is not 100% open in a "hide-by-obscurity" way...
As everyone knows the tracking happens in that 'back-end service stuff' that can breach anonymity using the committed data combined with IP etc.
**Anyway lets not derail into data mining and stuff and close this off-topic discussion branch.**
/sign-out of issue
