### ISSUE TITLE
Opening staging view autohighlights first hunk

### ISSUE THREAD

**Issue by colingm** [atom/github#1933]
### Description

With most recent updates whenever I open the staging view for a file it seems to auto highlight the first hunk entirely in blue making it now more difficult to view that hunk without first clicking off of it.

### Steps to Reproduce

1. Have a project that is using git
2. Edit a tracked file so that it is recognized by git as having changed
3. Open the git side panel
4. Click on the changed file to open the staging view

**Expected behavior:**

The file to open in staging view with nothing selected

**Actual behavior:**

The file opens and the first hunk is always auto highlighted with the blue colors making it harder to see due to contrast.

**Reproduces how often:**

100% of the time

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
MacOs Mojave 10.14.1

### Additional Information

![image](https://user-images.githubusercontent.com/11670266/52129569-d4e54d00-2605-11e9-8324-c9488760e533.png)

**Comment by annthurium** [comment]
@simurai would it make sense to make the colors for diff highlighting brighter? A few folks have complained about them being hard to see.

**Comment by simurai** [comment]
👍 Yeah, it bugs me too that the blue selection makes the thing you want to read harder to read.

Something that might be ok: Instead of using a blue background on the diff, **only** have the blue background in the gutter and hunk header. I'll give that a try.

**Comment by simurai** [comment]
> Instead of using a blue background on the diff, **only** have the blue background in the gutter and hunk header.

:point_up: that didn't feel right. So instead the blue background is just more faded for hunks, see #1949.
