### ISSUE TITLE
Resolved comment showing up in Files Changed tab

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1937]
<img width="1283" alt="banners_and_alerts_and_refactoring_builders__do_not_merge__by_annthurium_ _pull_request__1919_ _atom_github_and_pr__atom_github_1919_ _refactoring_builders__do_not_merge__ ___github_github" src="https://user-images.githubusercontent.com/7910250/52246111-827c8880-28b2-11e9-9f15-264d1477c8d1.png">

This comment lives in the fake PR we use for UXR studies -- https://github.com/atom/github/pull/1919

Tested using a local build of Atom with github@v0.25.0-0 pre-release. https://github.com/atom/atom/pull/18787, commit b83bd8f

**Comment by annthurium** [comment]
should be resolved by RCID stuff, because we no longer show the comment, just a decoration and it's ok to have decorations for unresolved comments.
