### ISSUE TITLE
"Files" tab pending comment threads appear as separate

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1943]
Repro steps:
1. Opened PR "Files" tab in Atom
1. Added a comment in an existing thread
1. Refreshed in Atom

Expected: New comment appears as part of thread
Actual: New comment appears separately and looks like the beginning of a new thread

<img width="1276" alt="multiple_threads_by_kuychaco_ _pull_request__5_ _kuychaco_test-repo_and_issueish_ ___github_github" src="https://user-images.githubusercontent.com/7910250/52295864-d89d0a80-294a-11e9-8c99-b3d9abb76085.png">

@simurai can you do some of your styling ✨

**Comment by kuychaco** [comment]
Hmm maybe it's not just non-review comments... 

<img width="1439" alt="issueish_ ___github_github_and_multiple_threads_by_kuychaco_ _pull_request__5_ _kuychaco_test-repo" src="https://user-images.githubusercontent.com/7910250/52296321-0e8ebe80-294c-11e9-8243-d74182884487.png">

And likely not just a styling issue...

**Comment by kuychaco** [comment]
Ooooh it's that we're not handling pending comments correctly! Once I submitted the review that contained those comments they showed up as part of the correct thread...

**Comment by smashwilson** [comment]
Fixed because we're reading review comments from the `reviewThreads` connection now, which correctly groups pending comments into the right threads.
