### ISSUE TITLE
Comment threads on same line appear in the wrong order

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1944]
<img width="1323" alt="multiple_threads_by_kuychaco_ _pull_request__5_ _kuychaco_test-repo_and_pr__kuychaco_test-repo_5_ _multiple_threads_ ___github_github" src="https://user-images.githubusercontent.com/7910250/52298037-06d11900-2950-11e9-811b-d282de4db0a3.png">

Note: the comments _within_ the thread seem to be ordered correctly. But the threads themselves are not.

Test PR: https://github.com/kuychaco/test-repo/pull/5/files

**Comment by smashwilson** [comment]
We've changed to using the `PullRequest#reviewThreads` connection in GraphQL in #1995, which might fix this for us by :sparkles: magic :sparkles:. But we should at least verify :smile:

**Comment by kuychaco** [comment]
Verified this is fixed in v0.28.0 ✨✨✨
