### ISSUE TITLE
Funky comment ordering within thread

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1945]
Found a PR that has some funky comment ordering in Atom -- https://github.com/grokys/PullRequestSandbox/pull/23/files

Seems like an edge case, as comment ordering for https://github.com/kuychaco/test-repo/pull/5 appears to be fine.

![pr__grokys_pullrequestsandbox_23_ _testing_pr_comments__ ___github_github_and_testing_pr_comments__by_grokys_ _pull_request__23_ _grokys_pullrequestsandbox_and_finders_course](https://user-images.githubusercontent.com/7910250/52304587-0e4cee00-2961-11e9-9a9c-7c00220011d1.png)

Upon investigation, the "replyTo" field for the comments is not what I expected / have seen in other comment threads... usually the "replyTo" field always points to the top-level comment ("Comment 1 here." in this case). But we see that most of the comments in this thread actually refer to the comment directly before them. 

![testing_pr_comments__by_grokys_ _pull_request__23_ _grokys_pullrequestsandbox](https://user-images.githubusercontent.com/7910250/52304425-b7dfaf80-2960-11e9-8aa1-0611df05b91b.png)

Not sure when/why this happens... I looked the the `pullRequestReview` id for each of the comments and it seems that each comment belongs to a different review (as they are all distinct)... this is likely because all of the comments were made as stand-alone comments, and not part of an actual review. Though maybe I'm missing something here 🤔 

| pullRequestReview ID |                      Comment body |
| ---------------------| ------------------------------ |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzYzMjY4OTQ |   Baz  |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzQzNjI0MzY |   Bar |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzQzNjEzNTU |   Foo |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzQzNTIwNzk |   Testing |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzM4NTUyODY |   Comment 1 here |
|  |  |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQwMTc3MzU  |  Why are there more comments here than on .com? |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzM4NTUyODY  |  Comment 1 here |
| | |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NTcxNjM3OTU  |  Inline HTML snippet |
| MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzM4NTUyODY  |  Comment 1 here |

**Comment by kuychaco** [comment]
> each comment belongs to a different review (as they are all distinct)... this is likely because all of the comments were made as stand-alone comments, and not part of an actual review

Tested this hypothesis in https://github.com/kuychaco/test-repo/pull/5/files#r254052376

Turns out the standalone comments I made still pointed to the same root review as their "replyTo" comment... so I'm not sure how  comments in https://github.com/grokys/PullRequestSandbox/pull/23/files#r112532110 ended up with a "replyTo" id that is different from the root comment 🤔

**Comment by smashwilson** [comment]
We've changed to using the `PullRequest#reviewThreads` connection in GraphQL in #1995, which might fix this for us by :sparkles: magic :sparkles:. But we should at least verify :smile:

**Comment by kuychaco** [comment]
Verified this is fixed in v0.28.0 👍
