### ISSUE TITLE
TypeError: Cannot destructure property `startBufferRow` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1946]
Got this error when trying to view the PR pane item "Files" tab for https://github.com/apiaryio/metamorphoses/pull/88 (pulled from list here https://github.com/github/analytics/pull/454)

<img width="837" alt="pr__apiaryio_metamorphoses_88_ _chore__decaffeinate_ ___github_github" src="https://user-images.githubusercontent.com/7910250/52306243-58d06980-2965-11e9-9d8d-b46ab854085d.png">

**Comment by annthurium** [comment]
Trying to repro this and running into that graphQL bug:

<img width="1023" alt="screen shot 2019-02-26 at 11 23 46 am" src="https://user-images.githubusercontent.com/3781742/53440366-34dad380-39b9-11e9-81bf-78b26721c06c.png">

@kuychaco did you happen to come across any other examples?

**Comment by vanessayuenn** [comment]
Came across this while QA-ing for #2005 too.

Steps to reproduce:
1. open a PR on dotcom
2. make an few inline comments in a file that's large enough to be diff-gated in atom
3. expand collapsed filepatch in PR view in atom

**Comment by kuychaco** [comment]
> Came across this while QA-ing for #2005 too.

@vanessayuenn did you see this exact error (`Cannot destructure property `startBufferRow` from 'undefined' or 'null'`) or was it the `offset` error that you're putting in a fix for?

I can't seem to repro this on our `all/review-comments` branch. In which case I might just close this issue unless you happened to be able to repro it

**Comment by vanessayuenn** [comment]
@kuychaco it was `Cannot destructure property offset from 'undefined' or 'null'` which occurred one line below where the error you encountered was thrown. I believe they're stemmed from the same issue -- we forgot to reset `diffRowOffsetIndices` upon expanding a large file patch that was "skipped" when we process it in the first run. 

I'm not able to repro the exact bug you're describing, even in a branch without the fix we put in, too.
