### ISSUE TITLE
Atom doesn't ignore commit template when template begins with comment 

### ISSUE THREAD

**Issue by jd12** [atom/github#1972]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description
Comment lines are included in the commit message when the commit template starts with comments

### Steps to Reproduce
1. Create a `~/.git-commit-template.txt` file that contains [git-commit-template.txt](https://github.com/atom/github/files/2891860/git-commit-template.txt)
2. Run the command `git config --global commit.template ~/.git-commit-template.txt`
2. Execute the command `touch test` from the command-line inside a Git repository
3. Launch Atom 
4. Open the Git panel
5. Double-click the `test` file in the Unstaged Changes panel
6. Type `foo` on the first non-comment line of the Git commit message box
7. Click "Commit to master"
8. Go back to the command line and execute `git log -1`

**Expected behavior:**

The commit comment text to consist only of `foo`

**Actual behavior:**

The commit comment contains the entire commit template

**Reproduces how often:**

100%

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

OS: MacOS High Sierra 10.13.6

### Additional Information

Says it was fixed in https://github.com/atom/github/issues/1817

Don't think it accounts for when the git commit template starts with a comment

**Comment by annthurium** [comment]
hello, thanks for reporting! 👋 

The fix that was merged to address this problem has not made it into Atom beta yet, so keep an eye out for the next beta release.  The fix should work for commit templates that begin with a commented line.

Let me know if you have any additional questions.

**Comment by annthurium** [comment]
Going to close this out since that fix has now rolled into stable, but please feel free to reopen if there are additional questions or issues.
