### ISSUE TITLE
Git Panel opens on every save

### ISSUE THREAD

**Issue by trevans24** [atom/github#1993]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description
The Github panel opens every time I save. For the longest time with this package, I could save all day long and it would never open and show me the differences in my branch to what I just saved. It was nice to have when I wanted to open and see all changes, but since I save and push to my git frequently I don't need to see this panel every save

### Steps to Reproduce

1. In any project start doing some changes different to what is on the branch, you are working on.
2. Do a core:save `cmd-s`
3. The git panel just opens by itself. It never used to do this and now manually closing it doesn't help either.

**Expected behavior:**
Leave it as it was where if I want to open the git panel and use it I would. Not to open because I save my project and haven't pushed to GitHub/bitbucket just yet. This setting never happened in the last 2 plus years I have had this package in Atom

**Actual behavior:**
The panel opens every save `cmd-s` and I am getting tired of closing it, and don't want it taking up a tab always open

**Reproduces how often:**
Every time you save (100% of the time)

### Versions
Atom 1.34.0
MacOS Mojave 10.14.2

### Additional Information
I tried toggling keybindings and making sure there were no extra settings added in the settings part of the package.

I also looked for similar issues like this one: [issue](https://github.com/atom/github/issues/1816)
but there seems to be nothing about what would be done to solve the issue or how to stop it from toggling on by itself

**Comment by annthurium** [comment]
@trevans24 thanks for reporting 👋 

Do you happen to have any merge conflicts present?  Can you reproduce this bug in multiple different repositories?

**Comment by wmgroot** [comment]
The tab appears automatically for me when I have unmerged paths present in `git status`. I would prefer if there was an option to never have the git pane appear, as I don't need the additional information to resolve my conflicts. It would be fine for me if the setting defaulted to showing the pane to users as it is now.

I would prefer not to disable the git integration package, as I do still like have the coloring and highlighting that the package provides while viewing the conflicts through the editor.

Sidenote: Why is the package called Github Integration and not Git Integration? It seems like many of the features are generic to just git, and are not specific to Github.

**Comment by annthurium** [comment]
Sorry about that!  I believe we have a fix for this in Atom 1.35 beta.  Would you mind trying Atom Beta and seeing if that resolves the issue?  (Alternately you can wait until the next atom release where what's currently beta rolls over into stable.)

for more context: https://github.com/atom/github/pull/1822

**Comment by annthurium** [comment]
friendly ping on this.  Now that Atom 1.35 stable is out, could you try upgrading and see if the bug is present in that version?

**Comment by annthurium** [comment]
going to close this out, but feel free to reopen if there are additional issues.
