### ISSUE TITLE
My editor is painfully slow, can't even type

### ISSUE THREAD

**Issue by nikoladim123** [atom/github#2022]
can you just let us disable github integration?????

_**Moderator's note:** Edited to remove foul language_

**Comment by annthurium** [comment]
Hi there. Sorry you're having trouble. Can you please provide specific reproduction steps and let us know what version of Atom you're running? This info helps us help you.

**Comment by nikoladim123** [comment]
i have a big folder with .git in it, and i DO NOT WANT TO INTEGRATE IT TO ONLINE GITHUB EVER! 
everytime i make subfolder and subfiles in that big folder, it gets mega lagy, because crap is trying to integrate whole big folder with my gh repo, WHICH I DO NOT WANT!
therefor every letter i type it has like 1 sec lag...
im using the latest version of atom. i tryed all the solutions i found online discussions about the same proble, and nothing helps, i just cant turn of github from atom, i want it removed completly from atom , i hate it, everyone hates it

**Comment by lee-dohm** [comment]
@nikoladim123 your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.
