### ISSUE TITLE
Repository not found in every private repo

### ISSUE THREAD

**Issue by der-eismann** [atom/github#2038]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Yes
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The GitHub tab is unusable in every private repo I cloned. The tab is just showing "Repository not found for the remote `origin`.", although the URLs are perfectly fine. In our public repos it shows existing pull requests.

### Steps to Reproduce

1. Clone private repo via SSH
2. Open repo in atom
3. Open GitHub tab, see mentioned message

**Expected behavior:**

See all existing PRs and that I am on the default branch

**Actual behavior:**

See "Repository not found for the remote `origin`."

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 2.7.16
git 2.21.0
```
On Solus 4.

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify:

> in every private repo I cloned

Are these all private repositories owned by your (or some other user) account, or are they owned by an organization account?  If an organization account, can you check if OAuth App restrictions are enabled in the organization /cc https://github.com/atom/github/issues/1010#issuecomment-422882361?

**Comment by der-eismann** [comment]
Thanks for the quick reply! They are all owned by an organization account indeed, I forgot to mention that. I will check the settings with an org admin and give feedback.
Maybe it would make sense to extend the error message with the OAuth info?

**Comment by der-eismann** [comment]
Alright, my admin won't allow access for the Atom package, so I guess I won't be using that feature. Thanks anyway!

**Comment by rsese** [comment]
Ahh ok, thanks for confirming :+1:

> Maybe it would make sense to extend the error message with the OAuth info?

Looks like others asked about this in https://github.com/atom/github/issues/1010 too, I'll make a note to open an issue with the suggestion.
