### ISSUE TITLE
reconsider grouping of review comments 

### ISSUE THREAD

**Issue by annthurium** [atom/github#2078]
we got some feedback from a user, via twitter:

https://twitter.com/flaximus_prime/status/1118210262446821376

"When there are many comments in a review, and some are resolved, it’s hard for me to scan that list and pick out those not resolved. They’re interspersed and it just doesn’t work for my eyes/brain. I’d love a way to hide the resolved ones or group them."

![image](https://user-images.githubusercontent.com/3781742/56233797-bc97a280-6038-11e9-8bde-72d1b8313e4d.png)

We tried to validate some hypotheses about comment ordering / grouping during our initial user research, but the results were inconclusive.  It could be worth revisiting comment grouping/ordering, now that we have something shipped.

**Comment by vanessayuenn** [comment]
Closed via #2117
