### ISSUE TITLE
Comment editing

### ISSUE THREAD

**Issue by vanessayuenn** [atom/github#2112]
Let's add capabilities to edit PR comments, code review comments, and issue description! 

I am envisioning a kebap menu at the top right corner that, when clicked, will have a context menu drop down with the options: `report abuse` (existing already), and `edit`. When in "edit mode", the content will be replaced by a textbox prefilled by existing text, in proper markdown format.

**Comment by smashwilson** [comment]
Fixed by #2124 :sparkles:
