### ISSUE TITLE
Atom's commit button does not work since version 1.36.0

### ISSUE THREAD

**Issue by danielvallecl** [atom/github#2182]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

The commit button from the GitHub tab has not worked since Atom version 1.6X. The last version that I can get to work is version 1.35.1.

### Steps to Reproduce

1. Stage any changes to commit
2. Press commit button

**Expected behavior:** Commit to be executed

**Actual behavior:** Nothing

**Reproduces how often:** Always

### Versions

Version 1.36.0 forward. Tried it also on 1.38.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by danielvallecl** [comment]
Nothing appears on the developer console. Also happening with version 1.38.2

**Comment by rsese** [comment]
Just to clarify (and after looking at https://github.com/atom/github/issues/2188), you don't happen to be using a commit message that starts with <kbd>#</kbd>?  If you just enter "Test", do you still have the same problem?  

Also, what operating system are you running?

**Comment by erindotio** [comment]
Also having this issue.

macOS version 10.14.5 (18F132)

Atom version 1.38.2

**Comment by danielvallecl** [comment]
> Also having this issue.
> 
> macOS version 10.14.5 (18F132)
> 
> Atom version 1.38.2

Same behaviour still happening in the 1.39 beta versions. Pushing from the terminal works as usual but not from within Atom.

**Comment by smashwilson** [comment]
Can you enable git diagnostics in the GitHub package settings and share any output produced for the "commit" command?

I'm not sure how the commit process could be failing in a way that wouldn't trip an error notification, but that should help narrow it down.

**Comment by alekseyp** [comment]
Not sure if it's related, but I had the same issue, and it was due to the `~/.gitconfig` and _template_ that was deleted from FS

```
[commit]
        template = /Users/xxxxx/.stCommitMsg
```

After removing it from config - atom is able to commit again.

**Comment by kentron** [comment]
I had the same problem as alekseyp comments. I've renamed my home directory time ago and .gitconfig template was pointing to the former. Since 1.36.0 the commit didnt work because its reading the template directive. Works for me now.
