### ISSUE TITLE
Add support for git submodules

### ISSUE THREAD

**Issue by johann1301h** [atom/github#2274]
![Skjermbilde 2019-09-18 kl  12 49 51](https://user-images.githubusercontent.com/25029220/65142359-d2a7f580-da12-11e9-9b7b-bac069c312a7.png)

**Comment by rsese** [comment]
Thanks for the suggestion!  It's helpful if you fill out the issue templates as much as possible, it helps us understand the request.  For example, from your screenshot I think that you're asking about UI support for submodule commands?  Not sure if that's the case or if you're more talking about submodule support in general but In any case, support for submodules is being tracked in https://github.com/atom/github/issues/309 so we'll close in favor of that issue for now.
