### ISSUE TITLE
Commit Diff: Jump to file does nothing

### ISSUE THREAD

**Issue by wadethestealth** [atom/github#2310]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When selecting a past commit, a diff view pops up of the commit, but when you right click there is a jump to file context, which when clicked does nothing rather than taking the user to the file shown in the commit diff.

### Steps to Reproduce

1. Open past commit diff
2. Right click on a line
3. Select 'Jump To File'
4. Nothing happens

**Expected behavior:**

You jump to the file.

**Actual behavior:**

Nothing changes.

**Reproduces how often:**

100%

### Versions

Atom    : 1.42.0-nightly8
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
OS: Windows 10

**Comment by rsese** [comment]
Thanks!  Confirmed on macOS 10.14.6 with 1.42.0-nightly8 :+1:
