### ISSUE TITLE
"Jump to File" in pull request reviews always leads to a path the first directory of a current project

### ISSUE THREAD

**Issue by aviatesk** [atom/github#2330]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

"Jump to File" in pull request reviews always leads to a path in the first directory of a current project, and so sometimes leads to wrong files.

### Steps to Reproduce

1. Open a project with multiple directories, where `dir1` is the first directory
2. Open a pull request review of a directory (`dir2`), which is not the first one
3. Click "Jump to File" button (say for a file `src/file`)

**Expected behavior:**

We want to land to `dir2/src/file`

**Actual behavior:**

It lands to `dir1/src/file`

** Example **

So if we have a project like below, `dir1` is `JunoLab`, and `dir2` is `Atom`:
![image](https://user-images.githubusercontent.com/40514306/68414050-cc442780-01d2-11ea-96e9-2732a01cfa16.png)

and in a PR review of **`Atom`** repository, when we click "Jump to File" for `Atom/src/goto.jl`, it leads to `JunoLab/src/goto.jl` instead of `Atom/src/goto.jl`
![image](https://user-images.githubusercontent.com/40514306/68414148-f7c71200-01d2-11ea-9084-262ba5af4188.png)

**Reproduces how often:**

Everytime

### Versions

> `atom --version`

```
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 3.7.1
git 2.24.0.windows.2
visual studio
```

github package version: `0.31.1`

**Comment by wadethestealth** [comment]
Can reproduce. It seems to just tack on the path to the current project and attempt to open even if that file doesn't exist it will open a new file.
