### ISSUE TITLE
Clicking Stage All on the Git tab has no effect.

### ISSUE THREAD

**Issue by theking2** [atom/github#2396]
### Description

Unstaged Changes are not Staged when clicking Stage All

### Steps to Reproduce

Open a git controlled folder
Make changes to a file
Under view toggle Git Tab until it is vissible
#make sure there are items listed under Unstaged Changes
Clicking Stage All

**Expected behavior:**
Unstaged items move to the Staged Changes item list

**Actual behavior:**
nothing happends

**Reproduces how often:**
100%

### Versions
 Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

Windows 10
github 0.30.0

### Additional Information
git configuration was created with git bash

**Comment by darangi** [comment]
I am currently unable to reproduce this on mac OS catalina. Can you reproduce this in safe mode? To run atom in safe mode, execute `atom --safe` from your terminal.

**Comment by Borumer** [comment]
Same problem on Windows 10 Version 1.44.0

**Comment by daniel-endraws** [comment]
I'm having the same problem

**Comment by theking2** [comment]
Was solved?
