### ISSUE TITLE
Wrong path when create repository for single files

### ISSUE THREAD

**Issue by bmario** [atom/github#2407]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When a single file is opened in the editor and that file doesn't belong to a git repository, the Git pane proposses to `Create Repository` in the path of the actual file, not the directory of the file.

### Steps to Reproduce

1. Open any file that is not part of a repository (for instance the Atom config file `style.less`)
2. Open the git pane, if not open
3. The git pan suggests to create a repository in the path of the file, e.g., `$HOME/.atom/style.less`

**Expected behavior:**

The path of the suggested repository should be the folder that contains the file, in my case `$HOME/.atom`.

**Actual behavior:**

The suggested repository path is the file itself.

**Reproduces how often:**

Every time.

### Versions

Atom: 1.44.0
atom/github: 1.34.0

### Additional Information

This might be an overlook in #2111

**Comment by smashwilson** [comment]
Fixed in #2426, along with some other surprising behavior for the path you'd be prompted to initialize when you open a file in a subdirectory of a non-git project root.
