### ISSUE TITLE
GIT and GITUB Panel blank after start ATOM and open Project

### ISSUE THREAD

**Issue by poudenes** [atom/github#2414]
When I start ATOM and open a Project. I edit my files. I see right below behind git (6) for example. When I click op it the panel is blank.

### Steps to Reproduce

1. Open Atom
2. Open Project
3. Edit File
4. Close Atom
5. Open Atom again
6. Now Github and Git Panels are back again

**Expected behavior:**

After opening Atom and the project you always have to see those panels.

**Actual behavior:**

After opening Atom and the project you won't see those panels

**Reproduces how often:**

100% Always have this problem

### Versions

Atom: 1.44.0 x64
MacOS: 10.13.6 (mid 2010, 12GB, 3,2GHz i3)

**Comment by smashwilson** [comment]
I've seen this happen sporadically myself but I've never been able to nail down repro steps.

Can you clarify:

* In which of your steps are the git and GitHub panels blank? (Step 6 lists them as "back again" but you don't specify when they're missing.) Is it before or after you edit a file?
* How you're opening Atom -- from the command line, from the dock?
* How you're opening your projects specifically. From the system menu? From the context menu when you right-click in the tree view? By running `atom -a` in a different folder on the command line?
* What value do you have set for "Restore Previous Windows On Start" in the "core" section of the settings view?
* Are there any exceptions visible in the dev console?

**Comment by poudenes** [comment]
@smashwilson 

Im using MacOS. Click on icon in Application menu or Dock of OSX
Restore Previous Windows on start: YES

1) Open Atom normal, non of projects are open then
2) File > Reopen Project
3) Edit a file and save
4) Right bottom corner GIT shows a indicator that X files are edited.
5) When click on it. Panel is blank
6) Close Atom
7) Reopen Atom
8) Click on Git on right bottom corner
9) Panel is ok

Im not a diehard developer. Im using Atom to edit my yaml files for my home assistant. And keep track on the changes.

**Comment by smashwilson** [comment]
Ahh beautiful, I was just able to repro 👍 Thanks for the clarifications, that makes this bug much easier to find.

> Im not a diehard developer. Im using Atom to edit my yaml files for my home assistant. And keep track on the changes.

Totally cool, just trying to make sure I have enough info to figure out what's going on.

**Comment by smashwilson** [comment]
Okay, this is fixed in master. Just so you know, it'll take some time to percolate out through our release process (nightly, beta, stable - so two full releases).

In the meantime, you might find it more convenient to close the blank git and GitHub tabs (by clicking the "x") and re-open them (by clicking the files-changed status bar tile or the octocat) rather than doing a full Atom reload :smile:

**Comment by poudenes** [comment]
Thanks!
