### ISSUE TITLE
Ui: Text box width in publish window incorrect

### ISSUE THREAD

**Issue by thirstyice** [atom/github#2433]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
 * [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
  * [x] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Ui issues in Publish window

### Steps to Reproduce

1. Create git repo
2. Use publish on Github feature in github tab
3. Observe text boxes

**Expected behavior:**

Text boxes that are a sensible size

**Actual behavior:**
This:
<img width="606" alt="Screen Shot 2020-04-12 at 19 26 44" src="https://user-images.githubusercontent.com/5591891/79085206-d70c6680-7cf4-11ea-94f6-d87f09580204.png">

**Reproduces how often:**

All the times I've tried so far

### Versions

Atom 1.45.0 x64
MacOS 10.14.6

**Comment by smashwilson** [comment]
Haha oops. Thanks for the report; I have the fix up in #2436 and will be merging shortly.
