### ISSUE TITLE
Using delta for Git diff

### ISSUE THREAD

**Issue by aminya** [atom/github#2462]
It would be nice if we can use delta for Git diff visualization:
https://github.com/dandavison/delta

![image](https://user-images.githubusercontent.com/16418197/81509791-c4288a00-92d2-11ea-859a-8caf69ebaacd.png)

**Comment by smashwilson** [comment]
Swapping out git's diff engine would involve re-engineering our diff parsing engine, rethinking our diff display, bundling a separate binary for all the platforms we support, and in general a _lot_ of effort to get back to where we are presently. I'd also rather implement syntax highlighting (#1357) with tree-sitter APIs than trying to inherit it from an external service for consistency. In short, I don't think this is something we'd consider, sorry.
