### ISSUE TITLE
UI Interact Logic: User should be able to login when working on local repositories.

### ISSUE THREAD

**Issue by PaperFlu** [atom/github#2497]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I'm a fresh Atom user. I was working on several loacl repositories, and I noticed there is no 'login' button in Github tab. I tried to click the "publish on GitHub..." but only to found a dialog keep loading github username. Of course, it can't, I didn't login at all. I tried to search the Internet for an hour, including issues here, nothing useful. I tried to use the Developer Tool to find out if the button was simply hidden, and it was not. I then tried to find all the config file of Atom to see if some was incorrectIy set, nothing again. I finally tried to follow the steps in most tutorials' examples, which is click "Clone an existing GitHub repository..." on an empty window. And, after a clone, the login button appeared.

### Steps to Reproduce

(Haven't tested but should work.)

1. Logout of your current GitHub account in Atom by using Command Palette if you have logged in.
2. Open a local repository.
3. You find that.

**Expected behavior:**

There is a button for users to login.

**Actual behavior:**

The GitHub tab in local repositories is always as if users have logged in.

**Reproduces how often:**

When you are working in a local repository and haven't logged in GitHub before.

### Versions

Atom    : 1.49.0
Electron: 5.0.13
Chrome: 73.0.3683.121
Node    : 12.0.0
On Windows 10 build 2004 x64

### Additional Information

Everything works as expected after I logged in.

**Comment by smashwilson** [comment]
Do you see the login form if you open the GitHub tab? You can open the GitHub tab by running `GitHub: Toggle GitHub Tab` from the command palette, or by clicking the octocat icon in the bottom-right of your status bar:

<img width="474" alt="Screen Shot 2020-09-26 at 10 13 56 AM" src="https://user-images.githubusercontent.com/17565/94342737-08e26280-ffe1-11ea-8608-dd09ac47c59c.png">

Definitely agree that our "logged out" state elsewhere is confusing and possibly broken. Ideally I think we'd show a button that opens the GitHub tab 🤔

**Comment by PaperFlu** [comment]
@smashwilson It would be quite wired if you really tried open the tab when working on a local repository, and then found a login button.

I'm not stupid as hell and I promise the github tab has no button at all at that time.

**Comment by smashwilson** [comment]
Oh! Somehow I totally misread the part of your issue where you were already looking there. Sorry!

That is strange. We do have a "stub" state for those tabs to deal with some timing issues with package state deserialization (... I think? It's been a long time) and I'm wondering if yours is stuck as a stub somehow.

If you close the GitHub tab by clicking the "X" (_not_ by closing the entire right dock with the arrow) and then re-open it, does it re-appear?

**Comment by smashwilson** [comment]
This is fixed by #2572. Thank you for the report, and sorry for the inconvenience and my inability to read 😅  🙇🏻 

In the meantime: you can work around this by opening a project folder that already has a git remote configured (like one you've cloned) and authenticating there.
