### ISSUE TITLE
My GitHub account not stops loading...

### ISSUE THREAD

**Issue by dulgermehmetakif** [atom/github#2499]
My GitHub account not stops loading...
Living in Turkey, 100Mbps Wi-Fi (Laptop does not supports cable internert), Sony Vaio model SVP132A1CW laptop

![Screenshot from 2020-08-09 16-26-52](https://user-images.githubusercontent.com/68149165/89733308-4acd3e80-da5d-11ea-9ea4-8d5043f8b223.png)

**Comment by j0ha** [comment]
Same problem here!

**Comment by mad-cs** [comment]
> Same problem here!

I hope someone helps @j0ha ...

**Comment by PaperFlu** [comment]
I think you might have the same problem here in #2497 .
Have you ever login before? If not, open an empty window, clone a project using Atom then a login button should appear, login and return to your unpublished repository. Now publish button should work. This troubled me for hours of searching a few days ago.

Wish it help.

**Comment by mad-cs** [comment]
> I think you might have the same problem here in #2497 .
> Have you ever login before? If not, open an empty window, clone a project using Atom then a login button should appear, login and return to your unpublished repository. Now publish button should work. This troubled me for hours of searching a few days ago.
> 
> Wish it help.

I downloaded it for first time!
