### ISSUE TITLE
Sync electron-* dependencies with Atom.

### ISSUE THREAD

**Issue by DeeDeeG** [atom/github#2509]
## Summary

Please sync `electron-mksnapshot` with Atom.

## Motivation

- The old `mksnapshot` binaries were [very large on Linux](https://github.com/electron/electron/releases/tag/v4.2.0), for some reason. (See `mksnapshot-v4.2.0-linux-[arch].zip`, these are ~350-480 MB on Linux, ~30-35 MB on macOS and Windows.) This makes building Atom slower and use more network data and disk space on Linux than it has to.
- Judging by this repo's commit history, staying in sync with Atom has been a goal in the past. Testing on the same version as Atom should help stay on top of any Electron-related bugs when using this in Atom.

## Describe alternatives you've considered

N/A, just bumping depednencies and syncing with Atom.

## Additional context

Atom is on `electron-mksnapshot` `^0.4.3`, and `electron-mksnapshot` `^9.0.2`*

* `electron-mksnapshot` 9.0.2 allows you to install a `mksnapshot` binary from an exact Electron version, down to the patch level. This requires installing `electron-mksnapshot` with the `ELECTRON_CUSTOM_VERSION` env var set to the version of electron you're targeting. Atom is currently targeting Electron 6.1.12, and configuring `electron-mksnapshot` to download the exact correct `mksnapshot` binary using this `ELECTRON_CUSTOM_VERSION` env var.

**Comment by smashwilson** [comment]
👍🏻 

I don't suppose you'd have time to put a pull request together? I could get you a quick merge if you did 😇

**Comment by DeeDeeG** [comment]
Closed by #2513. Thanks for merging.
