### ISSUE TITLE
Rendering large diffs takes a while

### ISSUE THREAD

**Issue by kuychaco** [atom/github#252]
Newly added jquery file (10K lines) takes a couple of seconds and the UI becomes unresponsive. This is especially annoying if you're just using using keyboard nav and you happen to scroll past a file with a large diff, or if you accidentally clicked the wrong diff.

Possible solutions:
- [ ] render file diff after a short delay if file is still selected
- [ ] only render first batch of visible lines and defer rendering of the rest, like infinite scrolling

**Comment by annthurium** [comment]
I'm going to assume this was solved by https://github.com/atom/github/pull/1512 and close it out but feel free to reopen if it's still an issue.
