### ISSUE TITLE
Force Push no longer works after Amending a Commit

### ISSUE THREAD

**Issue by gothicserpent** [atom/github#2547]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode> (safe mode does not show the same github amend prompt for me)
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/> (done)
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq> (done)
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom> (done)
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages> (done)

### Description

When I staged an edited file, amended the latest commit, and attempted to force push like i always do in atom, the force push does not execute this time.

### Steps to Reproduce

1. `edit a file` that has a connected repo to github in atom. There should be a mark for a change on the right panel.

![image](https://user-images.githubusercontent.com/36061843/96375128-febd0b00-112b-11eb-8d69-d23b6219cbed.png)
![image](https://user-images.githubusercontent.com/36061843/96375129-04b2ec00-112c-11eb-8140-cfb56eaeb911.png)

2. `stage` the change

![image](https://user-images.githubusercontent.com/36061843/96375135-109eae00-112c-11eb-8c7d-86bffa544e49.png)

3. right click the latest commit and click `amend`

![image](https://user-images.githubusercontent.com/36061843/96359675-59be1600-10ca-11eb-96f4-c5a23ed1f5d5.png)

4. right click the push / pull arrows and click `force push`

![image](https://user-images.githubusercontent.com/36061843/96375169-36c44e00-112c-11eb-9a03-a3490a1b2543.png)

**Expected behavior:**

After a few moments, the change *SHOULD* force push and the repo should be changed.

**Actual behavior:**

No force push is executed, leaving the pull notification still visible.  (in the past, this would always change to 0 changes after a few moments when atom does the force push) .

I attached a screenshot of what I'm seeing now: 

![image](https://user-images.githubusercontent.com/36061843/96359689-896d1e00-10ca-11eb-9a74-b021bb374dee.png)

**Reproduces how often:**

This reproduces 100% of the time for me. 

### Versions

 Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

Windows 10  
(10.0.19041 Build 10941)

### Additional Information

One note to remember here is that this WAS working just a week or two ago when I tried it.

Although this can be resolved by simply force pushing via command line, I would love to see this functionality brought back as I used it all the time. I use amend / force pushes since I'm the only person working on my private repo, and I don't need to make a new commit for small changes I make to my repo.

#### Workaround

![image](https://user-images.githubusercontent.com/36061843/96360503-b58c9d00-10d2-11eb-8bde-ad45f0f52e7c.png)

I had to disable "Block command line pushes that expose my email" in github email settings (https://github.com/settings/emails), and then do `git push --force` in the git commandline (externally from atom) while i was in the repo directory to make this work. 

![image](https://user-images.githubusercontent.com/36061843/96375365-83f4ef80-112d-11eb-817f-27367b77fcfd.png)

After I did this, there was no longer a pull notification in atom.

![image](https://user-images.githubusercontent.com/36061843/96375374-940ccf00-112d-11eb-820b-5fce5652339e.png)

Please let me know if you have any questions, and I hope this helps! Thanks for the great program!

**Comment by gothicserpent** [comment]
@ivoska I noticed you posted about this on another issue which was closed - if you have any more information you're welcome to add it here. thanks.

**Comment by gmichalec-pandora** [comment]
Just want to note that I am seeing the same issue, but using a non-github repository (bitbucket).

**Comment by nickhagen** [comment]
My typical workflow involves rebasing my contributors' branches and force-pushing them up to ensure their branches are up to date with master/main, this is affecting all force pushes as far as my testing goes.  I don't amend or change any files, simply rebase on your branch that is behind master/main and try force pushing and it doesn't do anything since 1.52. Doing this from the command line is my work around, but it would be nice to have this working again!

```
git push --force
```

**Comment by gothicserpent** [comment]
Issue is still persistent for me in this atom version: `Atom : 1.53.0 x64`

**Comment by ivoska** [comment]
I'm not switching from 1.51 till it is fixed :p

**Comment by gothicserpent** [comment]
Issue is **fixed** for me! When I perform the following steps: 

1. `change a file`, creating an unstaged change.
2. `stage` the change
3. right click the current commit on the bottom bar, click `Amend`
4.  ![image](https://user-images.githubusercontent.com/36061843/104790600-85de4700-574c-11eb-9116-30a2c3ec0c92.png)
right cliuck the push/pull bottom bar, click force push and confirm it 
![image](https://user-images.githubusercontent.com/36061843/104790642-af976e00-574c-11eb-9f1a-2d5f6352320d.png)
5.  It displays pushing on bottom bar 
![image](https://user-images.githubusercontent.com/36061843/104790666-be7e2080-574c-11eb-8a4a-cd04dcd222f9.png)
6. Amend successful!









Tested on: Atom 1.54.0 x64 using windows 10 Version 20H2 OS build 19042.746

**Comment by gothicserpent** [comment]
Sorry for waiting so long to close the issue. It's been resolved. Thanks!
