### ISSUE TITLE
Infinite loading github

### ISSUE THREAD

**Issue by kkhanh** [atom/github#2603]
Hi,

I'm running into an issue with the github integration. 

![Selection_048](https://user-images.githubusercontent.com/14584194/103881769-3019f700-50db-11eb-98bc-dcb7a9722898.png)

The main github window is hanging / infinitely loading as well as the fetching button on the bottom. It happens on all my repositories. The safe mode does not solve the problem.

I didnt do anything in particular, just loading atom as I do everyday, is there anyone who could help me ?

**Comment by damien-git** [comment]
Possibly related: #2242

**Comment by kkhanh** [comment]
I got it working by restarting my computer as suggested in #2242 which make no sense...

Thanks
