### ISSUE TITLE
dialog.showOpenDialog is a promise, not a callback

### ISSUE THREAD

**Issue by Aerijo** [atom/github#2605]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

This package uses Electrons `dialog` to open files, in particular [`showOpenDialog`](https://github.com/atom/github/search?q=showOpenDialog) and `showSaveDialog`. [As of Electron 6](https://www.electronjs.org/releases/stable?version=6&page=6#promises) these methods are promise only, with the callback support being removed. The tests mock the interface according to the original behaviour, allowing this to go unnoticed.

It seems the parameters are also different, with an object with more context being returned instead of just the file paths. 

### Steps to Reproduce

E.g.,

 https://github.com/atom/github/blob/5a8faf5bdfa682bbfeb2f1c8af823bbcaa12d254/lib/views/git-timings-view.js#L424-L437

**Expected behavior:**

NA

**Actual behavior:**

NA

**Reproduces how often:**

NA

### Versions

1.52.0+

### Additional Information

This package appears to be failing tests on macOS when upgraded to electron 9. I don't know if this is related though, as it mocks the API anyway.

**Comment by DeeDeeG** [comment]
Looks like this would be resolved by https://github.com/atom/github/pull/2626.

**Comment by smashwilson** [comment]
Yup, fixed. Thanks!
