### ISSUE TITLE
Simplify Pull/Push tooltip

### ISSUE THREAD

**Issue by simurai** [atom/github#311]
## Problem

Now that the branch pull/push buttons are in a tooltip of the status-bar, you have to click 2 times (click to open tooltip + click button) to do these actions.

![1](https://cloud.githubusercontent.com/assets/378023/20167938/3be5ac0e-a762-11e6-99c1-7a1f67032223.png)

It just feels a bit like too much extra work.

## Possible solution

Below an exploration in adding something similar to the [Magic sync button](https://github.com/desktop/desktop/issues/598) like on Desktop.

Clicking on the status-bar items does the action immediately without showing a tooltip. Also only the actions that you can currently do are shown.

### Neither ahead or behind
![4](https://cloud.githubusercontent.com/assets/378023/20167967/65ecf7f0-a762-11e6-9bea-dee2083235d6.png)

### Behind
![2](https://cloud.githubusercontent.com/assets/378023/20167946/4ac0d906-a762-11e6-88a3-fa3ad3c04754.png)

### Ahead
![3](https://cloud.githubusercontent.com/assets/378023/20167953/531699ce-a762-11e6-90f2-4cee7728f283.png)

### Ahead and behind
![6](https://cloud.githubusercontent.com/assets/378023/20167960/5a61f26e-a762-11e6-89ab-2effa10c84a8.png)

### Unpublished
![5](https://cloud.githubusercontent.com/assets/378023/20167977/6e2ad87e-a762-11e6-9c44-fce56dc3b327.png)

This should cover 97.4% of use cases.

## Special cases

Sometimes you might wanna fetch before pulling. Maybe to make sure nobody made more changes on the remote? Or you want to force push. For these cases, we could have a context-menu show up when right-clicking. So at any time there are still available.

![group](https://user-images.githubusercontent.com/378023/33748236-b46ec8bc-dc0a-11e7-86b9-77d96860b2c8.png)

The current popup could still be used for errors or confirmations, for example:

![7](https://cloud.githubusercontent.com/assets/378023/20167987/83d92c70-a762-11e6-8eb2-29b231b2017b.png)

**Comment by kuychaco** [comment]
For the "Special cases" we could additionally offer alt/cmd-clicking for fetching and force pushing to save users some clicks, per @mattmattmatt's suggestion in https://github.com/atom/github/pull/1308#issuecomment-365547324

Regarding errors and confirmations, for now the convention is to use Atom's built-in [notification manager](https://atom.io/docs/api/v1.24.0/NotificationManager) and [confirm prompt](https://atom.io/docs/api/v1.24.0/AtomEnvironment#instance-confirm)

**Comment by zeke** [comment]
> 97.4% of use cases

:)

**Comment by kuychaco** [comment]
Closed by https://github.com/atom/github/pull/1308. Thanks @mattmattmatt ✨
