### ISSUE TITLE
Rename config option for delay before opening FilePatchView

### ISSUE THREAD

**Issue by kuychaco** [atom/github#325]
Come up with better name for the config option that specifies the amount of time to wait before opening a file diff while using keyboard nav in the changed file list (to avoid locking the UI when navigating past a large file diff)

Maybe something like this...
<img width="678" alt="settings_ ___src_test-repo" src="https://cloud.githubusercontent.com/assets/7910250/20585530/b5fd7aaa-b1b0-11e6-85b3-5499a890a5ad.png">

reference: https://github.com/atom/github/pull/318

**Comment by annthurium** [comment]
this is now called "keyboard navigation delay" and I think that's good enough 😄 

going to close this out, feel free to reopen if you'd like to discuss further.
