### ISSUE TITLE
Slow activation time

### ISSUE THREAD

**Issue by winstliu** [atom/github#374]
The github package is taking a fairly long time to activate for me.  Right now it's at ~375ms, which is 4x as long as the package after that (status-bar at 93ms).  Might be something to look into. 🏇 

(It's also one of two packages that take longer than 5ms to load at 19ms)

### Versions

Atom Version (`atom --version`): 1.14.0-dev-b219c28 x64 (Windows 10 x64)

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):  2559ac24455655b9abc626afda685e0e5bed2e3a

**Comment by itotallyrock** [comment]
I've just updated to the latest version of atom, 1.18.0-beta0 x64, and I still consistently, during every boot for a project that has git, take 1 to 2 seconds according to time-cop for just GitHub.

Running Windows 10, GitHub package is 0.0.9, Git is 2.13.0.windows.1

![](https://image.prntscr.com/image/9b4aaa79dbb2420db99779e864e85267.png)
