### ISSUE TITLE
Mark and resolve merge conflicts within the Editor

### ISSUE THREAD

**Issue by smashwilson** [atom/github#383]
Shamelessly yank the merge-conflict parser and an initial UI take based on [merge-conflicts](https://github.com/smashwilson/merge-conflicts) to resolve merge conflicts.

- [x] Parse conflicting hunks in TextEditors that are open on files that currently include merge conflicts. Handle all of those weird [recursive diff3 output](https://github.com/smashwilson/merge-conflicts/blob/master/spec/fixtures/single-3way-diff-complex.txt) [shenanigans](http://stackoverflow.com/questions/16990657/git-merge-diff3-style-need-explanation).
- [x] Add decorations within the TextEditor to identify the _ours_, _theirs_, and potentially _parent_ sections. Style the lines within each conflict hunk.
- [x] Include controls for simple resolutions within the conflict hunk decoration.
- [x] Include a gear icon that triggers a dropdown menu offering more complex resolutions (ours-then-theirs, theirs-then-ours, and so on). See smashwilson/merge-conflicts#185.
- [x] Add a progress bar to each entry in the conflicting files list to indicate the number of conflict hunks that still need to be resolved within each file.
- [x] Warn when staging conflicting files that contain unresolved hunks.

/cc @iolsen, @BinaryMuse, @kuychaco

**Comment by git-vishalshukla** [comment]
How we can navigate next conflict line in large file without scroll manually?

**Comment by kristianb21** [comment]
Not sure where to post this question but is their a particular setting to enable git merge diff3 on Atom? I already have it set globally in my local git. I'm using Atom version 1.25.0.
Thanks for any help.
