### ISSUE TITLE
Confusing button text when amend box is checked prior to entering merge commit mode

### ISSUE THREAD

**Issue by nathansobo** [atom/github#407]
<img width="416" alt="screen shot 2017-01-05 at 11 06 58 am" src="https://cloud.githubusercontent.com/assets/1789/21691800/4d23a48e-d337-11e6-81ed-f7b442abc5af.png">

I'm not *quite* sure how I entered this state. I had a merge commit on `HEAD` and tried to amend it. Then I changed my mind and went to the command line, `reset --hard` back to the previous commit, and then did a `git merge master` again. Now the button says "Amend Commit" and there's no checkbox visible to change the state.

### Versions

Atom Version (`atom --version`):

Atom    : 1.14.0-dev-3960a214e
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):
bd8daf7d748ccd9bfabff8060325dea2a0e1e694

**Comment by no1xsyzy** [comment]
Met same problem with Atom 1.19.6 ia32

# Probable enough steps to reproduce
(I don't have time to mess my repo up right now, but I believe it can reproduce)

1. You must have two computers to access the same remote repo;
2. On one computer, say `A`, edit and commit and push some;
3. On another, say `B`, do some local changes and commit them;
4. On `B`, tick on `amend`, then pull;
5. There are only `Abort Merge` and `Amend commit` buttons, no way to commiting merge from github panel.

**Comment by annthurium** [comment]
we no longer have the amend checkbox, going to close this out.
