### ISSUE TITLE
Cannot pull/push/fetch with github package using ssh

### ISSUE THREAD

**Issue by ungb** [atom/github#411]
### Versions

Atom Version (`atom --version`):
```
Atom    : 1.14.0-dev-09ab7d6
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):
`e652cb81c0dd54ec9e154d1d1c7a379fd55baadd`

**Git pull using SSH**
if I clone via ssh from github and do a pull from terminal, it works, if I try from Atom, this doesn't work.  (Note: my ssh key has a pw on it.)

here's the .git/config info for the repo I am trying for:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = git@github.com:ungb/snippet-creator.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "test"]
        remote = origin
        merge = refs/heads/test
[branch "master"]
        remote = origin
        merge = refs/heads/master
```
**git pull using https**
Also, if I clone from https from terminal and do a git pull it works fine without asking me for details for private repo, I wonder if it's set somewhere, but if try to do a pull from atom it ask for my github login info.
Video of https issue: http://screencast.com/t/wsDz7SyIMNq

.git/config info:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = https://github.com/atom/github.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "as-ns-linux-build"]
        remote = origin
        merge = refs/heads/as-ns-linux-build
```

.gitconfig in userdir:
```
[user]
        name = ungb
        email = ungb@github.com
[github]
        user = ungb
[push]
        default = simple
[credential]
        helper = osxkeychain
[alias]
        co = checkout
        br = branch
        ci = commit
        st = status
```

**Comment by alexpolicastro** [comment]
I am having problems also, it may be because of 2 factor authentication.

**Comment by smashwilson** [comment]
@alexpolicastro If you have two-factor authentication enabled and fetch from an HTTPS remote, you'll need to provide a [personal access token](https://help.github.com/articles/providing-your-2fa-authentication-code/#when-youll-be-asked-for-a-personal-access-token-as-a-password) instead of your password.

We could certainly make that more obvious; I've filed #844 to track that :smile:

**Comment by smashwilson** [comment]
Closing this issue now to track individual credential-handling bugs individually.
