### ISSUE TITLE
Report stack traces in AppVeyor builds that crash Electron

### ISSUE THREAD

**Issue by smashwilson** [atom/github#430]
It'd be a big help to be able to collect stacktraces from builds in AppVeyor where we crashed the renderer. That's a little tricky to do, though.

The major obstacle that I had to just doing this was that I'm not sure where we can get the symbols for Atom/Electron and/or nsfw so that the traces will be useful.

* [relevant stackoverflow question](http://stackoverflow.com/questions/40648843/invoke-cdb-exe-windbg-to-run-noninteractively-and-produce-backtrace-in-case)

**Comment by annthurium** [comment]
@smashwilson, is this still a problem?

**Comment by smashwilson** [comment]
Nah. It turns out that Windows crash dumps can really easily include stuff like sensitive environment variables, so we decided not to do it. And then with a few nsfw PRs and the @atom/watcher work we haven't seen nearly as many native crashes so it became less important.
