### ISSUE TITLE
Determine binary file status for untracked files

### ISSUE THREAD

**Issue by kuychaco** [atom/github#454]
Currently all file patches for untracked files have a falsey value for the `binary` property.

Then consider using `assert.deepEqual` for file diffs, rather than `assertDeepPropertyVals` helper

### Versions

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`): ea44064cbb14f2fa248db504ec3e439059398ad3

**Comment by BinaryMuse** [comment]
Hm I added a thing to detect if untracked files are binary or not, but I'm not sure which property you're referring to.
