### ISSUE TITLE
Improve untracked branches UX

### ISSUE THREAD

**Issue by simurai** [atom/github#462]
Here some thoughts regarding untracked branches.

## Problem

Currently when creating a new branch and then making some commits, the pull/push indicator doesn't increase in value:

![screen shot 2017-01-20 at 9 50 56 am](https://cloud.githubusercontent.com/assets/378023/22131349/20dea64c-def6-11e6-8d83-6a812c36c62f.png)

It's because:

> @kuychaco Since there is no remote tracking branch yet we have nothing to calculate the ahead count relative to and there will be no commits listed to push. You can still push and we'll set up a remote tracking branch for you.

This is ok if you know about it, but could be confusing if not (or you have to keep reminding yourself). It could feel like committing didn't work.

## Solution

For untracked branches show a "Publish" link (with `icon-cloud-upload` icon) instead of the up/down arrows:

![screen shot 2017-01-20 at 10 03 54 am](https://cloud.githubusercontent.com/assets/378023/22131598/cee67282-def7-11e6-9d10-66beeeb4b246.png)

Also change the button in the tooltip:

![screen shot 2017-01-20 at 10 08 19 am](https://cloud.githubusercontent.com/assets/378023/22131764/baf242e6-def8-11e6-942a-e5aa9ac3ba3b.png)

## Concerns

Is "Publish" clear what it means? It's not really a term used in Git. Alternative might be: "Add remote" or "Track".

## Applicable issues

It's not **that** urgent and it also depends if #311 gets considered, then it would already be included there.

### Versions

Atom Version (`atom --version`):

```
Atom    : 1.15.0-dev-6010c4d
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):

```
f0df0b47da3f5e37a001e40271b677d6eea29a75
```

**Comment by kuychaco** [comment]
Closed by https://github.com/atom/github/pull/1308. Thanks @mattmattmatt ✨
