### ISSUE TITLE
Always asks for credentials on Windows

### ISSUE THREAD

**Issue by winstliu** [atom/github#470]
Note: I am unsure if this is something I have to set up separately and github will take care of it, or whether github should be the one remembering my credentials.

Every time I want to push something, the github package prompts me for my username and password.  This gets annoying, especially since I have to use a personal access token because of 2FA.  It looks like there's some credential helper stuff on macOS - I know Windows has one as well, and I'm fairly certain mine is set up to use it as I never get prompts from the terminal.

### Versions

Atom Version (`atom --version`): 1.15.0-dev-9547cab (this is an unpublished commit combining master and the Electron branch)

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`): dc57ad951202cd73f83a4f7e02f70f6d1f1d9758

**Comment by Subomi** [comment]
I don't use atom .. how can i fix this issue .. I believe am having same issue.

**Comment by Subomi** [comment]
Well, I noticed that was nodejs code .. so i ran that in a nodejs session and boom .. i got what i wanted thanks!
