### ISSUE TITLE
Merge commit message unexpectedly displayed in Atom

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#480]
I performed the following operation:

* Merged `origin/master' into my branch on the command line
* Viewed the files in Atom
* Resolved a merge conflict by re-generating the conflicted file
* Added the file and committed on the command line
* Pushed

The following day, when I looked at Atom, the merge commit message was still being shown.

### Versions

Atom Version (`atom --version`):

```
Atom    : 1.14.0-dev-6fb78bd
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`): fbb270e6579952d0cb51d19889e8b4e56f701e46

**Comment by kuychaco** [comment]
@BinaryMuse I believe you put in a fix that should've taken care of this? Double-checking to see if that is the case
