### ISSUE TITLE
"Hub" tab shows random(?) PR on master

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#489]
Two examples, one from settings-view and one from autocomplete-css:
![settings-view](https://cloud.githubusercontent.com/assets/2766036/22353347/f3f5c730-e3ed-11e6-8c07-a8ad01872800.png)
![autocomplete-css](https://cloud.githubusercontent.com/assets/2766036/22353379/148e1e0c-e3ee-11e6-9c9a-98fefdea529d.png)
The PR in question does not change upon reloading Atom.

### Versions

Atom Version (`atom --version`): 1.15.0-dev-751116d

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`): 68eb650
/cc @BinaryMuse

**Comment by kuychaco** [comment]
This is fixed now
