### ISSUE TITLE
Failed commits provide no feedback

### ISSUE THREAD

**Issue by sophaskins** [atom/github#495]
When I try to make a commit, but doing so fails (preconditions fail, or I type my gpg password incorrectly), the changes stay staged, but I don't get any of the output that caused it to fail (or any outward information that it failed, other than that the changes are still staged)

### Versions

Atom Version (`atom --version`): 1.13.1

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`): 11ebd4d314e358dbc2b3218339d6f1d608891b46

**Comment by bwestover** [comment]
@smashwilson - I think this one is fixed by #760 but didn't get auto-closed.
