### ISSUE TITLE
Recent commit log

### ISSUE THREAD

**Issue by smashwilson** [atom/github#554]
Show the most recent two or three commits in beneath the CommitView. This will provide a bit of subtle feedback that creating a commit "did something" rather than disappearing into the aether.

Only render a short SHA and a (likely truncated) description line.

**Comment by BinaryMuse** [comment]
Another issue talking about logging: https://github.com/atom/github/issues/823

**Comment by simurai** [comment]
Now with the docks, the ~recent~ commit log could be its own panel. Then if you wanted, you could drag it under the Git panel and make it look like the mockup above (plus tab).

**Comment by simurai** [comment]
Tried out the "be its own panel" in this static [prototype](https://github.com/atom/github-prototype/tree/history).

It's definitely nice be able to move the history panel anywhere that fits your window size or workflow. You can

- Switch between tabs
- Move it under the commit message
- Or side by side

![history](https://user-images.githubusercontent.com/378023/27576861-749a2b6e-5b59-11e7-9d16-13b2181f5425.gif)

A problem is that I think splitting dock items only gets serialized per project. So you would have to "split the history/log panel" in **every** project.

**Comment by CharlineCouchot** [comment]
Hi there.

Don't know if this is the right place to make a suggestion or if I should open a new issue but the option to disable this log or hide it would definitely be nice.

Thanks !
