### ISSUE TITLE
Cannot look up PR for private repos

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#567]
Looks like the GraphQL API is returning an empty set of pull requests when queried on a private repo. Look into changes in github/github#68308

**Comment by laughedelic** [comment]
I'm still having this problem. This is what I see in the console:

```
<embedded>:332134 Server request for query `Pr` failed for the following reasons:

1. Could not resolve to a Repository with the name 'my_repo'.
   agment F4 on Query {_repository3dNgj3:repository(owner:"my_org
                       ^^^
<embedded>:101159 Cannot find module '../build/Debug/nodegit.node' Error: Cannot find module 
```

I thought that probably some dependency is not installed well, but I don't know how to reinstall this package (disabling-enabling doesn't help).
