### ISSUE TITLE
Undo Discard is broken

### ISSUE THREAD

**Issue by ungb** [atom/github#588]
### Versions

Atom Version (`atom --version`):
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):
bf647675797e3b4e68b7167c1f6f175009c8b8b4

Repro Steps:
1. Open a Package in a git repo that has folders,  Open a file that is in a sub directory. 
2. Make some changes to the file in step 1
3. discard a few changes you made
4.  Click on undo discard

Expected: undo discard

Actual: error in console log

```
root-controller.js:468 Error: ENOENT: no such file or directory, open '/var/folders/lp/h7g12x7j68s02jr25ybpt2vc0000gn/T/github-discard-history-w22r0I/atom/github-package-acceptance.md-before-discard'
    at Error (native)(anonymous function) @ root-controller.js:468step @ root-controller.js:25(anonymous function) @ root-controller.js:25
```
screenshot:
![image](https://cloud.githubusercontent.com/assets/5624870/23531493/81eb9f32-ff5b-11e6-81ec-c07f7e51023b.png)

/cc @kuychaco

**Comment by VityaSchel** [comment]
I just lost dozens of hours because undo discard doesn't work. Guess next time I will commit and push every line of code I wrote.
