### ISSUE TITLE
Remove "Undo Discard" affordance after committing

### ISSUE THREAD

**Issue by nathansobo** [atom/github#605]
Once I have discarded *once* in a project, the "undo discard" button seems to hang around forever. This seems unnecessarily distracting. I like that this button hangs around even after edits, but it seems like we should maybe clear the discard history after committing the containing file.

/cc @kuychaco

**Comment by jnunemaker** [comment]
I'd really like to see undo discard go away at some point as well or have a way to dismiss it. I feel like it hangs around for a while and several times I've hit it instead of the file I wanted to stage which can cause some pain.

**Comment by nathansobo** [comment]
At the very least the button should be moved.

**Comment by the-j0k3r** [comment]
Why cant the discard cached memory just be cleared? like a dismiss option in the dialog options that pops up?

**Comment by the-j0k3r** [comment]
> At the very least the button should be moved.

@nathansobo hows that a solution?

**Comment by dpehrson** [comment]
I would like to add a note that never once have I wanted to use that button for its intended purpose, but I regularly click it by mistake and end up with a very confusing file state.

The prominence of this button should be reduced significantly. It's certainly not more important then "Stage All"

**Comment by ben-z** [comment]
Would it be difficult to add an option to disable that button in the settings?

**Comment by the-j0k3r** [comment]
@ben-z have a read at https://github.com/atom/github/pull/1242 discussion. But short answer is they wont add what you suggest.

**Comment by andreidobrinski** [comment]
May have found a workaround.
1. Undo the discard. Bring all those unwanted changes back up in the git tab.
2. Click on the file you want to discard to open it in the editor pane.
3. Click on the garbage can icon to discard the hunk. (Next to "Stage Hunk")
4. Repeat this for all changes
...
Haven't seen the Undo Discard button since. Hope that helps!

**Comment by the-j0k3r** [comment]
@andreidobrinski sorry if this sounds flippant, but #1242 discussion already covers alternatives and a solution that is likely to be accepted.  See https://github.com/atom/github/pull/1242#issuecomment-342625850 and https://github.com/atom/github/pull/1242#issuecomment-343346270

I think the discussion going on in #1242 applied to this ticket and should be had here though. For that end Ill make a friendly post there.

**Comment by simurai** [comment]
> @andreidobrinski Haven't seen the Undo Discard button since.

Even when discarding again? If so, that sounds more like a bug.

Here another idea: Move undo into the context menu:

![screen shot 2018-02-20 at 10 29 08 am](https://user-images.githubusercontent.com/378023/36403886-fc2fd86c-162a-11e8-849a-3bcdbd0637eb.png)

It's a bit harder to discover, but if it's not your first discard, you might remember that there is an "Undo Last Discard" option.

Or even show "Undo Last Discard" all the time, but disable it if no undos are possible. Electron has an `enabled` option: https://electronjs.org/docs/api/menu-item

**Comment by Boboss74** [comment]
I missclicked again on this evil button...
It took me so long to find out where the change came from T-T

**Comment by 50Wliu** [comment]
> Here another idea: Move undo into the context menu:

This is pretty close to what I suggested in https://github.com/atom/github/pull/1242#issuecomment-341910846 and almost exactly what @BinaryMuse suggested in https://github.com/atom/github/pull/1242#issuecomment-342303559.

**Comment by andreidobrinski** [comment]
@simurai good point. I checked again and what happened is that the Undo Discard affordance moved from the global git tab to the file-specific one. 
![screen shot 2018-02-20 at 2 06 21 pm](https://user-images.githubusercontent.com/22686684/36443899-12b16e30-1648-11e8-92dc-a2493e0c5cae.png)

would be nice to have an option to "permanently discard these changes, remove them from the Undo stash, and don't remind me again".

**Comment by Boboss74** [comment]
Manual fix to hide the _Undo Discard_ button. In your ~/.atom/style.less add this:
```css
atom-panel-container button.github-StagingView-headerButton--fullWidth {
  display: none;
}
```

**Comment by mingelz** [comment]
You can remove *Undo Discard* button via remove `undoDiscardHistory` manually:

1. open `.git/config` file in project directory,
2. remove `[atomGithub]` section, and save this file,
3. reopen the project with Atom

**Comment by smashwilson** [comment]
#1702 makes this much less prominent and harder to click on by mistake, so this is less of an issue now. We might iterate further on the UX here in the future, but it's not in our immediate roadmap, so we're going to close these. We'll open new issues in the future when we're ready for that 👌
