### ISSUE TITLE
Would like a Discard All option

### ISSUE THREAD

**Issue by damieng** [atom/github#611]
Unstaged Changes title bar where `Stage All` lives is a bit crowded already. Maybe either right-clicking Stage All to see a Discard All menu button or holding down alt to see the text change from Stage All to discard all?  Thoughts @simurai

**Comment by cbovis** [comment]
Agreed that there needs to be a confirmation when discarding all changes, especially when called directly via the command palette. I personally wouldn't find a confirmation dialog which gave me the option to destroy or stash my changes. I feel like stashing automatically would annoy me more as I'll then have to manage those stashes at a later point. More often than not if I'm discarding then thats really what I want to do, stashing for me is an explicit action.

I think the key to confirmation dialogs is using them for only the most destructive of actions, the kind of actions where selecting that action by mistake could be painful.

**Comment by simurai** [comment]
> I feel like stashing automatically would annoy me more as I'll then have to manage those stashes at a later point.

Yeah, that would get messy quickly. I was more thinking that auto-stashing would override your old auto-stash. So there would be your manual stashes and only **one** extra auto-stash. This also means that you can only recover your last "discard all".

**Comment by cbovis** [comment]
I just used the individual file discard option within the package for the first time today and realised that there's actually an Undo Discard option built in already. I've not looked into the implementation yet (it doesn't appear to create a stash) but I suspect that could be used to revert any Discard All changes as well...
