### ISSUE TITLE
Upgrade Package on Windows caused package to fail

### ISSUE THREAD

**Issue by Haacked** [atom/github#636]
Upgrading Atom seems to break the package on Windows. I haven't tried to reproduce this regularly. Seems to have happened to me twice. I wanted to log the issue before I forget.

Steps to reproduce.

1. `apm install https://github.com/atom/github
2. Wait till Atom tells me there's an update to atom/github.
3. In the Packages dialog, click "Update" to update the package without closing Atom.

Expected: The package is updated and still works.
Actual: The package no longer works and the package dialog shows the package as being disabled.

### Versions

Atom Version (`atom --version`): 1.15.0

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`): a2a1c61f792544ffac0f0097df5fc52590e33733

**Comment by kuychaco** [comment]
No longer relevant as package is now bundled into core
