### ISSUE TITLE
minor usability nitpick

### ISSUE THREAD

**Issue by technoweenie** [atom/github#645]
Hey all, I ran into something mildly annoying in the commit view of the github plugin. When I stage the hunks for a file, the "Unstaged Changes" tab turns into a regular file tab. If I'm crushing some diff hunks to make a commit, I'd like it to display the unstaged changes for the next file in the list.

![release_asset_rb_ ___github_github](https://cloud.githubusercontent.com/assets/21/24712883/573ca786-19e1-11e7-8600-b1040d14379e.png)

### Versions

Atom Version (`atom --version`):

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):

dce9960042816f969d893f2841263ee61530d4d8

**Comment by BinaryMuse** [comment]
Since the solution here is the same as in #606 I'm gonna close this and track it there ^_^ Thanks!
