### ISSUE TITLE
context menu shouldn't show up if there's no changes to stage and same for unstaging

### ISSUE THREAD

**Issue by ungb** [atom/github#648]
Staging all your files if you right click on the empty panel you get options to discard or stage. 

![image](https://cloud.githubusercontent.com/assets/5624870/24777380/fca620c8-1ad9-11e7-946f-640ca92809e6.png)
NOTE: click on `stage` seems to unstage the file in stage view.  

![image](https://cloud.githubusercontent.com/assets/5624870/24777422/2cba7372-1ada-11e7-8287-b3a328b5a4e8.png)

NOTE: click on `unstage` stages the selected file.  
  ### Versions

Atom Version (`atom --version`):

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):

**Comment by kuychaco** [comment]
Closing as a dup of #751
