### ISSUE TITLE
Selected hunk line is not visible after clicking Stage/Unstage button

### ISSUE THREAD

**Issue by ungb** [atom/github#649]
1. Make edits to a given file.  
2. Open the staged changes view
3. select a few things and click stage selection

Note: notice after this the stage selection is still there, when it should change to stage hunk?
If you click on it it will stage the last spot  you had selected, but doesn't show selected on ui.  

**Edit:** after looking closely at this it seems the current behavior is as expected, but our current styling does not show the next selected line since the `FilePatchView` loses its `:focus` when the button is clicked

![image](https://cloud.githubusercontent.com/assets/5624870/24777916/a714d444-1adc-11e7-94e2-44e976569baa.png)

### Versions

Atom Version (`atom --version`):

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):

**Comment by BinaryMuse** [comment]
This is interesting. Clicking the button again still works — it stages what would be the next selection — but the selection isn't highlighted visually.

**Comment by simurai** [comment]
The [styles](https://github.com/atom/github/blob/44fe488b39fe6b19ec86859f05331bcde72fa0bf/styles/hunk-view.less#L118) that make a line look selected only get shown when the `FilePatchView` has `:focus`.

So I guess clicking the "Stage Selection" button moves the focus somewhere outside of `FilePatchView`. ⬅️  ➡️  arrows also stop working. You can click anywhere inside to bring the focus back:

![selection](https://cloud.githubusercontent.com/assets/378023/26115647/8b30454a-3a9b-11e7-847f-98f3519706d1.gif)

**Comment by BinaryMuse** [comment]
@simurai Should we have styles for selected + focus and selected + no focus, similar to native UI?

<img width="770" alt="atom_and_atom_and_facebook" src="https://cloud.githubusercontent.com/assets/189606/26411130/655d3b88-40a5-11e7-9b09-a017eb1f32b4.png">

**Comment by kuychaco** [comment]
Okay, so the fix for this is to set up styling so that we visually see the selected item after clicking the "Unstage Selection" button. The behavior is as expected, but the styling isn't making it clear that another line is selected. I'm going to change the title of this issue to reflect this.

**Comment by simurai** [comment]
I see. Yeah, let's do that. Then it's the same as the lists. PR -> #871
