### ISSUE TITLE
GitHub Package broke my package updating

### ISSUE THREAD

**Issue by jbjonesjr** [atom/github#665]
### Versions

Atom Version (`atom --version`):
1.15, 1.16

Was similar to the issues described here: https://github.com/jesseweed/seti-syntax/issues/145 , but turned out to be the cause of the GitHub package, not the seti thing. ¯\_(ツ)_/¯

**Comment by BinaryMuse** [comment]
This should be resolved now that this is a bundled package. Feel free to reopen if I'm wrong.
