### ISSUE TITLE
Clicking the file patch view doesn't select a line/hunk unless the view is already focused

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/github#718]
### Steps to Reproduce

1. Click a file in the commit panel (focuses the commit panel)
2. Click a line in the newly-opened file patch view

**Expected behavior:**

The file patch view is focused and the clicked line is selected.

**Actual behavior:**

The file patch view is focused, but nothing is selected.

**Comment by smashwilson** [comment]
This one was fixed as part of #777. :stars:
