### ISSUE TITLE
Choosing "Stage" or "Unstage" from context menu can do the wrong thing

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#751]
To reproduce:

1. Select a file in the "Unstaged Changes" list
2. Right-click the empty space in the "Staged Changes" list
3. Select "Unstage"

Expected:

Nothing happens as nothing in the Staged Changes list was selected

Observed:

The selected file from the Unstaged Changes list is staged.

![github-package-weird-list-menus](https://cloud.githubusercontent.com/assets/189606/25781730/84feaf6e-333d-11e7-89c7-61b5c5c9ea4f.gif)

This happens because we dispatch `core:confirm` for both the "Stage" and "Unstage" context menu items.

**Comment by kuychaco** [comment]
Think it makes sense to make it such that the staging/unstaging context menu item only gets displayed when right clicking on an item
