### ISSUE TITLE
Force Push state changes rapidly when holding down ctrl

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#766]
The GIF does a horrible job of displaying the issue due to the 8fps default that I forgot to change.  But basically, to reproduce, just open the push/pull panel and hold down cmd/ctrl.
![force-push-flicker](https://cloud.githubusercontent.com/assets/2766036/25870699/0bc9ca9c-34d3-11e7-8935-a27c2e3b42ac.gif)

Fairly certain I'm on 4f41080a3ee42ce523402231ca67fc1923b39112 (I've pulled since then, but haven't restarted Atom).

**Comment by BinaryMuse** [comment]
@50Wliu Remind me what OS you're on again?

**Comment by 50Wliu** [comment]
Sorry, Windows 10 x64.
