### ISSUE TITLE
Changes preview doesn't update

### ISSUE THREAD

**Issue by Arcanemagus** [atom/github#768]
### Description

If the preview is open for a file and then further changes are made to the file, the preview doesn't update to account for the changes.

### Steps to Reproduce

1. Have a file with unstaged changes.
2. Single click the file to open the preview.
3. Switch tabs to the file and make further changes and save them.
4. Switch back to the preview and notice that the changes haven't been reflected.

**Expected behavior:**

The changes for the file should be reflected when it is saved.

**Actual behavior:**

The preview doesn't update. Even closing and opening the preview again doesn't update the changes. If you stage the file then the changes are updated.

**Reproduces how often:**

100% of the time.

### Versions

Windows 10 x64

Build from https://github.com/atom/atom/pull/14372.

Atom    : 1.18.0-dev-4cbff3044 x64
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

github@0.0.2 (bundled in the build)

### Additional Information

I had GitKraken open at the same time on the repo, and it's preview of changes updated whenever the file was saved as expected.

**Comment by BinaryMuse** [comment]
Curious: does it work if you close GitKraken?

**Comment by Arcanemagus** [comment]
> does it work if you close GitKraken?

Nope, still doesn't update. Also I forgot to test this before filing the issue, but safe mode shows the same behavior.

**Comment by smashwilson** [comment]
This sure smells like a caching issue to me... @BinaryMuse was just musing about the need for better diagnostic tools around the caching mechanism :grin:

Okay, my first guess is that there's a mismatch between the cache key that's used to store unstaged file patches and the one that's invalidated when the filesystem event arrives. I'll see if I can duplicate on my Windows box.

**Comment by smashwilson** [comment]
Ah ha, yup: I can reproduce, but _not_ from a file in the root directory. I'm guessing `/` vs. `\` issues in the cache keys.
