### ISSUE TITLE
Staged changes view doesn't disappear when changes committed externally

### ISSUE THREAD

**Issue by Arcanemagus** [atom/github#770]
### Description

If you have changes staged for commit and preview those changes in Atom, if the commit is done with an external program the preview doesn't close automatically.

### Steps to Reproduce

1. Stage changes to a file (doesn't matter where they are staged from, Atom or external)
2. Preview the staged changes in Atom
3. Commit the staged changes in an external program.

**Expected behavior:**

Staged changes preview window to automatically close when the commit is detected.

**Actual behavior:**

Staged changes preview window stays open, even though the changes it is showing have already been committed.

**Reproduces how often:**

100% of the time.

### Versions

Windows 10 x64

Atom    : 1.18.0-dev-4cbff3044 x64
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

github@0.0.2 (bundled in the build)

### Additional Information

External changes tested by committing from the CLI, as well as from GitKraken. Atom detects that the commit has been made as the changes no longer show in the staged changes, it just keeps the preview open.

Committing the changes in Atom itself _does_ close the preview window as expected.

**Comment by BinaryMuse** [comment]
Very likely the same caching issue as https://github.com/atom/github/issues/768

**Comment by smashwilson** [comment]
Reproduced and confirmed fixed as part of #776 :+1:

**Comment by Arcanemagus** [comment]
Apparently GitHub didn't like the "and #770" part of #776. Marking this as closed since it should be fixed in `master` now.

**Comment by mixelpixel** [comment]
Hi, I have this problem with version 1.20.1 - is there a fix, or something to hope for in subsequent version?
