### ISSUE TITLE
Clicking Conversation gives an unknown error

### ISSUE THREAD

**Issue by Arcanemagus** [atom/github#771]
### Description

When you click the Conversation button on the GitHub tab a tab opens up with an error message instead of the expected conversation.

### Steps to Reproduce

1. Have a PR for a branch.
2. Somehow get `github` to recognize this (took a restart of Atom to refresh data)
3. Click <kbd>Conversation</kbd>

**Expected behavior:**

The "Conversation" to load, whatever that is. In this case the PR had no comments, so I guess I would expect only the description to show.

**Actual behavior:**

![image](https://cloud.githubusercontent.com/assets/427137/25876725/fe53f1fc-34d3-11e7-898a-463f210e8e9c.png)

![image](https://cloud.githubusercontent.com/assets/427137/25876653/8d28dbb4-34d3-11e7-8e19-28b7cef7c4e4.png)
```
Server request for query `Issueish` failed for the following reasons:

1. Field 'id' doesn't exist on type 'Actor'
   or {avatarUrl,login,id},commit {oid,id},mergeRef {name,id},c
                       ^^^
```

**Reproduces how often:**

100% of the time.
Reproduces in safe mode.

### Versions

Windows 10 x64

Atom    : 1.18.0-dev-4cbff3044 x64
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

github@0.0.2 (bundled in the build)

### Additional Information

The PR/Branch in question is https://github.com/AtomLinter/linter-phpcs/pull/261.

**Comment by BinaryMuse** [comment]
Fixed by https://github.com/atom/github/pull/763
