### ISSUE TITLE
How can i use it?

### ISSUE THREAD

**Issue by antonkluev** [atom/github#773]
Hi!
I'm searching for an Access to those Git-Merge or Git-Commit Panels. Any shortcut? Command-Palette? Plugin?
Thanks.

**Comment by 50Wliu** [comment]
This package will be bundled with Atom starting in Atom 1.18.0.

**Comment by BinaryMuse** [comment]
Hey @antonkluev,

Yeah, this package will be built-in to Atom starting in version 1.18. When the 1.18 beta comes out, give it a shot and let us know what you think!
