### ISSUE TITLE
Show committer avatar as well as author in commit list

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#774]
We currently only show the author of the commits in the PR commit view.

<img width="184" alt="cursor_and_pr__atom_atom_13453_ use_new_text-buffer_version_with_a_more_efficient_displaylayer_ ___atom" src="https://cloud.githubusercontent.com/assets/189606/25895764/97963e26-3581-11e7-9250-e6ddc2ba0f2c.png">

It would be great to show the committer too, similar to how GitHub.com does it:

<img width="231" alt="cursor_and_use_new_text-buffer_version_with_a_more_efficient_displaylayer_by_maxbrunsfeld_ _pull_request__13453_ _atom_atom" src="https://cloud.githubusercontent.com/assets/189606/25895776/a5eb61cc-3581-11e7-9007-ae6c4530ea5f.png">

**Comment by ahmed-taj** [comment]
@BinaryMuse I think I will give it a try
