### ISSUE TITLE
Unable to close GitHub dock

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#784]
Steps to reproduce:
1. Open Github dock (I opened it by pressing the "0 files" text in the status bar)
2. Focus commit message
3. Attempt to close the dock (again by clicking the "0 files" text)

Expected: Dock closes
Actual: Dock closes and immediately reappears

ba757d5c567886a43e3e9c1551754f8908428b98, Atom 1.18.0-dev-6d7b5110b, Windows 10 x64

/cc @smashwilson

**Comment by smashwilson** [comment]
![SHAME](https://media.giphy.com/media/DF5Js3IOdd9xS/giphy.gif)

**Comment by smashwilson** [comment]
@50Wliu Thanks for the catch 😅
