### ISSUE TITLE
Keyboard toggle for the git/github panel does not function as expected

### ISSUE THREAD

**Issue by joshlove** [atom/github#810]
### Description

When I try to toggle the github/git view off via the keyboard commands `^(` and `^*` it simply switches the active panel. If you use the menu and click the toggle with you mouse, it actively hides the panel. Using the keyboard shortcuts brings it back but does not work in hiding it.

### Steps to Reproduce

1. Make sure git panel is visible (I have a directory open with some code)
2. try to use either keyboard shortcut of `^*` or `^(`
3. Use the view menu to toggle the view (which works as expected)

**Expected behavior:**

The panel to be hidden.

**Actual behavior:**

Nothing.

**Reproduces how often:**

100%

### Versions

```➜  devops-dotfiles git:(master) ✗ atom-beta --version
Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
➜  devops-dotfiles git:(master) ✗ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.12.2```

OSX 10.12.3, 2017 MBP.

**Comment by rsese** [comment]
Just to confirm, are you typing <kbd>ctrl-shift-8</kbd> for <kbd>^*</kbd> and <kbd>ctrl-shift-9</kbd> for <kbd>^(</kbd>?  Just <kbd>ctrl-8</kbd> and <kbd>ctrl-9</kbd> toggleas the focus for each tab. 

With the Git tab visible, <kbd>ctrl-shift-9</kbd> work ok for me to toggle the tab.

I did notice however that if both the Git and GitHub tabs are visible, toggling one or the other toggles both so they're both not visible.  Not sure if that's the correct behavior or not though 🤔

**Comment by joshlove** [comment]
Ok, that's weird, I was doing that earlier but it wasn't working. (Or maybe my keyboard at my desk was being funky - it's working on the native keyboard in my laptop).

I'll say close this one down, thanks for the tip!
