### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by ktornwall** [atom/github#822]
1. View a git diff for a file with at least two changes
2. Left click on one change
3. Right click on another change
4. Click away from the menu
--> Crash

![kapture 2017-05-16 at 19 10 37](https://cloud.githubusercontent.com/assets/1699388/26132018/68b815b8-3a6b-11e7-8ddf-6967485ff0e4.gif)

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [github](https://github.com/atom/github) package 0.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'parentNode' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/github/lib/views/file-patch-view.js:206

TypeError: Cannot read property 'parentNode' of null
    at requestAnimationFrame (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/github/lib/views/file-patch-view.js:206:1)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-elixir 1.5.14 
busy-signal 1.4.1 
editorconfig 2.2.2 
intentions 1.1.2 
language-elixir 0.17.0 
linter 2.1.4 
linter-eslint 8.1.6 
linter-flow 5.6.0 
linter-rubocop 2.1.1 
linter-ui-default 1.2.3 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by smashwilson** [comment]
Good catch 🙇  This is fixed in #853, along with some other weirdness with the `contextmenu` event handling, and will be included in the next hotpatch release.
