### ISSUE TITLE
Branch selector omits local branches with slashes (/) in their name

### ISSUE THREAD

**Issue by sentience** [atom/github#826]
### Description

Local branches with a slash in their name do not appear in the branch selector.

### Steps to Reproduce

1. Start with a project open on the ‘master’ branch.
2. Click the ‘master’ branch name in the status bar.
3. Click ‘new branch’ in the branch tooltip control.
4. Type `test/me` for the new branch name, and hit Enter.
5. Note: you are now on the ‘test/me’ branch, and its name is properly displayed in the status bar.
6. Click the ‘test/me’ branch name in the status bar.
7. Using the branch select list, switch to the ‘master’ branch.
8. Click the ‘master’ branch name in the status bar.
9. **Bug: the ‘test/me’ branch does not appear in the branch select list.**

**Expected behavior:**

The ‘test/me’ branch should still be available to select after switching to another branch.

**Actual behavior:**

The ‘test/me’ branch is not listed in the branch select list.

**Reproduces how often:**

Always.

### Versions

Atom: 1.18.0-beta0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0
macOS: 10.12.5 beta

**Comment by kuychaco** [comment]
Thanks for the report! @colepatrickturner fixed this in #820 ✨
