### ISSUE TITLE
Feature Request: Edit History

### ISSUE THREAD

**Issue by alrz** [atom/github#835]
- Edit commit message (with a warning if the commit is already pushed)
- Reorder commits by drag and drop (with a warning if any of commits are already pushed)
- Select and squash subsequent commits (with a warning if any of commits are already pushed)

**Comment by BinaryMuse** [comment]
Thank you for the suggestions! We would eventually like to support a wide range of rebase-style features — we'll track that in https://github.com/atom/github/issues/762 for now and other issues/PRs if and when we get to these.

**Comment by alrz** [comment]
Thanks for the pointer to #762. I think this would make more sense for github desktop at this stage.
