### ISSUE TITLE
Integration for GitHub Enterprise?

### ISSUE THREAD

**Issue by sebastianroming** [atom/github#843]
Currently (with `1.18.0-beta0`) I get the following notification in the _GitHub (preview)_ Tab: 

`This repository does not have any remotes hosted at GitHub.com`

Indeed, that is correct, but it has one at a GitHub Enterprise installation. Will this get implemented in the near future?

**Comment by BinaryMuse** [comment]
We'd love to support this, but GitHub Enterprise does not yet implement the GraphQL API with the endpoints that we need to support the integration there. Tracking this at #270, so I'll close this here. Thanks for the question!

**Comment by uchuugaka** [comment]
Any idea when Github Enterprise might be ready?
Or if there's not another way beyond GraphQL?

**Comment by zbikmarc** [comment]
It looks like it is ready now, at realist regarding to what @chickenkiller wrote in #270 

> For information, GitHub Enterprise 2.10.0 has just been released, with [support for GraphQL API](https://enterprise.github.com/releases/2.10.0/notes).
> Usage of GraphQL API through GitHub Enterprise is documented [here](https://developer.github.com/enterprise/2.10/v4/guides/intro-to-graphql/).

**Comment by BinaryMuse** [comment]
I updated #270 to give some more information — locking this thread, but feel free to comment more there if you have questions or thoughts.
