### ISSUE TITLE
Work with lot of files

### ISSUE THREAD

**Issue by fabianfiorotto** [atom/github#845]
I have 421 files in "Unstage changes", It would be nice to have a way to filter them or to stage/diff the file that is currently opened in the editor.

**Comment by kuychaco** [comment]
These are all great suggestions! Here are individual issues associated with each of your requests: 

* #46 - Highlight changed lines in the editor and stage them
* #889 - View staged/unstaged changes for current file (implemented in PR #879)
* #888 - Filter changed file lists
