### ISSUE TITLE
ux: Using keyboard to stage a file should show the next file's diff

### ISSUE THREAD

**Issue by benogle** [atom/github#854]
* Have multiple files with changes
* Select a file in the unstaged changes area, note that it shows the diff
* Hit enter to stage it
* Note that the file is staged, and another file in the unstaged changes list is selected, but the newly selected file's diff is not shown. If I hit the up/down key or click on the file, the diff is shown.

**Comment by simurai** [comment]
❤️  Welcome back to the team.

**Comment by BinaryMuse** [comment]
This has come up a couple times in various contexts — https://github.com/atom/github/issues/606,  https://github.com/atom/github/issues/645 — and the latest conversation ended in a decision to keep the diff view open, but empty, with an easy way to get to the next file. Thoughts?

**Comment by benogle** [comment]
> ❤️ Welcome back to the team.

❤️  lol, my feels were flaring up when using the git stuff. It's _so nice_ to not need to leave the editor.

Keeping the diff open sounds good. Seems like keeping it open whenever the diff view or git tab are focused would be legit. I guess when to hide it is kind of hard. My gut is that I want to see the diff view the whole time I deal with git stuff, then when I ctrl-shift-9 hide, I want to see no more git stuff.

Anyway feel free to close this as a dupe if you wanna. And nice job on the package all y'all.

**Comment by kuychaco** [comment]
👋 @benogle, thanks for the feedback! Captured it in #864.
