### ISSUE TITLE
Don't display the Git or GitHub panels when editing a recognizable Git message

### ISSUE THREAD

**Issue by lee-dohm** [atom/github#882]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

![screen shot 2017-05-27 at 10 52 20 am](https://cloud.githubusercontent.com/assets/1038121/26523343/9b1ab3aa-42ca-11e7-924d-9a908f81f66a.png)

For now (and possibly in perpetuity), it is still occasionally necessary to use the command-line for certain commands. (Specifically, I ran into this when using `git revert`.) Having the Git tab open when editing `COMMIT_EDITMSG` caused me a moment's confusion because I wasn't sure if clicking the "Commit" button would do what I wanted it to.

### Steps to Reproduce

1. Configure Atom to be your git editor: `git config --global core.editor=atom --wait`
1. Execute a git command from the command-line that prompts for a commit message, ex: `git revert HEAD`

**Expected behavior:** Atom to open without the Git or GitHub panels showing

**Actual behavior:** Git and GitHub panels were showing

### Versions

```
Atom    : 1.19.0-dev-0b0a72af8
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

N/A

**Comment by smashwilson** [comment]
I believe #872 takes care of this without needing a special case, unless the very first time you open Atom with the github package installed is to edit a git commit message :smile:

**Comment by lee-dohm** [comment]
Yep, it should :+1: Thanks @smashwilson :grinning:
