### ISSUE TITLE
(Un)staged changes tab resets scroll position when changing focus

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#884]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When you scroll through (un)staged changes and then unfocus the tab, the scroll position is reset to the beginning.

### Steps to Reproduce

1. Create enough changes that there will be a scrollbar
2. Open the unstaged changes
3. Scroll through the changes
4. Change focus, i.e. switch to the commit box, change tabs, focus tree view, ...

**Expected behavior:** Scroll position to stay the same

**Actual behavior:** Scroll position resets to the top of the file

**Reproduces how often:** 100%

### Versions

Atom 1.19.0-dev-9e64abef3, Windows 10 x64, safe mode.

### Additional Information

![scoll-position-reset](https://cloud.githubusercontent.com/assets/2766036/26532483/ce59f59a-43cf-11e7-9fd9-538c92193150.gif)

**Comment by bbugh** [comment]
This happens to me even when I'm just scrolling. I'll scroll halfway down and it will jump back to the top. Even if I scroll while keeping the mouse button held, every second or so it will jump back up to the top and then back down to where my cursor is. It is really aggravating. 😅

**Comment by hexsprite** [comment]
same behavior as @bbugh, Confirmed in 1.19.2

**Comment by johnckendall** [comment]
If you click on a highlighted row then it will just keep jumping back to that row.  The bug seems to be that it want's to keep the currently highlighted row in view and scrolling doesn't change the highlighted row.

**Comment by smashwilson** [comment]
The fix was merged in 0.10, which is in Atom beta now and will make it to Atom stable in the next release.
