### ISSUE TITLE
Save credentials login

### ISSUE THREAD

**Issue by PixelT** [atom/github#893]
It's possible to save credential login/password to repository?
Currently I must write login/password for each action like fetch / pull / push....

**Comment by smashwilson** [comment]
![is such a thing even possible](http://i0.kym-cdn.com/photos/images/original/000/155/594/yesitis2.gif)

For the moment, you may be able to configure a [credential helper](https://help.github.com/articles/caching-your-github-password-in-git/) for git, which will store successfully used credentials in your OS keychain. We're tracking this at #861, so subscribe there for discussion and updates :smile:
