### ISSUE TITLE
Respect prepared commit messages

### ISSUE THREAD

**Issue by smashwilson** [atom/github#894]
[Commit templates](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#__code_commit_template_code) and [prepare-commit-msg hooks](https://git-scm.com/docs/githooks#_prepare_commit_msg) provide ways to customize the default commit message. These are especially useful for adhering to organization standards for commit message formatting (like ensuring that every commit references an issue, for example). We should respect these when populating the commit message dialog or editor.

**Comment by smashwilson** [comment]
An open question: the message templates aren't that useful in the CommitView editor, because (a) it doesn't have a lot of screen real estate so you can't see the template and (b) the information generated by the default templates is redundant to the rest of the UI anyway. We may want to only show the template when the message is being edited in a full editor as per #818, and trim comments for the CommitView editor.

The tricky bits here are:

* How do we preserve context as you toggle a message back and forth between the editor and CommitView? Especially if you edit lines among comment lines.
* Will changing the commit message be disconcerting to users?
* How do we know when to generate the templated message?

/cc @kuychaco

**Comment by chrleon** [comment]
So, if I understand this correct: There is no way to get the prepared commit message to show up in Commit View?

**Comment by annthurium** [comment]
good news!  Now we support commit message templates.  Going to close this out, but please feel free to reopen if you have questions or concerns. 😄

**Comment by dflock** [comment]
> good news! Now we support commit message templates. Going to close this out, but please feel free to reopen if you have questions or concerns

It appears that Atom supports commit templates - i.e. _static_ commit boilerplate, but **NOT** prepare-commit-msg hooks - i.e. _dynamic_ commit boilerplate. :cry:
