### ISSUE TITLE
bash_profile not executed when committing

### ISSUE THREAD

**Issue by cbovis** [atom/github#898]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? yes
* Have you checked the FAQs on the [message board][message-board] for common solutions? yes
* Have you checked that your issue [isn't already filed][already-filed]? yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When attempting to commit I'm receiving an error from our pre-commit linter due to an environment variable not being set, this environment variable is set via my bash_profile. Committing via terminal or my other GUI (Tower) works fine so it appears to be an issue isolated to github for atom.

### Steps to Reproduce

1. Set an environment variable within your bash_profile
2. Depend upon this variable within a pre-commit script and fail if it's not set
3. Attempt to commit a change via github for atom

**Expected behavior:**

Pre-commit step executes as expected using the environment variable from bash_profile.

**Actual behavior:**

An error is displayed stating that the environment variable is missing.

**Reproduces how often:**

100%

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.12.2

macOS Sierra 10.12.5

**Comment by piuccio** [comment]
I opened the same issue on atom/atom#14798

### Description

I've just updated Atom and tried to commit from the new GitHub/Git package but I get the error

```
Error: Failed to replace env in config: ${BINTRAY_TOKEN}
    at /usr/local/lib/node_modules/npm/lib/config/core.js:418:13
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:414:12)
    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:392:7)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (native)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf. (/usr/local/lib/node_modules/npm/lib/config/core.js:322:10)

/usr/local/lib/node_modules/npm/lib/npm.js:45
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:45:13)
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:74:40)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:194:3)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (bootstrap_node.js:304:26)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint:staged`
pre-commit: hook returned an exit code (7). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

I have the following `.npmrc` in my project

```
@private-stuff:registry=https://api.bintray.com/npm/private-repository/
//api.bintray.com/npm/private-repository/:_authToken=${BINTRAY_TOKEN}
//api.bintray.com/npm/private-repository/:username=${BINTRAY_USER}
//api.bintray.com/npm/private-repository/:email=${BINTRAY_EMAIL}
//api.bintray.com/npm/private-repository/:always-auth=true
```

The environment variables are defined in my `~/.bash_profile`

```
export BINTRAY_TOKEN=abc
# ...
```

It works fine from both the command line `git commit -m` and the `git gui`

I also have a pre-commit hook installed through [pre-commit](https://www.npmjs.com/package/pre-commit) and using [lint-staged](https://www.npmjs.com/package/lint-staged) to run eslint, but I'm not sure that's the problem


### Steps to Reproduce

1. Create an `.npmrc` file with a configuration variable
2. export the variable
3. try to commit

**Expected behavior:** You can create a commit

**Actual behavior:** Get the error

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.0

Using masOS Sierra 10.12.4

**Comment by RobertWHurst** [comment]
I'm also experiencing this issue.

**Comment by BinaryMuse** [comment]
I'm thinking we can just clone all of `process.env` as we pass it to the sidecar shellout process to fix this, as long as the env vars exist in Atom's `process.env` object. 💭 s @kuychaco @smashwilson?

**Comment by BinaryMuse** [comment]
#1075 fixes this as long as the environment variables make their way into the Atom process itself — there's code in Atom to ensure this happens, but I guess it's still feasible that there's an edge case here. The change will be in the upcoming beta so feel free to try it out and let us know what you think.
