### ISSUE TITLE
Possibility to make a Pull with rebase

### ISSUE THREAD

**Issue by dandeveloper** [atom/github#913]
Is there any way to make a Pull with the rebase option?
And if it's not possible, why not to implement this in the package configuration.

**Comment by smashwilson** [comment]
We respect the [git config options](https://stackoverflow.com/questions/13846300/how-to-make-git-pull-use-rebase-by-default-for-all-my-repositories) which you can set with a lot of granularity (from "only for this branch" to "always rebase all the time on this machine"). This lets us ensure consistency with the way that pulls work from the command-line.

We _don't_ currently have a way to do a one-off `git pull --rebase` equivalent, though.

See #493 for some prior discussion about this.
