### ISSUE TITLE
stage entire folder

### ISSUE THREAD

**Issue by UziTech** [atom/github#927]
There is no way to easily stage an entire folder without selecting all of the files from that folder

**Comment by UziTech** [comment]
It would be nice to see an option for tree view style file lists

**Comment by 50Wliu** [comment]
> It would be nice to see an option for tree view style file lists

Ooh, I didn't know that I needed this until you brought it up.

**Comment by varemenos** [comment]
I was looking all over the github package issues for a "tree view style staging" feature mention.
It would be great if it had it's own issue to track.

**Comment by UziTech** [comment]
I added a "Stage Changes" command to [context-git](https://atom.io/packages/context-git) so you can stage an entire folder from the tree-view

![stage_changes](https://user-images.githubusercontent.com/97994/39446896-99239e84-4c85-11e8-9a38-e61e03493c1c.gif)

You can also use it from the command palette:

![stage_changes_cp](https://user-images.githubusercontent.com/97994/39447066-3088ba5c-4c86-11e8-83f7-1320f135b563.gif)
