### ISSUE TITLE
Add a loader during pre-commit hook process

### ISSUE THREAD

**Issue by danillewin** [atom/github#929]
Hello

Could you add some loader for pre-commit hooks? When I commit my changes I have a hook that takes a time to be done, and there's no way in current interface to understand that something is happening now. Of course, after the hook is done the commit text and staged files are gone, and it's clear that I can commit, but in my opinion loader will be very clear and user-friendly feature)

P.S. This feature is awesome, thank you

**Comment by BinaryMuse** [comment]
I love the idea of an indeterminate progress indicator between when a commit starts and finishes. Thanks for the suggestion!

**Comment by gillesdemey** [comment]
Integration with [busy-signal](https://atom.io/packages/busy-signal) would be awesome 🙌

**Comment by agisilaos** [comment]
I was thinking of starting working on this issue. @BinaryMuse What are you thinking is a good approach for this issue? The integration with busy-signal seems logical to you? ✨

**Comment by BinaryMuse** [comment]
@agisilaos Integration with busy-signal might be nice-to-have if it's not too difficult, but I think a higher priority change would be to show something in the Git UI (since that's the part of the UI that you can't interact with while a commit is running).

**Comment by agisilaos** [comment]
@BinaryMuse Makes total sense. I want to think about it and see if I can come up with a native solution for this issue. Will update this issue regularly.
