### ISSUE TITLE
Using offline need to improve UI

### ISSUE THREAD

**Issue by torn4dom4n** [atom/github#931]
### Description

Notice: `An unknown error occurred` and `Try Again` button. It isn't Atom's style.

![image](https://user-images.githubusercontent.com/27698189/27204508-cc0e166a-5255-11e7-88ee-249179d80559.png)

Windows 10 Creator Update
Atom 1.19.0-beta0

**Comment by antwal** [comment]
same problem on OSX with https and git url repository
