### ISSUE TITLE
How to use git rebase instead of pull in Atom 1.18?

### ISSUE THREAD

**Issue by vitorlee** [atom/github#933]
Any idea that set git pull to git rebase?

**Comment by ungb** [comment]
Thanks for the suggestion.  Currently there isn't a way to rebase using the github package. 
 We plan to support this scenario eventually.  Will close this issue in favor of  https://github.com/atom/github/issues/762.  When the team starts working on rebase they will see this as part of that other issue during implementation.

**Comment by vitorlee** [comment]
tks

**Comment by pastephens** [comment]
Any update on this? Ideally, Atom would read the repository's git config and behave as defined there.
