### ISSUE TITLE
Slow regaining focus

### ISSUE THREAD

**Issue by steronydh** [atom/github#936]
I am still seeing the same effect as [Atom #9544](https://github.com/atom/atom/issues/9544) with the new Github integration. I get a 4-5 second freeze on Windows 10 when Atom regains focus with three Git project folders in the Project pane. This even happens in Safe mode.

**Comment by 50Wliu** [comment]
The github package did not address atom/atom#9544, so I'm going to close this issue in favor of keeping the discussion centralized at atom/atom#9544.
