### ISSUE TITLE
If the remote url contain the username and I push change them I get this error message: Empty password

### ISSUE THREAD

**Issue by dragonzap** [atom/github#941]
### Description

I can't push my commits from Atom **if remote url contain the username**, but git bash work correctly with **git push** command.
When I push them Atom ask password and I fill it but Atom say: (Unable to push, remote: Empty password...)

### Steps to Reproduce

1. Change files
2. Stage files
3. Commit (with message)
4. Click Push Button (It show that, I have one commit.)
5. Fill password field
6. I got a message: Unable to push (remote: Empty password, fatal: Authentication failed for '...@bitbucket.org/...')

**Expected behavior:**

Ask user password (or not).
Push commit(s).

**Actual behavior:**

Ask user password.
Error message.

**Reproduces how often:**

If the remote url contain username.

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: Windows 10 
git: 2.10.2.windows.1

### Additional Information

I use bitbucket repo but I think It should be work with this.
It work corretly if I remove username from remote url, but I would be happier If it work in both version.

**Comment by jonnitto** [comment]
The same here, but on macOS 10.12.15

**Comment by loxiw** [comment]
Same with Bitbucket.
Just in case that helps, I'm also having problems with my repo in Gitkraken (this app just crashes whenever I try to open a repo with the remote pointing to bitbucket).

**Comment by rsese** [comment]
For folks using Bitbucket, does your remote URL have your username embedded i.e. `https://username@bitbucket.org/USER/REPO`?   If so, can you update your remote to remove the username and try again?

git remote set-url origin https://bitbucket.org/USER/REPO

**Comment by leshido** [comment]
Using Bitbucket, changing the remote url to NOT include the username as suggested by @rsese does seem to solve the issue. Atom prompts to enter both username and password, and is then able to push with no error.

**Comment by podhikaru** [comment]
@rsese thanks no more error but pain to enter user/pass every time, there is anyway to remember this ?

**Comment by dragonzap** [comment]
@rsese , @leshido : Thanks, It work.

**Comment by BinaryMuse** [comment]
Alright, this does seem to be a bug where we're not properly respecting the credentials stored in the remote URL. Thanks for the reports.

**Comment by jano23** [comment]
#rsese Thanks - that worked.

I agree with others that eventually it would be nice if one could store the credentials locally so they don't have to be entered EACH AND EVERYTIME one does a Pull or a Push

**Comment by smashwilson** [comment]
@jano23: That's [on our radar](https://github.com/atom/github/issues/861)! In the meantime, if you have [a git credential helper appropriate to your OS installed](https://help.github.com/articles/caching-your-github-password-in-git/), it can be used to store password in your OS keychain or cache them for a certain amount of time.
