### ISSUE TITLE
Delete Branch Button

### ISSUE THREAD

**Issue by UziTech** [atom/github#944]
It would be nice to have a delete branch button

![image](https://user-images.githubusercontent.com/97994/27238881-42a2a762-5294-11e7-988d-437e2c0aba27.png)

**Comment by rsese** [comment]
It looks like this enhancement is covered in this high level branch management issue?

https://github.com/atom/github/issues/556

I'll close as a dupe for now but let me know if I mis-understood anything.

**Comment by amanibouguila240** [comment]
how can i get it !

**Comment by UziTech** [comment]
@amanibouguila240 the github extension does not have it but I created another extension [git-menu](https://atom.io/packages/git-menu) that adds a way to delete branches (along with other git operations) to the context menu.
