### ISSUE TITLE
How do I change the remote to see PRs associated

### ISSUE THREAD

**Issue by HidekiHokuto** [atom/github#946]
Once I selected a remote, How do I change it to another one?

**Comment by EroMonsterSanji** [comment]
![screen shot 2017-06-17 at 03 27 19](https://user-images.githubusercontent.com/13698108/27242263-ec732f6c-530e-11e7-89ea-521fc09b52dc.png)

**Comment by mloschia** [comment]
Selected origin remote instead of upstream so I landed here too. I tried enabling and disabling the package but that didn't work.

**Comment by smashwilson** [comment]
There's some missing UI here to get back to the remote selection state (/cc @simurai for thoughts).

In the meantime, the current remote is stored in your repository's git configuration, so you can edit that directly:

```
git config --unset atomGithub.currentRemote
```

**Comment by simurai** [comment]
For now could be similar to a pinned PR:

![image](https://user-images.githubusercontent.com/378023/27367024-07b3be30-5685-11e7-91c1-7d3cf722b9a7.png)

But **if**, then only short term. Some sort of GitHub browser/filter, like https://github.com/atom/github/pull/714#issuecomment-298145826 is still the better approach.
