### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by fdioni** [atom/github#947]
i have putty key which already added to my ssh key list on github. but when i use git on atom using this package, show error:

```
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
atom  version
`Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0`

**Comment by 50Wliu** [comment]
Please uninstall the github package - it is not meant to be installed manually.  After uninstalling, update to Atom 1.18.0, which includes the github package.  If you can still reproduce the issue, then please file a new issue and completely fill out the provided issue template.  Thanks!

**Comment by fdioni** [comment]
how to uninstall? it's automatically added after i update my atom. my problem not yet solved and you just close it?
