### ISSUE TITLE
Atom crashing because of git...

### ISSUE THREAD

**Issue by SakoMe** [atom/github#948]
Atom keeps freezing and crashes after about a minute. 

Ran apm disable github and it seems to be fine now...

OS Siera 10.12.5

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by serafeimgr** [comment]
Have you set up atom to load a specific project on start up?

**Comment by SakoMe** [comment]
Nope... It just started happening out of the blue a few days ago...

**Comment by serafeimgr** [comment]
Did you tried --safe option?

**Comment by SakoMe** [comment]
Yes, to no avail... the only thing that worked is what I have already mentioned arm disable github.

**Comment by 50Wliu** [comment]
I'm closing this as a duplicate of atom/atom#14806 because there's more discussion there.
