### ISSUE TITLE
Standalone version ?

### ISSUE THREAD

**Issue by n457** [atom/github#949]
Hi everybody,

Thanks to the Atom team and contributors for bringing Git and GitHub integration in Atom, it's very simple and well made 👍

This package is so good that I'm very interested to see it also released as a standalone version (as an Electron app, for example). This would be an excellent alternative to existing heavy Git clients (SourceTree, GitKraken, etc.). What do you think ? Any chance to see that happening ?

Keep up the good work ! 😉

**Comment by serafeimgr** [comment]
Are you aware of GitHub's native app?
https://desktop.github.com/

**Comment by BinaryMuse** [comment]
Hey there! 

As mentioned, GitHub already maintains a desktop client, so it's unlikely that we'll extract the GitHub package into a separate app.

**Comment by n457** [comment]
@serafeimgr @BinaryMuse  Oh ! OK I was not aware of the latest major update, pretty cool. But GitHub for Desktop is not open source and not available for Linux, unlike Atom and its git UI package :) That's what I'm looking for

**Comment by 50Wliu** [comment]
@n457 the new one is open source!  https://github.com/desktop/desktop
Maybe you can look into it and help them create a version for Linux.
