### ISSUE TITLE
Github integration crashing editor upon launch 

### ISSUE THREAD

**Issue by MandarSant** [atom/github#955]
please check this issue ->    [#14446](https://github.com/atom/atom/issues/14446)

**Comment by BinaryMuse** [comment]
@MandarSant We have a few open issues already for crashing related bugs. Please add a crash dump to one of the existing issues if you have one. Thank you!

**Comment by MandarSant** [comment]
@BinaryMuse  what is crash dump?

**Comment by rsese** [comment]
You can find them as described here @MandarSant:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

So for Windows the crash files should be in `%TEMP%\Atom Crashes`.

**Comment by MandarSant** [comment]
@BinaryMuse  @rsese 
[operation_log.txt](https://github.com/atom/github/files/1093483/operation_log.txt)

**Comment by ungb** [comment]
@MandarSant can you provide a few more info?  Are you using a git project?  Also, can you provide the following info?

- OS
- Atom version (`atom --version`)
- Have you tried safe mode? `atom --safe`
- List of packages installed `apm list`


Also, if you can provide detailed step by step repro on what you did to encounter this would be very useful.   We're currently trying to get repro for crash issues, once we have that we can pinpoint the issue and hopefully get a fix out asap.

Information about the git repo(assuming you're using one).  

If you can compress and share the crash dumps that would be more useful than the operation_log.txt.

**Comment by MandarSant** [comment]
@ungb 
OS:-Win 8.1 WMC
Atom V:-latest
Yes,tried is safe mot still it hangs my pc and also editor

**Comment by 50Wliu** [comment]
@MandarSant are there `.dmp` files located in `%TEMP%\Atom Crashes`?  If so, it would be very helpful if you could share them by creating a zip file and attaching it here.

Also, what are the steps that you took before experiencing the crash?

**Comment by MandarSant** [comment]
@ungb @50Wliu @BinaryMuse @rsese I creatd New issue [#973] (https://github.com/atom/github/issues/973) so insted communicating here continue there
