### ISSUE TITLE
Atom freezes when GitHub package is enabled (repo located on a virtual machine)

### ISSUE THREAD

**Issue by Powell-v2** [atom/github#956]
Hey guys, I've got an issue which I suppose is related to GitHub core package.

### Description

Atom freezes every now and then for a couple of seconds.

### Steps to Reproduce

I guess the problem I am experiencing is related to my non-trivial dev environment (see _"Additional info"_).
For what it's worth, Atom hangs when I perform basic actions: select, edit and search code, as well as just clicking around the file.

**Expected behavior:**

No lags of course! 🤓 

**Actual behavior:**

Lags, lags, lags ...

**Reproduces how often:**

Often enough to irritate 😀 !
Sometimes interval is quite short - can happen several times during one minute.

### Versions

**Atom**
* Atom    : 1.18.0
* Electron: 1.3.15
* Chrome  : 52.0.2743.82
* Node    : 6.5.0

**My OS**
* macOS Sierra
* 10.12.5 (16F73)

### Additional Information

That's where things get interesting.. I access repo which is located on a virtual machine through a mount:

* I am running Ubuntu 16.04.2 LTS on VirtualBox
* Drive is mounted using samba

It seems to me that the issue is related to GitHub core package. When I disable it, Atom works just fine.

Moreover, for some reason Git marked all the files in the project as unstaged, whereas in Mac terminal it behaves as expected (connected to the machine via ssh).

Lastly, attached is JavaScript CPU Profile:
[CPU-20170620T124300.cpuprofile.zip](https://github.com/atom/github/files/1088093/CPU-20170620T124300.cpuprofile.zip)

**Comment by BinaryMuse** [comment]
Heya, are you still experiencing this on Atom 1.19.2 or above?

**Comment by Powell-v2** [comment]
heyyo, I'll verify tomorrow and let you know.

**Comment by Powell-v2** [comment]
It seems like everything is fine - I haven't experienced any freezes or hiccups while using Atom today with GitHub package enabled (~3 hours). 👍

**Comment by BinaryMuse** [comment]
Great! I'm _fairly_ certain this was fixed in #1028 (via https://github.com/kuychaco/what-the-status/pull/1) so I'm going to close this for now. Let us know if you have other issues!
