### ISSUE TITLE
300000 unstaged changes crush

### ISSUE THREAD

**Issue by StanSkrivanek** [atom/github#958]
After update there is now 358344 unstaged changes 99% starting with .atom/*** . Atom freeze and is not responsive finally after while crush. 
 Switching package on / of cause creation of multiple identical overviews

**Comment by serafeimgr** [comment]
Most probably a .git directory has been created in .atom.
I suggest deleting this.

**Comment by serafeimgr** [comment]
Also you could use `apm disable` command to disable github package.

**Comment by BinaryMuse** [comment]
I've opened #959 to track this bug. Thanks for reporting this here.

In the meantime, removing the `.git` folder from your `.atom` will resolve the issue, or if you want to keep it tracked in git, you can ignore `node_modules` and other temporary folders so that the change file list isn't so large.

**Comment by Yessengerey** [comment]
This happens to me only when I open files with Atom on C: disk. over 125000 .atom unstaged changes appear which causes Atom to lag and eventually freeze and die... I do not seem to have a .git folder in my .atom. So I suppose simply deleting it is not an option for me. Could someone please help? 
P.S. Deleting and re-installing Atom did not help...
![atom issue](https://user-images.githubusercontent.com/9358796/27516584-8bb5866c-59de-11e7-8cbf-035fb586fca8.PNG)

**Comment by elliot2282** [comment]
@serafeimgr you are a lifesaver, thank you so much. Have been searching for days

**Comment by StanSkrivanek** [comment]
Thanks

**Comment by Bonteqq** [comment]
@serafeimgr I'm running into this issue as well, but am unsure what you mean by apm disable or deleting the .git file from .atom... do you mind going into a bit more detail please? Atom is virtually useless for any new projects I am attempting to create right now.

**Comment by devOpElliot** [comment]
open your command prompt and type apm disable
this will stop atom from lagging and freezing up

**Comment by gonzen2310** [comment]
Go to setting -> packages -> type git -> look for a package named Github and disable it. Done!
