### ISSUE TITLE
Large repos result in high CPU usage

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#959]
When there is a very large repo, a considerable amount of time is spent synchronously parsing the output of `git status --porcelain=v2` with the pegjs parser, causing the editor to be unresponsive. On my machine, adding a repo at `~/.git` (which I suspect is the most common case of this) results in output that is 621144 lines long, which caused the editor to completely freeze.

One option is to switch away from using the parser in this case and do something slightly more manual and fine-tuned; another is to detect very large repos (or odd cases like a repo in `~/.git`) and confirm that the user even wants to attempt to use the integration for that particular repo (and then deal with performance issues from that point).

I have a hunch this might be related to #953 and possibly #958 

/cc @kuychaco

**Comment by smashwilson** [comment]
Maybe we could put a timeout on the git calls, and treat the repository as "large" if they expire?

**Comment by serafeimgr** [comment]
Interesting, i have one question though.
--porcelain does not seems to take a value, am i missing something here?

**Comment by Arcanemagus** [comment]
@serafeimgr `--porcelain` definitely takes a [version argument](https://git-scm.com/docs/git-status#git-status---porcelainltversiongt).

**Comment by BinaryMuse** [comment]
It's likely your system Git is just older than the new v2 porcelain
version. The package ships with it's own version of Git.

**Comment by serafeimgr** [comment]
i thought it uses the one mentioned in `apm --version`, which is the same as the one installed in my system.
thanks for the clarification

**Comment by BinaryMuse** [comment]
We bundle Git using [dugite](https://github.com/desktop/dugite) (which uses [dugite-native](https://github.com/desktop/dugite-native)) specifically to avoid version issues.

**Comment by serafeimgr** [comment]
Thanks for the info, i will have a look.
