### ISSUE TITLE
Uncaught TypeError: Cannot read property 'domNode' of undefined

### ISSUE THREAD

**Issue by heitormejias** [atom/github#965]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'domNode' of undefined

```
At /usr/share/atom/resources/app/node_modules/github/node_modules/etch/lib/patch.js:5

TypeError: Cannot read property 'domNode' of undefined
    at patch (/usr/share/atom/resources/app/node_modules/github/node_modules/etch/lib/patch.js:5:39)
    at updateSync (/usr/share/atom/resources/app/node_modules/github/node_modules/etch/lib/component-helpers.js:108:26)
    at /usr/share/atom/resources/app/node_modules/github/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (/usr/share/atom/resources/app/node_modules/github/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
     -4:25.1.0 git-control:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -2:35.6.0 core:confirm (atom-pane.pane)
  3x -1:31.6.0 git-control:toggle (atom-pane.pane)
     -1:23.1.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -1:02.8.0 github:toggle-git-tab (div.tool-panel.tree-view)
  8x -0:48.5.0 git-control:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:13.8.0 github:toggle-git-tab (atom-pane.pane)
```

### Non-Core Packages

```
atom-typescript 11.0.3 
busy-signal 1.4.3 
git-control 0.9.0 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.1 
pretty-json 1.6.3 
```

**Comment by BinaryMuse** [comment]
Hi there!

Your issue doesn't include any steps to reproduce this issue. Please feel free to reopen this issue with more information. In addition, it'd be very helpful to know if the issue still happens if you run Atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). Thanks for meeting us halfway!

**Comment by zzjin** [comment]
I can reproduce this issue when change projects root path, when using packages like package `project-plus` and `project-manager` to change projects

**Comment by MxRay** [comment]
I can confirm [zzjin's discovery](https://github.com/atom/github/issues/965#issuecomment-323991616"). Same thing happened to me while switching projects via `project-manager`
