### ISSUE TITLE
ordering changed - now less convenient

### ISSUE THREAD

**Issue by nebulousdog** [atom/github#969]
ordering is wonky now, or at least, not convenient.

the first choice used to be "Open on Github: File", but now it is `Github: Pull`
![screen shot 2017-06-22 at 2 25 43 pm](https://user-images.githubusercontent.com/2218331/27456687-d6ba8de0-5756-11e7-8d23-cdabef4eaa4f.png)

```
$ apm list | grep github
├── github@0.3.3
├── open-on-github@1.2.1
```

**Comment by Arcanemagus** [comment]
This package has nothing to do with the ordering there, you want [`atom/command-palette`](https://github.com/atom/command-palette/issues).

**Comment by nebulousdog** [comment]
ok closing, ty!
