### ISSUE TITLE
Github integration freezing editor and hangs PC upon launch

### ISSUE THREAD

**Issue by MandarSant** [atom/github#973]
### Description
The new V of Atom(1.8) hangs my pc and editor also freezes when ever i start editor I have press restart button to get out of it

**Expected behavior:**

[Run clearly without freezing and hanging pc]

**Actual behavior:**

[Freezes editor and hangs pc]

**Reproduces how often:**

every time,not able to use editor

### Versions

OS:-Win 8.1 WMC
Atom :- Latest

**Comment by 50Wliu** [comment]
@MandarSant thanks for creating a new issue.  Can you answer @ungb's questions [here](https://github.com/atom/github/issues/955#issuecomment-310504162) and mine [here](https://github.com/atom/github/issues/955#issuecomment-310561810)?  Thanks!

**Comment by MandarSant** [comment]
@50Wliu no any `.dmp` file

**Comment by MandarSant** [comment]
@50Wliu .......?????

**Comment by MandarSant** [comment]
@50Wliu  as per this relpy by @jeremyott  in  #14446 atom works well I tried it 

This is probably not the right place for this comment, but I was running into similar issues following 1.18.0 update. Not sure if the github integration was recently added to the core packages, but it was crashing my editor upon launch almost every time. I disabled the github-integration core package and no more timeouts/crashes.

**Comment by MandarSant** [comment]
@50Wliu @ungb 
                                           
Built-in Atom Packages (91)                             
├── atom-dark-syntax@0.28.0                             
├── atom-dark-ui@0.53.0                                 
├── atom-light-syntax@0.29.0                            
├── atom-light-ui@0.46.0                                
├── base16-tomorrow-dark-theme@1.5.0                    
├── base16-tomorrow-light-theme@1.5.0                   
├── one-dark-ui@1.10.4                                  
├── one-light-ui@1.10.4                                 
├── one-dark-syntax@1.7.1                               
├── one-light-syntax@1.7.1                              
├── solarized-dark-syntax@1.1.2                         
├── solarized-light-syntax@1.1.2                        
├── about@1.7.6                                         
├── archive-view@0.63.2                                 
├── autocomplete-atom-api@0.10.1                        
├── autocomplete-css@0.16.2                             
├── autocomplete-html@0.8.0                             
├── autocomplete-plus@2.35.4                            
├── autocomplete-snippets@1.11.0                        
├── autoflow@0.29.0                                     
├── autosave@0.24.3                                     
├── background-tips@0.27.0                              
├── bookmarks@0.44.4                                    
├── bracket-matcher@0.85.5                              
├── command-palette@0.40.4                              
├── dalek@0.2.1                                         
├── deprecation-cop@0.56.7                              
├── dev-live-reload@0.47.1                              
├── encoding-selector@0.23.4                            
├── exception-reporting@0.41.4                          
├── find-and-replace@0.208.3                            
├── fuzzy-finder@1.5.8                                  
├── github@0.3.3                                        
├── git-diff@1.3.6                                      
├── go-to-line@0.32.1                                   
├── grammar-selector@0.49.5                             
├── image-view@0.61.2                                   
├── incompatible-packages@0.27.3                        
├── keybinding-resolver@0.38.0                          
├── line-ending-selector@0.7.1                          
├── link@0.31.3                                         
├── markdown-preview@0.159.12                           
├── metrics@1.2.5                                       
├── notifications@0.67.2                                
├── open-on-github@1.2.1                                
├── package-generator@1.1.1                             
├── settings-view@0.249.4                               
├── snippets@1.1.4                                      
├── spell-check@0.71.4                                  
├── status-bar@1.8.11                                   
├── styleguide@0.49.6                                   
├── symbols-view@0.116.0                                
├── tabs@0.106.2                                        
├── timecop@0.36.0                                      
├── tree-view@0.217.1                                   
├── update-package-dependencies@0.12.0                  
├── welcome@0.36.4                                      
├── whitespace@0.36.2                                   
├── wrap-guide@0.40.2                                   
├── language-c@0.58.0                                   
├── language-clojure@0.22.2                             
├── language-coffee-script@0.48.7                       
├── language-csharp@0.14.2                              
├── language-css@0.42.2                                 
├── language-gfm@0.89.0                                 
├── language-git@0.19.1                                 
├── language-go@0.44.0                                  
├── language-html@0.47.2                                
├── language-hyperlink@0.16.1                           
├── language-java@0.27.1                                
├── language-javascript@0.126.1                         
├── language-json@0.19.1                                
├── language-less@0.32.0                                
├── language-make@0.22.3                                
├── language-mustache@0.14.1                            
├── language-objective-c@0.15.1                         
├── language-perl@0.37.0                                
├── language-php@0.38.0                                 
├── language-property-list@0.9.1                        
├── language-python@0.45.2                              
├── language-ruby@0.71.0                                
├── language-ruby-on-rails@0.25.2                       
├── language-sass@0.59.0                                
├── language-shellscript@0.25.0                         
├── language-source@0.9.0                               
├── language-sql@0.25.5                                 
├── language-text@0.7.2                                 
├── language-todo@0.29.1                                
├── language-toml@0.18.1                                
├── language-xml@0.35.0                                 
└── language-yaml@0.29.0                                
                                                        
Community Packages (20) C:\Users\Mandar\.atom\packages  
├── atom-live-server@2.1.2                              
├── busy-signal@1.4.3                                   
├── emmet@2.4.3                                         
├── file-icons@2.1.7                                    
├── highlight-selected@0.13.1                           
├── intentions@1.1.2                                    
├── linter@2.2.0                                        
├── linter-csslint@1.3.4                                
├── linter-eslint@8.2.1                                 
├── linter-htmlhint@1.3.3                               
├── linter-ui-default@1.6.2                             
├── minimap@4.28.2                                      
├── minimap-bookmarks@0.4.2                             
├── minimap-cursorline@0.2.0                            
├── minimap-find-and-replace@4.5.2                      
├── minimap-highlight-selected@4.6.1                    
├── minimap-pigments@0.2.2                              
├── pigments@0.39.1                                     
├── platformio-ide-terminal@2.5.1                       
└── split-diff@1.4.3

**Comment by MandarSant** [comment]
@rsese how will i know that other packages are afecting lode time of editor bcoz after disabling  the github package some minor improve is seen but still freezes

**Comment by ungb** [comment]
If you are on windows, another known issue is spell-check package https://github.com/atom/spell-check/issues/190 which there is a fix that is currently being worked on for. 

You can see which package impact startup load time if you open time cop.

**Comment by MandarSant** [comment]
@ungb Reduced the load and freezing time but still freezes and hangs pc

**Comment by rsese** [comment]
Based on your comment [above](https://github.com/atom/github/issues/973#issuecomment-312423813), it sounds like you disabled the GitHub package and restarted but Atom still freezes for you @MandarSant?

If so, can you confirm if it only freezes with a particular project open or do you see the same problem with any project or with no project open?

**Comment by MandarSant** [comment]
@rsese Yes,I confirmed editor freezes with any project and also with no project open and
 **Specialy hangs my pc also**

**Comment by ungb** [comment]
@MandarSant Sorry, one last thing to try to verify if it's due to a 3rd party package or not is if you can run atom in safe mode?

`atom --safe`  <-- to run in safe mode on cmd.

**Comment by ungb** [comment]
oh I see that you said you already tried it... I'm not seeing these issues on my windows box.  Let me try on windows 8.1 instead of windows 10.

**Comment by MandarSant** [comment]
@ungb When I encountered [THIS](https://discuss.atom.io/t/installiing-packages-through-command-line/44465) issue I reinstalled Atom without any packages so still that also didnt worked

**Comment by ungb** [comment]
@MandarSant are you still seeing this issue with github package on latest stable atom release?

**Comment by MandarSant** [comment]
@ungb a very big YESsssssssss

**Comment by ungb** [comment]
@MandarSant, when you run `apm disable github` from powershell and start atom, are you still seeing this?

**Comment by MandarSant** [comment]
I permanentaly disable github when it was launched i from then i use **git bash**

**Comment by MandarSant** [comment]
@ungb  no any reply...?????

**Comment by ungb** [comment]
@MandarSant Sorry for not replying earlier.  We're still waiting for more info on this as none of us are able to repro this very issue.  

Is this when you open only a git project or happens just because the package is enabled?  I've never seen this before on windows.

**Comment by MandarSant** [comment]
@ungb  this happens both the  ways enable and disabled but disabled decreases the time

**Now i think you should come to my home to repair the defect**
