### ISSUE TITLE
Add multiple projects to git

### ISSUE THREAD

**Issue by anuj9196** [atom/github#974]
I have a multiple git projects added in atom editor.

I want to manage them all separately and in-built git feature to be able to fetch all git projects.

I only add first project to manage.

I opened a new project with separate git project. But still it binds with previous project.

I moved new project to top. Still it have previous project.

Any help?

**Comment by smashwilson** [comment]
The easiest way to change the active git repository is to open a file in the project you want to interact with. We follow the "active pane item" in your workspace to determine the git context in ambiguous situations.

Hope this helps!
