### ISSUE TITLE
Atom freezes with over 125000 Unstaged Changes in the Git Panel

### ISSUE THREAD

**Issue by Yessengerey** [atom/github#984]
### Description

After the latest update, with the introduction of Git/Github panels, Atom gets extremely laggy and eventually freezes and dies due to over 125000 unstaged changes in the Git panel. I have searched through some of the similar Closed issue threads however I did not find a solution for my problem, so please help!

### Steps to Reproduce

1. Open a file or a directory with Atom **on C: drive.**
2. Wait for a few seconds (or open the Git panel) and let the lags begin
3. Try to look through some of the Unstaged Changes until Atom stops responding completely or an Alert pops up informing you that Atom has stopped responding.

**Expected behavior:**

Atom Editor was expected to be working as normal. Since I was opening just a file or a folder (not a Git Repository) there were expected to be no Unstaged Changes at all.

**Actual behavior:**

Over 125000 .atom and .config files and other files got listed as Unstaged Changes

**Reproduces how often:**

This issue appears **every** time I open a file or a folder on C: drive.

### Versions

**atom --version**:
Atom : 1.18.0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0

**apm --version**:
apm 1.18.1
npm 3.10.10
node 6.9.5 x64
python
git 2.13.0.windows.1
visual studio 2015

### Additional Information

> Some have suggested removing **.git folder** from .atom folder, however I seem to not have that .git folder, so I suppose removing it is not an option.

> Removing and re-installing Atom does not help eiter

(https://user-images.githubusercontent.com/9358796/27516719-29b6f88a-59e1-11e7-946c-0968f5bfe5a3.PNG)

**Comment by smashwilson** [comment]
> Some have suggested removing .git folder from .atom folder, however I seem to not have that .git folder, so I suppose removing it is not an option.

Try looking for a `.git` directory in your home directory, instead - the folder that contains the `.atom` directory.

**Comment by Yessengerey** [comment]
@smashwilson Oh right! .git seems to have been a hidden folder. Just found it in the parent directory to .atom and removed it. The issue seems to have stopped. Thank you very much!

**Comment by veranyc** [comment]
Many thanks for posting this issue and resolution!
