### ISSUE TITLE
Pull/Push aways requires authentication

### ISSUE THREAD

**Issue by mattberan** [atom/github#993]
How can I set up atom so I don't have to authenticate on each pull/push/fetch

**Comment by smashwilson** [comment]
:wave:

This is definitely on our radar. In the meantime, you should be able to configure a [credential helper](https://help.github.com/articles/caching-your-github-password-in-git/) for git that will remember https credentials in your OS keychain.

We're tracking this in #861, so subscribe over there for updates :smile:
