### ISSUE TITLE
Save Authentication Credentials by GitHub Usernames

### ISSUE THREAD

**Issue by EmpireWorld** [atom/github#994]
We need to save the Authentication credentials for all time or a part time.

It is hard to use when we are restricted to enter the credentials each time we want to a push, pull or fetch.

Thanks.

**Comment by smashwilson** [comment]
:wave:

This is definitely on our radar. In the meantime, you should be able to configure a [credential helper](https://help.github.com/articles/caching-your-github-password-in-git/) for git that will remember https credentials in your OS keychain.

We're tracking this in #861, so subscribe over there for updates :smile:
