### ISSUE TITLE
List of commands for keybindings

### ISSUE THREAD

**Issue by theramiyer** [atom/github#995]
Hi!

It's great to have GitHub baked right into Atom!

It would be better if we could get a list of commands supported by the GitHub core package, so that we could set keybindings as per our convenience. For instance, the "GitHub: Stage All Changes". We can see from the `git.cson` file a few commands, but the others are not listed anywhere.

Could you please add some help on that?

Thanks,
Ram

**Comment by kuychaco** [comment]
Hi @theramiyer, to see a list of active keybindings you can go to the `github` package settings:

<img width="616" alt="settings_ ___github_github" src="https://user-images.githubusercontent.com/7910250/27878431-1834cb66-6173-11e7-82c3-b0b2dbc16216.png">

One way to quickly see a list of all the commands in the github package and their associated keybindings is to use the command palette (cmd-shift-p) and type "github". 

<img width="670" alt="staging-view_js_ ___github_github" src="https://user-images.githubusercontent.com/7910250/27878298-9abd135a-6172-11e7-85f6-5f7f7fbd58d3.png">

Note that focus within the editor impacts the commands that appear. For example, the commands available when a file is focused are different than those available when the Git panel is focused. 

You can add your own custom keybindings to commands or re-map existing ones by adding them to your `keymap.cson` file.
