### ISSUE TITLE
Atom Git fails to use credential-osxkeychain from .gitconfig on Mac OS X

### ISSUE THREAD

**Issue by aterenin** [atom/github#998]
### Description

On Mac OS X, Atom does not correctly use username and password stored in keychain.

### Steps to Reproduce

1. Add `[credential]` and `helper = osxkeychain` to `.gitconfig`.
2. Clone a Git repository from GitHub using https.
2. Run `git pull` from the terminal at least once and enter username/password.
4. Run `git pull` again. This time it will not ask for a password, and will use the one in the keychain.
5. Open Atom and try to use `git pull`. Atom will ask for a password.

**Expected behavior:**

In Atom, `git pull` works without prompting username of password.

**Actual behavior:**

Atom asks for Git username and password, even if it is correctly stored in keychain and `git pull` works from the command line without prompting for anything.

### Versions

1.18.0 x64 on Mac OS X

### Additional Information

There is no such issue when using ssh keys, because in this scenario `credential-osxkeychain` is not used, so is a https-only issue. May be related to #932, as user.name and user.email both involve `.gitconfig`.

**Comment by smashwilson** [comment]
Can you give the `${PATH}` solution in https://github.com/atom/github/issues/436#issuecomment-307370841 a try?

**Comment by aterenin** [comment]
Confirmed that adding `export PATH=${PATH}:$(git --exec-path)` to `.profile` makes Git work correctly in Atom.

**Comment by Pageboy** [comment]
Can someone explain where .profile is exactly? or is this a bash command?

**Comment by aterenin** [comment]
`.profile` is a text file located in your home directory that contains terminal commands that are executed every time a terminal window is opened - here, the we add `git --exec-path` to PATH. Hopefully it's an easy fix in Atom - while the workaround is acceptable, I don't like to add things to my PATH that don't need to be there.

**Comment by Pageboy** [comment]
Still doesn't work for me. How does Atom know to run terminal? I put .profile in ~ and added `export PATH=${PATH}:$(git --exec-path)` is there anything else that needs to be in there? Do I need to restart the MAC?

**Comment by dietrichliko** [comment]
It seems that this version of Atom is using its own version of git

`/Applications/Atom.app/Contents/Resources/app/node_modules/dugite/git/`

which misses `git-credential-osxkeychain`

You can create a link to 

`ln -s /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-credential-osxkeychain /Applications/Atom.app/Contents/Resources/app/node_modules/dugite/git/libexec/git-core/`

which works in my case

**Comment by smashwilson** [comment]
This particular case should be fixed by #1057 :sparkles:
